function h(b){throw b;}var i=void 0,k=!0,q=null,r=!1;function s(){return function(){}}function t(b){return function(){return this[b]}}function v(b){return function(){return b}}Kinetic.t={};var aa=q;window.egame=q;window.onload=function(){aa=new ba;window.egame=aa};WebFontConfig={google:{families:["Nunito::latin","Doppio+One::latin","Nobile:400,700:latin","Galindo::latin"]}};var w=document.createElement("script");w.src=("https:"==document.location.protocol?"https":"http")+"://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js";
w.type="text/javascript";w.async="true";var ca=document.getElementsByTagName("script")[0];ca.parentNode.insertBefore(w,ca);
function ba(){function b(){j.a("Game.loadingSounds");var a=q,b=q;z.debug("Loading sounds...","game");var e=new PreloadJS(r);e.onComplete=function(){clearInterval(a);b=setInterval(function(){j.a("Game.updateImageLoading",{progress:da.ad()})},50);z.debug("Sounds loaded.","game");j.a("Game.loadingImages");da.md(function(){clearInterval(b);j.a("Game.updateImageLoading",{progress:1});z.debug("Images loaded.","game");setTimeout(function(){j.a("Game.loadingDone");g.start()},E?0:1E3)})};e.installPlugin(SoundJS);
a=setInterval(function(){j.a("Game.updateSoundLoading",{progress:e.progress})},50);G.Bd(c);j.on(ia,function(){G.Ld()},"game");e.loadManifest(G.bd())}var a=new ja;K.Ad();this.applySettings=function(){a.apply();$.cookie("monkeyWorldSettings",JSON.stringify(K.sa()))};this.hideSettings=function(){a.hide()};this.showSettings=function(){a.show()};var c=new Kinetic.Stage({container:"container",width:1010,height:660});c.If=c.getWidth()/1024;var d=new Kinetic.Layer,f=new Kinetic.Layer,e=new Kinetic.Layer;
c.add(d);c.add(f);c.add(e);c.Dc=d;c.U=f;c.Ec=e;c.Fc=f;c.Mf=t("U");c.Lf=t("Dc");c.Nf=t("Ec");c.na=r;c.Jf=0;c.Hf=0;c.Ob=function(){c.na=k};var g=new ka(c),j=g.j,n=function(){var a=0,b=new Kinetic.Text({text:"",fontFamily:"Arial",textFill:"black",textStroke:"white",textStrokeWidth:1,fontSize:18,x:0,y:0}),c=k;j.on(la,function(){c?(console.info("Turning off FPS display"),f.remove(b),c=r):(console.info("Turning on FPS display"),f.add(b),c=k)},"game");f.add(b);return{Ed:function(c){if(0==a||10<c.time-a)b.setText("FPS: "+
Math.round(1E3/c.timeDiff)),a=c.time}}}();c.onFrame(function(a){E&&n.Ed(a);j.a("frame",{frame:a});f.draw();c.na&&(e.draw(),c.na=r);Tween.tick(a.timeDiff,r)});c.start();j.on("Game.miniGameListenersInitiated Game.viewInitiated",function(){f.moveToTop();e.moveToTop()},"game");d=E?0:2E3;j.a("Game.showLoadingScreen",{time:d});setTimeout(function(){b()},d);this.Tb=function(){g.Tb()}}
var L="frame",ia="TRIGGER_SUBTITLES",ma="TRIGGER_SCORE",la="TRIGGER_FPS",na="backendScoreUpdateMode",oa="setPitcherLevelBefore",pa="setPitcherLevelSetDropOrigin",qa="INTRODUCE_AGENT",ra="MG_LADDER_PLACE_TARGET",xa="MG_LADDER_HELPER_APPROACH_TARGET",ya="MG_LADDER_PICKED",za="MG_LADDER_ALLOW_INTERRUPT",Aa="MG_LADDER_FORBID_INTERRUPT",Ba="MG_LADDER_READY_TO_PICK",M="MG_LADDER_RESET_SCENE",Ca="MG_LADDER_GET_TARGET",Da="MG_LADDER_HAS_TARGET",Ea="MG_LADDER_CONFIRM_TARGET",Fa="MG_LADDER_CHEER",Ga="MG_LADDER_IGNORE_INPUT",
N="MG_LADDER_ACKNOWLEDGE_INPUT",Ha="MG_LADDER_FORBID_GAMER_INPUT",O="MG_LADDER_ALLOW_GAMER_INPUT",Ia="MG_LADDER_GET_TREAT",Ja="MG_LADDER_INTERRUPT",Ka="MG_LADDER_START_AGENT";
function La(){var b={},a=[],c=0;this.Fa=v("GameEventManager");this.on=function(a,c,e){for(var a=a.split(" "),g=0;g<a.length;g++)a[g]in b||(b[a[g]]=[]),b[a[g]].push(c),c.J=e,z.debug((e===i?"unnamed":e)+" registerd "+a[g],"evm")};this.off=function(a,c){for(var e=0;e<b[a].length;e++)b[a][e].J===c&&b[a].splice(e,1);0==b[a].length&&delete b[a]};this.print=function(){console.log("-------EVENT MANAGER STATE-----------------");for(var a in b){console.log("key: "+a);for(var c=0;c<b[a].length;c++)console.log("   "+
b[a][c].J)}console.log("-------------------------------------------")};this.u=function(d){if(0<c)a.push(d);else{var f=0,e;for(e in b){for(var g=b[e].length,j=0;j<g;j++)b[e][j].J===d&&(b[e].splice(j,1),j--,g--,f++);0==b[e].length&&delete b[e]}z.debug("Forgot "+f+" event registred by "+d,"evm")}};this.a=function(d,f,e){c++;d=b[d];if(d!=i)for(var g=0;g<d.length;g++){var j=d[g];e!=i&&e&&z.debug("      "+d[g].J);j(f)}c--;if(0==c&&0<a.length){for(g=0;g<a.length;g++)this.u(a[g]);a=[]}};this.$b=function(d,
f,e,g){c++;e=b[e];if(e!=i)for(var j=0;j<e.length;j++){var n=e[j];z.debug("      "+e[j].J);n(d,g);f||d()}c--;if(0==c&&0<a.length){for(j=0;j<a.length;j++)this.u(a[j]);a=[]}};this.q=function(a,c,b){this.$b(c,k,a,b)}}var E=r;Kinetic.jb=s();Kinetic.jb.getWidth=s();
function P(b){this.l=b;var a=this;document.onkeypress=function(c){117===c.keyCode?a.a(ia):105===c.keyCode?a.a(ma):111===c.keyCode?a.a(la):115===c.keyCode?a.a("setPitcherLevel",{callback:s()}):console.info("Unhandles key: "+c.keyCode)};this.on=function(a,b,f){this.j.on(a,b,f===i?this.l:f)};this.off=function(a,b){this.j.off(a,b===i?this.l:b)};this.u=function(a){this.j.u(a===i?this.l:a)};this.a=function(b,d,f){f!=i&&f&&z.debug("Out: "+b,a.l);this.j.a(b,d,f)};this.q=function(b,d,f){z.debug("Out: "+b,
a.l);this.j.q(b,d,f)};this.Vb=function(b,d,f){return function(e){z.debug("Out: "+d,a.l);a.j.$b(e,b,d,f)}};this.Ub=function(b){return a.Vb(r,b,i)};this.M=function(b,d){return a.Vb(k,b,d)};this.Fa=function(){console.log(this.j.Fa())};this.Zb=function(a){this.l=a}}P.prototype.j=new function(){this.Fa=v("NoEventManager");this.on=s();this.a=s();this.off=s();this.u=s()};P.prototype.e=new Kinetic.jb;P.prototype.b=q;
function Ma(){var b=[];this.Rb=function(a){b.push(a)};this.Y=function(a){var c=a-1;(0>c||c>=b.length)&&h("MonkeyWorld.NoSuchRoundException ("+a+")");return b[c]}}function Na(){var b=r,a=[];this.ya=function(){z.debug("Got mistake report","game");b=k};this.Lb=function(){return b};this.sd=function(b){a.push(b)};this.wa=function(){a.splice(a.length-1)};this.Vc=function(){return a}}
function Oa(){this.Rb=function(){h("MonkeyWorld.NoMiniGameResultException")};this.Y=function(){h("MonkeyWorld.NoMiniGameResultException")}}
function Pa(b){P.call(this,b);var a=this,c=new function(){var a=[];this.setTimeout=function(b,c){var d=setTimeout(b,c);a.push(d);return d};this.setInterval=function(b,c){var d=setInterval(b,c);a.push(d);return d};this.clearTimeout=function(b){a.remove(b);clearTimeout(b)};this.clearInterval=function(b){a.remove(b);clearInterval(b)};this.Ca=function(){for(var b=0;b<a.length;b++)clearTimeout(a[b]);delete a;a=[]}},d=[],f=[];this.k=function(a){d.push(a)};this.p=function(){d===q&&h({name:"MW.TearDownAlreadyCalledException",
message:"This module ("+b+") has already been teared down."});c.Ca();a.u();for(var e=0;e<d.length;e++)d[e](),d[e]=q;d=q};this.m=function(a){f.push(a)};this.v=function(){f===q&&h({name:"MW.SetupAlreadyCalledException",message:"This module ("+b+") has already been setted up."});for(var a=0;a<f.length;a++)f[a](),f[a]=q;f=q};this.setTimeout=function(a,b){return c.setTimeout(a,b)};this.setInterval=function(a,b){return c.setInterval(a,b)};this.clearTimeout=function(a){c.clearTimeout(a)};this.clearInterval=
function(a){c.clearInterval(a)}}
var K=new function(){var b={global:{language:{g:"en"},monkeySeeRounds:{g:1},triesBeforeGuardianAngel:{g:3}},miniGames:{fishingGame:{targetNumber:{g:2},numberCorrect:{g:1},numberOfFish:{g:7},maxNumber:{g:9}},ladder:{targetNumber:{g:-1}}}};this.sa=function(){return b};this.get=function(a){for(var c=b,d=0;d<arguments.length;d++)c=c[arguments[d]];return c.g};this.set=function(a){for(var c=b,d=0;d<arguments.length-1;d++)c=c[arguments[d]];c.g=arguments[arguments.length-1]};this.Ad=function(){var a=JSON.parse($.cookie("monkeyWorldSettings"));
a!==q&&(b=a)};this.yd=function(a,c){for(var d=a.split("-"),f=b,e=0;e<d.length;e++)f=f[d[e]];f.g=c}};
function ja(){function b(a,c){for(var e in a)if("object"===typeof a[e]&&a[e].g===i)b(a[e],c+"-"+e);else if(a[e].g!=i){var d=$("#"+c+"-"+e).val();K.yd(c+"-"+e,d)}}function a(){$("#settings-panel").append('<div id="settings-panel-content">');e=$("#settings-panel-content");e.append("<h1>"+Q.get("SETTINGS_LABEL")+"</h1>");e.append("<form>");var a=f.sa(),b;for(b in a)e.append(d(b,2,"")),e.append(c(a[b],2,b));e.append("<button type=\"button\" onclick=\"window['egame']['hideSettings']()\">"+Q.get("SETTINGS_CANCEL")+
"</button>");e.append("<button type=\"button\" onclick=\"window['egame']['applySettings']();window['egame']['hideSettings']()\">"+Q.get("SETTINGS_APPLY")+"</button>");e.append("</form>");e.append("</div>")}function c(a,b,e){var f;f="<ul>";for(var l in a)if("object"===typeof a[l]&&a[l].g===i)f+=d(l,b+1,e),f+=c(a[l],b+1,e+"-"+l);else{f+="<li>";f+=d(l,b+1,e);var m="",m=m+('<input type="text" id="'+(e+"-"+l)+'" value="'+a[l].g+'" />');f+=m+"</li>"}return f+"</ul>"}function d(a,b,c){var e="",a="SETTINGS_"+
((c===i?"":c+"_")+a).toUpperCase().replace("-","_")+"_LABEL",a=Q.get(a);a!=q&&(e+="<h"+b+">"+a+"</h"+b+">");return e}var f=K,e=$("#settings-panel-content");this.apply=function(){var c=f.sa(),d;for(d in c)"object"===typeof c[d]&&b(c[d],d);e.remove();a()};this.show=function(){a();$("#settings-panel").show()};this.hide=function(){e.remove();$("#settings-panel").hide()}}function Qa(){}function Ra(){}
function Sa(b){Pa.call(this,"AgentChooser");var a=[{ua:Qa,view:Ta},{ua:Ra,view:R},{ua:Qa,view:Ta},{ua:Qa,view:Ta}];this.Wc=function(){return a};this.Qc=function(a){b(a)}}function S(b,a){this.Zc=function(){return b};this.$c=function(){return a}}
function ka(b){function a(a){if(p&&!E){var b=m(Ua,function(e){e?(b.p(),a()):(b.p(),c(a))});b.v();u.a("Game.viewInitiated")}else c(a)}function c(a){if(p&&!E){var b=m(Va);b.v();u.a("Game.viewInitiated");u.a("Game.demonstrateGarden",{callback:function(){b.p();a()}})}else a()}function d(a){function b(){U=0;u.a("resetPitcherLevel");c.p();u.a("Game.gardenWatered");a!=i&&a()}if(p){var c=m(Va);c.v();u.a("Game.waterGarden",{callback:function(){b()}})}else b()}function f(){u.a("Game.stopMiniGame");p&&sa.p();
B.stop();B.p();delete B;V=0;B=D;u.a("miniGameDone")}function e(){function a(){if("Monkey Do"===y){var b=ea.Y(fa).Vc();B.play(H,b)}else B.play(H);u.a("miniGameStarted",{},k)}u.j.print();ta();B.v();p&&(ga=m(ua,B),ga.v(),u.a("Game.miniGameListenersInitiated"));u.a("miniGameInitiated",{},k);p?u.q(qa,a):a()}function g(a){if(0<C.length){var b=C[0];C.splice(0);var c=b.Zc();va=c;ta=function(){B=m(c.b);ua=c.view};a();o(b.$c())}else u.a("Game.showMiniGameChooser",{callback:function(b){va=b;ta=function(){u.a("Game.hideMiniGameChooser");
B=m(b.b);ua=b.view};a();o(J)},Uc:Wa})}function j(){ea=new Ma;H=A;y="Child Play";g(function(){p&&(console.log("cre\u00e4tar minigamehandlerviwe"),sa=m(Xa),sa.v());n(0);e()})}function n(a){V=a;u.a("backendScoreGameUpdateMiniGame",{xd:V})}function o(a){u.a("learningTrackUpdate",{ld:a},k)}function l(a){a>K.get("global","monkeySeeRounds")&&("Monkey See"===y||"Monkey Do"===y)&&h("MonkeyWorld.MiniGameRoundOverMaxLimit");1>a&&h("MonkeyWorld.MiniGameRoundUnderMinLimit");fa=a}function m(a,c){a.prototype.j=
u.j;a.prototype.b=u;a.prototype.e=b;var e=q;return e=c===i?new a:c!=i?new a(c):new a(c,i,i,i)}var p=k,x=!E,u=this;P.call(this,"Game");this.j=new La;this.e=b;this.b=this;var D=new Ya,I=new Oa,A=m(Za),F=m($a),J=new ab,W=new bb,ha=new cb,y="Child Play",B=D,ua=q,ga=q,sa=q,ta=q,H=A,fa=1,ea=I,V=0,va=q,U=0,wa=q,C=[];p===i&&(p=k);x===i&&(x=k);p&&m(db);this.nd=function(){B===D&&h({name:"MonkeyWorld.NoActiveMiniGameException",message:"There is no active minigame"});p&&(console.log("Tear down: ",ga),ga.p());
n(V+B.Xc());if("Child Play"===y)y="Monkey See",e();else if("Monkey See"===y){var a=B.Y();ea.Rb(a);y="Monkey Do";H=F;e()}else if("Monkey Do"===y)if(fa===K.get("global","monkeySeeRounds")){l(1);y="Child Play";H=A;f();var a=va,b=V;26<b&&30>=b?(C.push(new S(a,ha)),C.push(new S(a,ha))):22<b&&26>=b?(C.push(new S(a,W)),C.push(new S(a,W)),C.push(new S(a,W))):0<=b&&22>=b?(C.push(new S(a,J)),C.push(new S(a.Pc.ec[0],J)),C.push(new S(a,J)),C.push(new S(a,J)),C.push(new S(a,J))):h("MW.NoSuchMinigameScore");j()}else l(fa+
1),e()};this.f=function(){return wa};this.start=function(){var b=q,c=q;a(function(){x?(b=m(Sa,function(a){b.p();c!=q&&c.p();wa=new a.view;j()}),p&&(c=m(eb,b),c.v(),u.a("Game.viewInitiated"))):(wa=new R,j())})};this.stop=function(){f();y="Child Play";l(1);H=A;ea=I;this.a("Game.stop")};this.Tb=function(){this.stop();this.start()};this.Lc=function(a){u.a(oa);u.a("setPitcherLevel",{callback:function(){6===U?d(a):a!=i&&a()}});U+=1};this.cd=function(){return U};this.Wb=function(){H=F};this.Xb=function(){H=
A};this.Nb=function(){return H===A};this.Mb=function(){return H===F};this.ca=function(){return"Child Play"===y};this.ba=function(){return"Monkey See"===y};this.d=function(){return"Monkey Do"===y}}function cb(){}cb.prototype.name=v("Fast");function bb(){}bb.prototype.name=v("Medium");function ab(){}ab.prototype.name=v("Regular");
function fb(){function b(){D=r;g.b.d()&&g.a(Aa)}function a(a){D=k;g.b.d()&&!g.i()?g.q(za,a):a()}function c(){l=T.X(j,n);I+=1;T.pa(g.M(ra),function(){g.a(Ba);g.a(N,{},k);g.b.d()||g.a(O,{},k)})()}function d(a){u=k;console.log("gotCorrectTarget");T.pa(g.M(Ca),g.M(M),g.Ub(Da),function(){g.ub("correct");u=r;a()})()}function f(a){console.log("gotIncorrectTarget");g.q(M,function(){g.a(N,{},k);g.b.d()||g.a(O);g.ya();g.a("Ladder.incorrect");4<=F&&g.a("Ladder.agentSuggestSolution");g.ub("incorrect");a()})}
function e(){var a=3<=p,b=1<=x;3===x||a&&b?g.q(Fa,g.wd):c()}gb.call(this,"Ladder");var g=this,j=1,n=6,o=[],l=T.X(j,n),m=q,p=0,x=0,u=r,D=r,I=0,A=0,F=0;g.m(function(){var a,b=0;for(a=j;a<=n;a+=1)o[b]=a,b+=1});this.va=function(){x+=1;g.b.ca()?(g.q(Ea),g.q(Ia,e)):(g.a(Ea),g.b.Lc(e))};this.o=function(c){m=c;p+=1;T.pa(a,g.M(ya,{Of:c,Kf:c===l}),g.Ub(Ga),function(a){F=g.h()?F+1:0;g.h()&&c===l&&g.ed();a()},function(a){c===l&&(c<A&&(g.i()||g.h()))&&g.a("Ladder.betterBecauseSmaller");c===l&&(c>A&&(g.i()||g.h()))&&
g.a("Ladder.betterBecauseBigger");c!==l&&(g.i()||g.h())&&g.a("Ladder.hmm");g.b.d()&&(A=c);if(g.b.d()&&!g.h()||g.h()&&c===l)g.vd(),g.a(Ha,{},k);a()},g.M(xa),function(a){b();c===l?d(a):f(a);c<l&&(g.b.d()&&!g.i()&&!g.h())&&g.a("Ladder.agentTooLow");c>l&&(g.b.d()&&!g.i()&&!g.h())&&g.a("Ladder.agentTooHigh");c<l&&(g.b.ba()||g.i()||g.h())&&g.a("Ladder.tooLow");c>l&&(g.b.ba()||g.i()||g.h())&&g.a("Ladder.tooHigh");m=q})()};this.K=function(){return l};this.Hb=function(){var a=T.X(0,o.length-1);return o[a]===
l?this.Hb():o[a]};this.n=function(){m===q&&h({name:"No number chosen yet",b:"Ladder",message:"A chosen number was asked for in the Ladder Game, but no number has yet been chosen by the user or the agent."});return m};this.Z=function(){0===I&&h("MinigameNotStartedException");return I};this.qa=function(){return o};this.Ic(function(){D&&g.b.d()&&(b(),g.wa(),p-=1,u||(g.a(O,{},k),g.a(Ja,{}),g.q(M,function(){g.a(N,{},k)})))});this.Jc(function(){g.a(Ga,{},k);g.a(Ha,{},k);g.b.d()?g.q(Ka,c):c()});this.Kc(function(){g.a("Game.roundDone")})}
function gb(b){Pa.call(this,b);var a=this,c=[],d=[],f=r,e=r,g=q,j=10,n=q;this.ub=function(a){g.sd(a)};this.wa=function(){g.wa()};this.Jc=function(a){c.push(a)};this.Kc=function(a){d.push(a)};this.start=function(){f&&h({name:"MW.MinigameModuleAlreadyStarted",message:"This minigame module ("+b+") has already been started."});for(f=k;0<c.length;)c.shift()()};this.stop=function(){e&&h({name:"MW.MinigameModuleAlreadyStopped",message:"This minigame module ("+b+") has already been stopped."});for(e=k;0<
d.length;)d.shift()()};this.ya=function(){0<j&&(j--,a.a(na,{zb:j},k));g.ya()};this.Lb=function(){return g.Lb()};this.Y=function(){return g};this.Xc=function(){return j};this.wd=function(){z.debug("Round done","game");a.a("Game.roundDone");a.a("Game.nextRound");a.b.nd()};this.play=function(b,c){j=10;a.a(na,{zb:j},k);g=new Na;n=new b.ha[this.l](this,c);this.start()};var o=r,l=r,m=[];this.hd=function(){o=k;n.aa();a.b.Xb();for(var b=0;b<m.length;b+=1)m[b]()};this.Ic=function(a){m.push(a)};this.vd=function(){o=
r;a.b.Wb();n.ud()};this.i=function(){return o};this.dd=function(){l=k;a.b.Xb()};this.ed=function(){l=r;a.b.Wb()};this.h=function(){return l}}function Ya(){this.play=function(){h("No implemented mini game")}}Ya.prototype=new gb("NoMiniGame");var Wa=function(){var b={ze:{Af:{b:fb,view:hb,title:"Tree Game"},pf:{b:fb,view:ib,title:"Mountain Game"}}},a;for(a in b){var c=0,d=b[a],f=[],e;for(e in d)f.push(d[e]),d[e].Pc=d,c++;d.ec=f;d.Kd=function(){return c}}return b}();
function Za(){P.call(this,"GamerPlayer");this.Zb("GamerPlayer");z.debug("Creating GamerPlayer","player");this.ha=s();this.ha.Ladder=s()}
function $a(){z.debug("Creating MonkeyPlayer","player");P.call(this,"MonkeyPlayer");var b=this;this.ha=s();this.ha.Ladder=function(a,c){function d(b){e||(j++,setTimeout(function(){z.debug("Picking a number","agent");b===g||"incorrect"===c[b]?a.o(a.Hb()):a.o(a.K())},2E3))}z.debug("Applying MonkeyPlayer's strategy to the Ladder","player");var f=0,e=r,g=T.X(0,c.length-1);z.debug("Will make mistake on try number "+g+1,"agent");var j=0;b.on(Ba,function(){d(f++)});b.on("Ladder.incorrect",function(){a.i()||
(4>j?d(f++):4===j&&!a.h()&&(G.play(jb),a.dd()))});b.on("Ladder.correct",function(){j=0});this.aa=function(){z.debug("Interrupting agent","agent");e=k;j=0};this.ud=function(){z.debug("Resuming agent","agent");e=r};b.on(Da,function(){setTimeout(function(){a.va()},1500)});b.on("Game.stopMiniGame",function(){b.u()})}}
var kb={lf:"monkey.png",fc:"balloons.png",tf:"Symbol-Stop.png",sf:"Symbol-Check.png",I:"yesno/no1.png",bb:"yesno/no2.png",cb:"yesno/no3.png",eb:"yesno/no4.png",fb:"yesno/no5.png",gb:"yesno/no6.png",hb:"yesno/no7.png",ja:"yesno/yes1.png",N:"yesno/yes2.png",O:"yesno/yes3.png",ib:"yesno/yes4.png",qc:"Jungle_Bkg.png",be:"elephant.png",hf:"lion.png",qe:"giraff.png",oc:"bg-garden.png",pc:"bg-sadgarden.png",P:"minigames/treegame/background.png",Ac:"minigames/treegame/treedots.png",Q:"minigames/treegame/lizard_cover.png",
s:"minigames/treegame/lizard/lizard-standing.png",yc:"minigames/treegame/lizard/lizard-step1.png",ob:"minigames/treegame/lizard/lizard-step2.png",kb:"minigames/treegame/lizard/mouth-1.png",lb:"minigames/treegame/lizard/mouth-2.png",mb:"minigames/treegame/lizard/mouth-3.png",nb:"minigames/treegame/lizard/mouth-4.png",S:"minigames/treegame/lizard/tongue/tongue-1.png",pb:"minigames/treegame/lizard/tongue/tongue-2.png",qb:"minigames/treegame/lizard/tongue/tongue-3.png",rb:"minigames/treegame/lizard/tongue/tongue-4.png",
zc:"minigames/treegame/lizard/tongue/tongue-last.png",la:"minigames/treegame/lizard/hole/1.png",ma:"minigames/treegame/lizard/hole/2.png",R:"minigames/treegame/lizard/hole/3.png",sc:"minigames/treegame/nrpad.png",uc:"minigames/treegame/paket-1.png",vc:"minigames/treegame/paket-2.png",wc:"minigames/treegame/paket-3.png",ia:"buttons/wood.png",gc:"buttons/wood-selected.png",ic:"numbers/dots/prick-1.png",jc:"numbers/dots/prick-2.png",kc:"numbers/dots/prick-3.png",lc:"numbers/dots/prick-4.png",mc:"numbers/dots/prick-5.png",
nc:"numbers/dots/prick-6.png",$d:"moln.png",T:"vattendroppe.png",r:"vattenkanna.png",ka:"vattenkanna-botten.png",Za:"agents/mouse/normal.png",$a:"agents/mouse/normal-no-arm.png",Ya:"agents/mouse/head.png",Wa:"agents/mouse/facials/m-normal.png",Od:"agents/mouse/facials/m-glad.png",Pd:"agents/mouse/facials/m-suprised.png",Ta:"agents/mouse/dance/1.png",Ua:"agents/mouse/dance/2.png",Va:"agents/mouse/dance/3.png",Qa:"agents/mouse/facials/blink/1.png",Ra:"agents/mouse/facials/blink/2.png",Sa:"agents/mouse/facials/blink/3.png",
ab:"agents/mouse/facials/m-prat.png",Xa:"agents/mouse/falling.png",Ga:"agents/mouse/pointing/arm-1.png",Ha:"agents/mouse/pointing/arm-2.png",Ia:"agents/mouse/pointing/arm-3.png",Ja:"agents/mouse/pointing/arm-4.png",Ka:"agents/mouse/pointing/prickpek-1.png",La:"agents/mouse/pointing/prickpek-2.png",Ma:"agents/mouse/pointing/prickpek-3.png",Na:"agents/mouse/pointing/prickpek-4.png",Oa:"agents/mouse/pointing/prickpek-5.png",Pa:"agents/mouse/pointing/prickpek-6.png"},X={},da=function(){var b={},a=0,c=
0,d;for(d in X)a++;b.ad=function(){return c};b.md=function(b){z.debug("Loading images...","images");var e=0,d=Object.size(kb),j;for(j in kb){var n=kb[j];X[j]=new Image;X[j].onload=function(){++e>=d&&b();c=e/a};X[j].src="../res/img/"+n}};return b}();function Y(b,a,c){this.fa=b;this.Id=a;this.Gc=a!=q;this.Kb=c}
var lb=new Y("19446__totya__yeah","YAY"),mb=new Y("27882__stickinthemud__bike-horn-double-toot",q),nb=new Y("60443__jobro__tada1",q),ob=new Y("406__tictacshutup__click-1-d",q,4),pb=new Y(q,"NO_MY_TURN"),qb=new Y(q,"CHOOSE_YOUR_FRIEND"),rb=new Y(q,"THANKS_FOR_CHOOSING_ME"),sb=new Y(q,"BUT_YOU_CAN_INTERRUPT"),tb=new Y(q,"IM_GOING_TO_PICK_THIS_ONE"),ub=new Y(q,"MAYBE_THAT_WORKS"),vb=new Y(q,"YAY_HELPED_ME_GET_WATER_DROP_1"),wb=new Y(q,"YAY_HELPED_ME_GET_WATER_DROP_2"),xb=new Y(q,"YAY_HELPED_ME_GET_WATER"),
yb=new Y(q,"LETS_FILL_THE_BUCKET"),zb=new Y(q,"WHICH_ONE_DO_YOU_THINK_IT_IS"),Ab=new Y("25879__acclivity__drip1",q),Bb=new Y(q,"INTRO_1"),Cb=new Y(q,"INTRO_2"),Db=new Y(q,"INTRO_3"),Eb=new Y(q,"INTRO_4"),Fb=new Y(q,"INTRO_5"),Gb=new Y(q,"INTRO_GARDEN_1"),Hb=new Y(q,"INTRO_GARDEN_2"),Ib=new Y(q,"SYSTEM_FIRST_YOU_PLAY"),Jb=new Y(q,"SYSTEM_WELL_DONE"),Kb=new Y(q,"SYSTEM_TIME_TO_TEACH_FRIEND"),Lb=new Y(q,"LADDER_LOOKS_FUN"),Mb=new Y(q,"LADDER_SHOW_ME"),Nb=new Y(q,"LADDER_MY_TURN"),jb=new Y(q,"LADDER_PLEASE_HELP_ME"),
Ob=new Y(q,"LADDER_TREE_OOPS_TOO_HIGH"),Pb=new Y(q,"LADDER_TREE_OOPS_TOO_LOW"),Qb=new Y(q,"LADDER_TREE_TRY_A_SMALLER_NUMBER"),Rb=new Y(q,"LADDER_TREE_TRY_A_BIGGER_NUMBER"),Sb=new Y(q,"LADDER_TREE_AGENT_SUGGEST_SOLUTION_1"),Tb=new Y(q,"LADDER_TREE_AGENT_SUGGEST_SOLUTION_2"),Ub=new Y(q,"LADDER_TREE_BETTER_BECAUSE_BIGGER"),Vb=new Y(q,"LADDER_TREE_BETTER_BECAUSE_SMALLER"),Wb=new Y(q,"LADDER_TREE_AGENT_PLAY_TOO_LOW"),Xb=new Y(q,"LADDER_TREE_AGENT_PLAY_TOO_HIGH"),Yb=new Y(q,"LADDER_TREE_AGENT_SEE_CORRECT"),
Zb=new Y("34208__acclivity__tongueclick1",q),$b=new Y(q,"LADDER_MOUNTAIN_IM_DOWN_HERE"),ac=new Y(q,"LADDER_MOUNTAIN_IM_UP_HERE"),bc=new Y(q,"LADDER_MOUNTAIN_TRY_FEWER_BALLOONS"),cc=new Y(q,"LADDER_MOUNTAIN_TRY_MORE_BALLOONS"),dc=new Y(q,"LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_1"),ec=new Y(q,"LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_2"),fc=new Y(q,"LADDER_MOUNTAIN_BETTER_BECAUSE_BIGGER"),gc=new Y(q,"LADDER_MOUNTAIN_BETTER_BECAUSE_SMALLER"),hc=new Y(q,"LADDER_MOUNTAIN_AGENT_PLAY_TOO_LOW"),ic=new Y(q,
"LADDER_MOUNTAIN_AGENT_PLAY_TOO_HIGH"),jc=new Y(q,"LADDER_MOUNTAIN_AGENT_SEE_CORRECT"),kc=new Y(q,"LADDER_MOUNTAIN_YOU_SAVED_ME"),lc=new Y(q,"LADDER_MOUNTAIN_IM_HUNGRY"),mc={Cf:lb,Td:mb,xf:nb,Zd:ob,rf:pb,Yd:qb,yf:rb,Wd:sb,re:tb,Gf:new Y(q,"YES_I_THINK_THAT_ONE_IS_BETTER"),kf:ub,Ef:vb,Ff:wb,Df:xb,ff:yb,Bf:zb,nf:new Y(q,"MONKEY_HMM"),jf:new Y("51710__bristolstories__u-chimes3_short",q),ae:Ab,se:Bb,te:Cb,ue:Db,ve:Eb,we:Fb,xe:Gb,ye:Hb,uf:Ib,wf:Jb,vf:Kb,Nd:new Y(q,"AGENT_BUCKET_IS_FULL"),Rd:new Y(q,"AGENT_NEED_MORE_WATER"),
Qd:new Y(q,"AGENT_LETS_KEEP_PLAYING"),De:Lb,Te:Mb,Re:Nb,Be:new Y(q,"LADDER_IS_IT_RIGHT"),Ce:new Y(q,"LADDER_IT_WAS_RIGHT"),Se:jb,Ae:new Y(q,"LADDER_AGENT_HELP_IN_INTERRUPT"),af:Ob,bf:Pb,ef:Qb,df:Rb,Xe:Sb,Ye:Tb,Ze:Ub,$e:Vb,Ve:Wb,Ue:Xb,We:Yb,cf:Zb,Le:$b,Ne:ac,Oe:bc,Pe:cc,He:dc,Ie:ec,Je:fc,Ke:gc,Fe:hc,Ee:ic,Ge:jc,Qe:kc,Me:lc,NUMBER_1:new Y(q,"NUMBER_1"),NUMBER_2:new Y(q,"NUMBER_2"),NUMBER_3:new Y(q,"NUMBER_3"),NUMBER_4:new Y(q,"NUMBER_4"),NUMBER_5:new Y(q,"NUMBER_5"),NUMBER_6:new Y(q,"NUMBER_6"),NUMBER_7:new Y(q,
"NUMBER_7"),NUMBER_8:new Y(q,"NUMBER_8"),NUMBER_9:new Y(q,"NUMBER_9"),NUMBER_10:new Y(q,"NUMBER_10"),Sd:new Y(q,"ARE_YOU_READY_TO_TEACH"),pe:new Y(q,q,2),ie:new Y(q,"FISHING_FREE_WRONG_ONES"),fe:new Y(q,"FISHING_CATCH"),ke:new Y(q,"FISHING_NOT_THIS_ONE"),ne:new Y(q,"FISHING_THERE_ARE_MORE"),je:new Y(q,"FISHING_KEEP_GOING"),ee:new Y(q,"FISHING_ARE_YOU_SURE"),ge:new Y(q,"FISHING_COUNT_FISH"),he:new Y(q,"FISHING_COUNT_TARGET_FISH"),oe:new Y(q,q),le:new Y(q,q),me:new Y(q,q),ce:new Y(q,"FISHING_ANGEL_CHOOSE_FISH"),
de:new Y(q,"FISHING_ANGEL_COUNT"),Vd:new Y(q,"BUBBA_HI"),Ud:new Y(q,"BUBBA_HERE_TO_HELP"),of:new Y(q,"MONKEY_LEARNED_WELL"),mf:new Y(q,"MONKEY_DIDNT_LEARN_WELL"),gf:new Y(q,"LETS_SHOW_HIM_AGAIN"),zf:new Y(q,"THANK_YOU_FOR_HELPING"),qf:new Y(q,"NOW_MONKEY_SHOW_YOU")},G=function(){function b(a){for(var b=0;b<f.length;b++)f[b].attrs.y-=30;f.push(a)}var a={},c=q,d=q,f=[],e=q,g=k;a.Bd=function(a){c=a;d=c.Fc};a.bd=function(){if(e===q){e=[];for(var a in mc){var b=mc[a];mc[a].tb=a;if(b.fa!=q){var c={id:a,
src:"../res/sound/"+b.fa+".ogg|../res/sound/"+b.fa+".mp3"};b.Kb!=i&&(c.data=b.Kb);e.push(c)}}}return e};a.play=function(a){var e=a.Id;z.pd('"'+e+'"');if(g&&a.Gc){var o=new Kinetic.Text({x:0,y:d.getParent().attrs.height-50,text:Q.get(e),fontSize:20,fontFamily:"Nobile",textFill:"white",textStroke:"black",align:"center",fontStyle:"bold",width:d.getParent().getWidth(),height:50,verticalAlign:"middle",textStrokeWidth:2});b(o);d.add(o);c.Ob();setTimeout(function(){d.remove(o);c.Ob();for(var a=0;a<f.length;a++)f[a]===
o&&f.splice(a,1)},3E3)}a.fa!=q&&SoundJS.play(a.tb)};a.stop=function(a){SoundJS.stop(a.tb)};a.Ld=function(){g?(g=r,console.info("Turning off subtitles")):(g=k,console.info("Turning on subtitles"))};return a}(),Q=function(){var b={INIT_LOADING_SOUNDS:{sv:"Laddar ner ljud...",en:"Downloading sounds..."},INIT_LOADING_IMAGES:{sv:"Laddar ner bilder...",en:"Downloading images..."},RESTART:{sv:"Starta om",en:"Restart"},SETTINGS:{sv:"Inst\u00e4llningar",en:"Settings"},YAY:{sv:"Hurra!",en:"Yay!"},INTRO_1:{sv:"Hej! De h\u00e4r v\u00e4nnerna beh\u00f6ver din hj\u00e4lp",
en:"Hello! These friends need your help"},INTRO_2:{sv:"med att f\u00e5 deras tr\u00e4dg\u00e5rd att v\u00e4xa.",en:"to make their garden grow."},INTRO_3:{sv:"Om du kan l\u00e4ra din v\u00e4n hur man spelar spelen",en:"If you can teach your friend how to do the games"},INTRO_4:{sv:"kan han eller hon samla vattendroppar -",en:"he or she can collect water drops -"},INTRO_5:{sv:"- f\u00f6r att f\u00e5 deras tr\u00e4dg\u00e5rd att v\u00e4xa -",en:"- to make their garden grow again -"},INTRO_GARDEN_1:{sv:"- fr\u00e5n det h\u00e4r...",
en:"- from this..."},INTRO_GARDEN_2:{sv:"...till det h\u00e4r!",en:"...to this!"},CHOOSE_YOUR_FRIEND:{sv:"B\u00f6rja med att v\u00e4lja vilken v\u00e4n du vill hj\u00e4lpa!",en:"First, choose the friend you would like to teach!"},THANKS_FOR_CHOOSING_ME:{sv:"Ja! Tack f\u00f6r att du valde mig!",en:"Yay! Thanks for choosing me!"},ARE_YOU_READY_TO_TEACH:{sv:"\u00c4r du redo att l\u00e4ra apan?",en:"Are you ready to teach monkey?"},SYSTEM_FIRST_YOU_PLAY:{sv:"F\u00f6rst \u00e4r det du som spelar spelet!",
en:"First, you play the game!"},SYSTEM_WELL_DONE:{sv:"Bra gjort!",en:"Well done!"},SYSTEM_TIME_TO_TEACH_FRIEND:{sv:"Nu \u00e4r det dags att l\u00e4ra din v\u00e4n hur man g\u00f6r!",en:"Now it's time to teach your friend!"},NO_MY_TURN:{sv:"Gl\u00f6m inte att det \u00e4r MIN tur nu!",en:"Remember it\u2019s MY turn now!"},BUT_YOU_CAN_INTERRUPT:{sv:"Men du kan avbryta mig om jag g\u00f6r fel.",en:"But you can interrupt me if I'm making a mistake."},AGENT_BUCKET_IS_FULL:{sv:"Hurra! Nu \u00e4r min kanna full och vi kan bes\u00f6ka min tr\u00e4dg\u00e5rd!",
en:"Wow! Now my bucket is full and we are ready to visit my garden!"},AGENT_NEED_MORE_WATER:{sv:"Jag beh\u00f6ver mer vatten till tr\u00e4dg\u00e5rden!",en:"I still need more water to fix my garden!"},AGENT_LETS_KEEP_PLAYING:{sv:"Vi forts\u00e4tter spela.",en:"Let\u2019s keep playing."},MAYBE_THAT_WORKS:{sv:"Okej, vi testar och ser om det \u00e4r r\u00e4tt.",en:"OK, let's see if this works."},YAY_HELPED_ME_GET_WATER_DROP_1:{sv:"Hurra! Du hj\u00e4lpte mig att f\u00e5 en vattendroppe",en:"Yay! You helped me get a water drop"},
YAY_HELPED_ME_GET_WATER_DROP_2:{sv:"till min tr\u00e4dg\u00e5rd, s\u00e5 den kan v\u00e4xa!",en:"for my garden to grow again!"},YAY_HELPED_ME_GET_WATER:{sv:"Hurra! Tack f\u00f6r hj\u00e4lpen! Nu fick jag lite vatten till min tr\u00e4dg\u00e5rd!",en:"Woo! Thank you for helping me! Now I have some water for my garden!"},LETS_FILL_THE_BUCKET:{sv:"Kom igen och fyll kannan!",en:"Let's fill the bucket!"},WHICH_ONE_DO_YOU_THINK_IT_IS:{sv:"Vilken tror du att det \u00e4r?",en:"Which one do you think it is?"},
YES_I_THINK_THAT_ONE_IS_BETTER:{sv:"Ja, det d\u00e4r fungerar nog b\u00e4ttre!",en:"Yes, I think that one is better!"},LADDER_TREE_BETTER_BECAUSE_BIGGER:{sv:"Ja, det verkar vara ett bra val, eftersom den \u00c4R st\u00f6rre!",en:"Yes, that seems to be a good choice because it IS bigger!"},LADDER_TREE_BETTER_BECAUSE_SMALLER:{sv:"Ja, det verkar vara ett bra val, eftersom den \u00c4R mindre!",en:"Yes, that seems to be a good choice because it IS smaller!"},IM_GOING_TO_PICK_THIS_ONE:{sv:"Okej, f\u00e5r se om den h\u00e4r fungerar. Hmm...",
en:"Ok, let's see if this works. Hmm..."},FISHING_CATCH_NUMBER:{sv:"F\u00e5nga nummer %1",en:"Catch number %1"},FISHING_CATCH:{sv:"F\u00e5nga",en:"Catch"},FISHING_FREE_WRONG_ONES:{sv:"Frige fiskarna som \u00e4r fel",en:"Put back the wrong fish"},FISHING_NOT_THIS_ONE:{sv:"Inte den!",en:"Not this one!"},FISHING_THERE_ARE_MORE:{sv:"Det finns mer fiskar att f\u00e5nga. Forts\u00e4tt leta!",en:"There are more fish to catch. Keep looking!"},FISHING_ARE_YOU_SURE:{sv:"\u00c4r du s\u00e4ker?",en:"Are you sure?"},
FISHING_COUNT_FISH:{sv:"R\u00e4kna fiskarna!",en:"Count the fish!"},FISHING_COUNT_TARGET_FISH:{sv:"R\u00e4kna fiskarna med",en:"Count the fish with"},FISHING_ANGEL_CHOOSE_FISH:{sv:"Jag v\u00e4ljer den h\u00e4r fisken eftersom...",en:"I choose this fish, because it..."},FISHING_ANGEL_COUNT:{sv:"Jag v\u00e4ljer den h\u00e4r siffran eftersom...",en:"I choose this number, because..."},LADDER_LOOKS_FUN:{sv:"Det d\u00e4r s\u00e5g kul ut!",en:"That looked fun!"},LADDER_SHOW_ME:{sv:"Visa mig hur man g\u00f6r!",
en:"Now show me how to do it!"},LADDER_MY_TURN:{sv:"Okej, nu ska vi se om jag klarar det h\u00e4r sj\u00e4lv!",en:"Ok, now let's see if I can do this on my own!"},LADDER_IS_IT_RIGHT:{sv:"G\u00f6r jag r\u00e4tt eller fel?",en:"Am I doing it right or wrong?"},LADDER_IT_WAS_RIGHT:{sv:"Ja! Du fick presenten!",en:"Yeah! You got it!"},LADDER_TREE_OOPS_TOO_HIGH:{sv:"Oj, kanske tog vi i f\u00f6r mycket!",en:"Oops! Maybe we overdid it!"},LADDER_TREE_OOPS_TOO_LOW:{sv:"Hmm... Kanske var det inte tillr\u00e4ckligt!",
en:"Hmm... Maybe it wasn't enough!"},LADDER_TREE_TRY_A_SMALLER_NUMBER:{sv:"Vi kan v\u00e4l testa en mindre och se vad som h\u00e4nder!",en:"Let's try a smaller one and see what happens!"},LADDER_TREE_TRY_A_BIGGER_NUMBER:{sv:"Vad tror du? Ska vi testa en st\u00f6rre?",en:"What do you think? Shall we try a bigger one?"},LADDER_TREE_AGENT_PLAY_TOO_LOW:{sv:"Hmm, det gick inte. Jag undrar varf\u00f6r. Jag testar en st\u00f6rre!",en:"Hmm, that didn't work. I wonder why. Let me try a bigger one!"},LADDER_TREE_AGENT_PLAY_TOO_HIGH:{sv:"\u00c5h, nej! Var den f\u00f6r stor?",
en:"Oh no! Was that too big?"},LADDER_TREE_AGENT_SEE_CORRECT:{sv:"WOO! Tack f\u00f6r hj\u00e4lpen! Vilken fin present!",en:"WOO! Thank you for helping me! What a great surprise!"},LADDER_TREE_AGENT_SUGGEST_SOLUTION_1:{sv:"Kanske kan vi f\u00f6rs\u00f6ka med samma siffra p\u00e5",en:"Maybe we should match the number on"},LADDER_TREE_AGENT_SUGGEST_SOLUTION_2:{sv:"nummerplattan som vid presenten?",en:"the number pad to the number by the gift?"},LADDER_PLEASE_HELP_ME:{sv:"Kan du hj\u00e4lpa mig att v\u00e4lja r\u00e4tt?",
en:"Can you please help me find the right one?"},LADDER_MOUNTAIN_IM_DOWN_HERE:{sv:"Jag \u00e4r h\u00e4r nere!",en:"I'm down here!"},LADDER_MOUNTAIN_IM_UP_HERE:{sv:"Jag \u00e4r h\u00e4r uppe!",en:"I'm up here!"},LADDER_MOUNTAIN_YOU_SAVED_ME:{sv:"Du r\u00e4ddade mig!!!",en:"You saved me!!!"},LADDER_MOUNTAIN_IM_HUNGRY:{sv:"Jag \u00e4r hungrig. Kom s\u00e5 g\u00e5r vi och \u00e4ter!",en:"I'm hungry. Let's go eat!"},LADDER_MOUNTAIN_TRY_FEWER_BALLOONS:{sv:"Kanske ska vi testa med f\u00e4rre ballonger?",
en:"Perhaps we should try with fewer balloons?"},LADDER_MOUNTAIN_TRY_MORE_BALLOONS:{sv:"Vi kan v\u00e4l testa med fler ballonger och se vad som h\u00e4nder?",en:"Let's try with more balloons and see what happens!"},LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_1:{sv:"Kanske kan vi f\u00f6rs\u00f6ka med lika m\u00e5nga ballonger",en:"Maybe we should match the number of balloons"},LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_2:{sv:"som niv\u00e5er upp din v\u00e4n \u00e4r.",en:"to the level your friend is stuck on."},
LADDER_MOUNTAIN_AGENT_PLAY_TOO_LOW:{sv:"Oj, det kanske var f\u00f6r f\u00e5 ballonger.",en:"Oops, maybe I used to few balloons."},LADDER_MOUNTAIN_AGENT_PLAY_TOO_HIGH:{sv:"Hoppsan, det var nog f\u00f6r m\u00e5nga ballonger!",en:"Oops, I think there were too many balloons!"},LADDER_MOUNTAIN_BETTER_BECAUSE_BIGGER:{sv:"Ja, det fungerar nog, f\u00f6r det \u00c4R fler ballonger!",en:"Yes, this can work, beacuse that IS more ballons!"},LADDER_MOUNTAIN_BETTER_BECAUSE_SMALLER:{sv:"Ja, det fungerar nog, f\u00f6r det \u00c4R f\u00e4rre ballonger!",
en:"Yes, this will probably work, beacuse that IS fewer balloons!"},LADDER_MOUNTAIN_AGENT_SEE_CORRECT:{sv:"WOO! Tack f\u00f6r hj\u00e4lpen! Vi r\u00e4ddade v\u00e5r v\u00e4n!",en:"WOO! Thank you for helping me! We saved our friend!"},BUBBA_HI:{sv:"Hej! Mitt namn \u00e4r Bubba!",en:"Hi, my name is Bubba!"},BUBBA_HERE_TO_HELP:{sv:"Jag ska hj\u00e4lpa dig och apan l\u00e4ngs v\u00e4gen.",en:"I'm here to help you and monkey throughout his journey."},MONKEY_LEARNED_WELL:{sv:"Toppen! Apan l\u00e4rde sig bra!",
en:"Great! Monkey learned well!"},MONKEY_DIDNT_LEARN_WELL:{sv:"\u00c5h, nej! Apan l\u00e4rde sig inte riktigt.",en:"Oh no! Monkey didn't learn well."},LETS_SHOW_HIM_AGAIN:{sv:"Visa honom igen!",en:"Let's show him again!"},THANK_YOU_FOR_HELPING:{sv:"Tack f\u00f6r att du hj\u00e4lpte apan!",en:"Thank you for helping monkey!"},NOW_MONKEY_SHOW_YOU:{sv:"Nu visar apan dig vad den har l\u00e4rt sig!",en:"Now monkey show you what it learned!"},MONKEYS_TURN:{sv:"Apans tur!",en:"Monkey's turn!"},MONKEY_HMM:{sv:"Apan: Hmmm...",
en:"Monkey: Hmm..."},FISHING_KEEP_GOING:{sv:"Forts\u00e4tt!",en:"Keep going!"},NUMBER_1:{sv:"nummer 1",en:"number 1"},NUMBER_2:{sv:"nummer 2",en:"number 2"},NUMBER_3:{sv:"nummer 3",en:"number 3"},NUMBER_4:{sv:"nummer 4",en:"number 4"},NUMBER_5:{sv:"nummer 5",en:"number 5"},NUMBER_6:{sv:"nummer 6",en:"number 6"},NUMBER_7:{sv:"nummer 7",en:"number 7"},NUMBER_8:{sv:"nummer 8",en:"number 8"},NUMBER_9:{sv:"nummer 9",en:"number 9"},NUMBER_10:{sv:"nummer 10",en:"number 10"},SETTINGS_LABEL:{sv:"Inst\u00e4llningar",
en:"Settings"},SETTINGS_APPLY:{sv:"Verkst\u00e4ll",en:"Apply"},SETTINGS_SHOW:{sv:"Visa inst\u00e4llningar",en:"Show settings"},SETTINGS_HIDE:{sv:"G\u00f6m inst\u00e4llningar",en:"Hide settings"},SETTINGS_CANCEL:{sv:"Avbryt",en:"Cancel"},SETTINGS_GLOBAL_LABEL:{sv:"Globala",en:"Global"},SETTINGS_GLOBAL_LANGUAGE_LABEL:{sv:'Spr\u00e5k (kan vara "sv" eller "en" och kr\u00e4ver omstart)',en:'Language (can be "sv" or "en" and requires restart)'},SETTINGS_GLOBAL_MONKEYSEEROUNDS_LABEL:{sv:"Monkey See-rundor",
en:"Monkey See rounds"},SETTINGS_GLOBAL_TRIESBEFOREGUARDIANANGEL_LABEL:{sv:"F\u00f6rs\u00f6k innan skydds\u00e4ngel",en:"Tries before guardian angel"},SETTINGS_MINIGAMES_LABEL:{sv:"Minispel",en:"Mini-games"},SETTINGS_MINIGAMES_FISHINGGAME_LABEL:{sv:"Fiskespel",en:"Fishing Game"},SETTINGS_MINIGAMES_FISHINGGAME_TARGETNUMBER_LABEL:{sv:"M\u00e5lnummer",en:"Target number"},SETTINGS_MINIGAMES_FISHINGGAME_NUMBERCORRECT_LABEL:{sv:"Antal korrekta fiskar",en:"Number of correct fish"},SETTINGS_MINIGAMES_FISHINGGAME_NUMBEROFFISH_LABEL:{sv:"Antal fiskar totalt",
en:"Number of fish totally"},SETTINGS_MINIGAMES_FISHINGGAME_MAXNUMBER_LABEL:{sv:"H\u00f6gsta m\u00f6jliga nummer",en:"Maximum number on fish"},SETTINGS_MINIGAMES_LADDER_LABEL:{sv:"Stegen",en:"The Ladder"},SETTINGS_MINIGAMES_LADDER_TARGETNUMBER_LABEL:{sv:"M\u00e5lnummer",en:"Target number"}};return{get:function(a,c){if(b[a]===i)return q;for(var d=b[a][K.get("global","language")],f=1;f<arguments.length;f++)d=d.replace("%"+f,arguments[f]);return d}}}();
Object.size=function(b){var a=0,c;for(c in b)b.hasOwnProperty(c)&&a++;return a};var z=new function(){function b(a,b,d,f){var e=console;d===i?d="":"string"!==typeof d&&(d="");if("evm"!=d&&"sound"!=d){for(var d=d.substr(0,8),d=d.toUpperCase(),g=8-d.length,j=0;j<g;j++)d=" "+d;f.call(e,a+" "+d+" "+b)}}console.log("Creating Log");this.debug=function(a,c){b("DEBUG  ",a,c,console.debug)};this.pd=function(a){b("NOTIFY ",a,"sound",console.info)};this.error=function(a,c){b("ERROR  ",a,c,console.error)}};
Array.prototype.remove=function(b){for(var a=0;a<this.length;a++)this[a]===b&&this.splice(a)};
var T=new function(){function b(a,b,d,f,e){var g=0,j=0;this.next=function(){var n=a+g*d,o=b+j*f;g=(g+1)%e;0==g&&j++;return{x:n,y:o}}}this.pa=function(a){var b=arguments;return function(a){var f,e=[],g=q,j=k;for(f=0;f<b.length;f+=1)e.push(b[f]);g=function(b){j&&(b=a,j=r);var c=e.shift();c!=i&&c(g,b)};g()}};this.X=function(a,b){return Math.floor(Math.random()*(b-a+1))+a};this.gd=function(a,b){for(var d=0;d<a.length;d++)if(a[d]===b)return k;return r};this.$=function(a,c,d,f,e){return new b(a,c,d,f,e)}};
Kinetic.Xd=function(b){var a=new Kinetic.Group({x:b.x,y:b.y,width:b.width,height:b.height}),c=new Kinetic.Rect({x:0,y:0,width:b.width,height:b.height,fill:"#ccc",strokeWidth:1,stroke:"white"}),d=new Kinetic.Text({text:b.text,fontFamily:"Arial",textFill:"black",fontSize:b.fontSize,x:b.width/2,y:b.height/2,verticalAlign:"middle",align:"center"});a.add(c);a.add(d);a.on("mousedown touchstart",b.callback);return a};
function nc(){var b=this,a=q,c=q,d=q,f=q,e=q,g=q,j=q,n=q,o=q,l=q,m=q,p=q;this.F=function(e,l,m){f=e;j=l;n=m;a=new Kinetic.Group({x:j,y:n});c=new Kinetic.Image({image:b.z()});d=new Kinetic.Image({image:b.G(),x:-12,y:-11});g=new Kinetic.Image({image:b.H()[0],x:-216,y:-196,visible:r});a.add(c);a.add(d);a.add(g);return a};this.Gb=function(a,c,d){e=a;a=new Kinetic.Group({x:c,y:d});c=new Kinetic.Image({image:b.head(),width:b.head().width,height:b.head().height});o=new Kinetic.Image({image:b.G(),x:-12,y:-11});
l=new Kinetic.Image({image:b.B()[0],visible:r,x:-12,y:-11});a.add(c);a.add(o);a.add(l);return a};this.kd=function(e,g){j=e;n=g;c.setImage(b.Eb());d.hide();f.c(a.attrs).to({alpha:1},400).to({x:e,y:g},3E3).call(function(){c.setImage(b.z());d.show()})};this.Dd=function(){a.setAlpha(1);a.show()};this.od=function(b,c){j=b;n=c;a.setX(b);a.setY(c)};this.Pb=function(a,e){function d(a){m=a;l=k;o||n()}var n=q,j=[b.H()[0],b.H()[1],b.H()[2],b.H()[3],b.Qb()[a-1]],l=r,m=q,p=0,o=r;c.setImage(b.Yb());g.show();n=
function(){o=k;g.setImage(j[p]);f.setTimeout(function(){!l&&p<j.length?(p+=1,n()):l&&0<=p?(p-=1,n()):p===j.length?(e(),o=r):l&&-1===p&&(c.setImage(b.z()),g.hide(),m!==q&&m!==i&&m(),o=r)},200)};n();return this.td=d};this.jd=function(){this.td()};this.Gd=function(){f.da(c.attrs);c.setImage(b.z());a.setX(j);a.setY(n);c.setWidth(b.z().width);c.setHeight(b.z().height);d.show()};this.D=function(){d.hide();a.setX(j+0);a.setY(n+-51);c.setImage(b.w()[0]);c.setWidth(b.w()[0].width);c.setHeight(b.w()[0].height);
f.c(c.attrs).to({image:b.w()[0]}).wait(400).to({image:b.w()[1]}).wait(400).to({image:b.w()[2]}).wait(400).call(b.D)};this.Sc=function(){e.setInterval(function(){l.show();e.c(l.attrs).to({image:b.B()[1]},100).to({image:b.B()[2]},100).to({image:b.B()[1]},100).to({image:b.B()[0]},100).call(function(){l.hide()})},5E3)};this.Fd=function(){d.setImage(b.Ba());m=f.setInterval(function(){d.setImage(b.G());p=f.setTimeout(function(){d.setImage(b.Ba())},200)},400)};this.Hd=function(){f.clearInterval(m);f.clearTimeout(p);
d.setImage(b.G())}}function Ta(){nc.call(this);this.head=function(){return X.Ya};this.z=function(){return X.Za};this.Yb=function(){return X.$a};this.G=function(){return X.Wa};this.w=function(){return[X.Ta,X.Ua,X.Va]};this.H=function(){return[X.Ga,X.Ha,X.Ia,X.Ja]};this.Qb=function(){return[X.Pa,X.Oa,X.Na,X.Ma,X.La,X.Ka]};this.B=function(){return[X.Qa,X.Ra,X.Sa]};this.Ba=function(){return X.ab};this.Eb=function(){return X.Xa}}
function R(){nc.call(this);this.head=function(){return X.Ya};this.z=function(){return X.Za};this.Yb=function(){return X.$a};this.G=function(){return X.Wa};this.w=function(){return[X.Ta,X.Ua,X.Va]};this.H=function(){return[X.Ga,X.Ha,X.Ia,X.Ja]};this.Qb=function(){return[X.Pa,X.Oa,X.Na,X.Ma,X.La,X.Ka]};this.B=function(){return[X.Qa,X.Ra,X.Sa]};this.Ba=function(){return X.ab};this.Eb=function(){return X.Xa}}
function eb(b){function a(a,d,j){var n=new Kinetic.Group({x:d,y:j}),d=new Kinetic.Rect({width:250,height:250,fill:{start:{x:125,y:125,radius:0},end:{x:125,y:125,radius:187.5},colorStops:[0,"#00FF7F",1,"#556B2F"]},shadow:{color:"black",blur:15,offset:[15,15],alpha:0.5},alpha:0.6,cornerRadius:10,strokeWidth:4,stroke:"white",offset:{x:125,y:125}});n.add(d);n.A=d;n.Cc=a;a=(new a.view).Gb(c,-110,-60);a.setScale(0.9);n.add(a);n.on("mousedown touchstart",function(){G.play(ob);n.A.setFill("white");n.moveToTop();
f.Nc(n,function(){b.Qc(n.Cc)});f.Rc()});return n}Z.call(this,"AgentChooserView");var c=this,d=q,f=function(){var a=[];this.add=function(b){a.push(b);d.add(b)};this.Rc=function(){for(var b=0;b<a.length;b++)a[b].attrs.listening=r};this.Nc=function(b,d){for(var f=0;f<a.length;f++)a[f]===b?(c.c(a[f].attrs).wait(1E3).to({x:c.e.getWidth()/2,y:c.e.getHeight()/2},1E3),c.c(a[f].attrs.scale).wait(1E3).to({x:1.5,y:1.5},1E3).call(function(){G.play(rb)}).wait(5E3).call(d)):c.c(a[f].attrs).to({alpha:0},1E3)};return this}();
c.v=function(){d=new Kinetic.Layer;c.e.add(d);var e=new Kinetic.Image({image:X.qc});d.add(e);for(var e=T.$(363,150,310,310,2),g=b.Wc(),j=0;j<g.length;j++){var n=e.next();f.add(new a(g[j],n.x,n.y))}G.play(qb)};c.k(function(){c.e.remove(d)});c.on(L,function(){d.draw()})}
function Va(){Z.call(this,"GardenView");var b=this,a,c,d,f,e,g;b.m(function(){a=new Kinetic.Image({image:X.pc});c=new Kinetic.Image({image:X.oc});f=new Kinetic.Group({x:300,y:300,visible:r});e=new Kinetic.Image({image:X.r,offset:{x:X.r.width/2,y:X.r.height/2}});g=new Kinetic.Polygon({points:[{x:40,y:0},{x:60,y:0},{x:80,y:40},{x:41,y:63},{x:15,y:17}],offset:{x:X.r.width/2,y:X.r.height/2},fill:"blue"});d=new Kinetic.Layer;b.getStage().add(d);d.add(a);d.add(f);f.add(g);f.add(e)});b.k(function(){b.getStage().remove(d)});
b.on(L,function(){d.draw()});b.on("Game.demonstrateGarden",function(e){G.play(Gb);c.setAlpha(0);d.add(a);d.add(c);var f=new Kinetic.Group({x:10,y:10}),g=new Kinetic.Rect({width:100,height:30,fill:"gray"}),l=new Kinetic.Text({text:"Skip",width:100,height:30,y:10,align:"center",fontFamily:"Arial",textFill:"black"});f.add(g);f.add(l);f.on("mousedown touchstart",function(){e.callback()});d.add(f);b.setTimeout(function(){G.play(Hb);b.c(a.attrs).to({alpha:0},2E3);b.c(c.attrs).to({alpha:1},2E3).wait(3E3).call(e.callback)},
3E3)});b.on("Game.waterGarden",function(a){var c=g.attrs.points,d=(c[0].y-c[4].y)/(c[0].x-c[4].x),l=(c[2].y-c[1].y)/(c[2].x-c[1].x),m=c[0].y+17,p=c[0].y-d*c[0].x,x=c[2].y-l*c[2].x;e.setRotation(Math.PI/3);f.show();setTimeout(function(){setTimeout(function(){b.c(g.attrs.points[0]).to({x:(m-p)/d,y:m},3E3);b.c(g.attrs.points[1]).to({x:(m-x)/l,y:m},3E3).call(function(){var e=(c[3].y-c[4].y)/(c[3].x-c[4].x),d=c[3].y-e*c[3].x;m+=c[3].y-c[2].y;b.c(g.attrs.points[0]).to({x:(m-d)/e,y:m},3E3);b.c(g.attrs.points[1]).to({x:(m-
x)/l,y:m},3E3).call(function(){m+=c[3].y-c[2].y;b.c(g.attrs.points[0]).to({x:(m-d)/e,y:m},2E3);b.c(g.attrs.points[1]).to({x:(m-d)/e,y:m},2E3).call(function(){b.setTimeout(function(){a.callback()},3E3)})})})},1E3)},1E3)})}
function Ua(b){Z.call(this,"IntroductionView");var a=this,c,d;a.m(function(){c=a.getStage();d=new Kinetic.Layer;c.add(d);var f=new R,e=f.F(a,100,200);d.add(e);f.D();e.setScale(0.7);f=new R;e=f.F(a,300,200);d.add(e);f.D();e.setScale(0.7);f=new R;e=f.F(a,500,200);d.add(e);f.D();e.setScale(0.7);f=new R;e=f.F(a,700,200);d.add(e);f.D();e.setScale(0.7);var f=new Kinetic.Group({x:10,y:10}),e=new Kinetic.Rect({width:100,height:30,fill:"gray"}),g=new Kinetic.Text({text:"Skip",width:100,height:30,y:10,align:"center",
fontFamily:"Arial",textFill:"black"});f.add(e);f.add(g);f.on("mousedown touchstart",function(){b(k)});d.add(f);a.setTimeout(function(){G.play(Bb)},2E3);a.setTimeout(function(){G.play(Cb)},2E3);a.setTimeout(function(){G.play(Db)},7E3);a.setTimeout(function(){G.play(Eb)},7E3);a.setTimeout(function(){G.play(Fb)},12E3);a.setTimeout(function(){b(r)},14E3)});a.k(function(){c.remove(d)});a.on(L,function(){d.draw()})}
function Xa(){Z.call(this,"MinigameHandlerView");var b=this.e.U;(function(a){var c=new Kinetic.Text({text:"Backend Score (current minigame):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:a.e.getWidth()-700,y:35}),d=r,f=r;a.on("backendScoreGameUpdateMiniGame",function(a){c.setText("Backend Score (current minigame): "+a.xd)});a.m(function(){f=d=k;b.add(c)});a.on(ma,function(){f&&!d?(b.add(c),d=k,console.info("Turning off backend score display")):f&&d&&(b.remove(c),
d=r,console.info("Turning on backend score display"))});a.k(function(){f=r;d&&b.remove(c);d=r})})(this);(function(a){var c=new Kinetic.Text({text:"Learning track (current game):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:a.e.getWidth()-700,y:55}),d=r,f=r;a.m(function(){b.add(c);d=f=k});a.on("learningTrackUpdate",function(a){c.setText("Learning track (current game): "+a.ld.name())});a.on(ma,function(){f&&!d?(b.add(c),d=k):f&&d&&(b.remove(c),d=r)});a.k(function(){f=
r;d&&b.remove(c);d=r})})(this);(function(a){var c,d,f,e,g=10,j=20;a.m(function(){c=new Kinetic.Image({image:X.r,x:b.getStage().getWidth()-X.r.width-20,y:20,width:X.r.width,height:X.r.height,visible:r});d=new Kinetic.Image({image:X.T,offset:{x:X.T.width/2,y:0},width:X.T.width,height:X.T.height,visible:r,rotation:Math.PI});f=new Kinetic.Image({image:X.ka,x:c.getX(),y:c.getY(),width:X.ka.width,height:X.ka.height,visible:r});e=new Kinetic.Rect({fill:"#379de4",x:c.getX()+20,y:c.getY()+c.getHeight()-4,
width:54,height:0});b.add(f);b.add(e);b.add(d);b.add(c)});a.k(function(){b.remove(d);b.remove(c);b.remove(f);b.remove(e)});a.m(function(){c.show();var b=a.b.cd();0<b&&f.show();e.setHeight(e.getHeight()-6.9*b)});a.on("resetPitcherLevel",function(){f.hide();e.setHeight(0)});a.on(pa,function(a){g=a.x;j=a.y});a.on("setPitcherLevel",function(b){var o=c.getX()+c.getWidth()/2,l=c.getY()+c.getHeight()-d.getHeight(),m=1E3*(Math.sqrt(Math.pow(g-o,2)+Math.pow(j-l,2))/200);d.setX(g);d.setY(j);d.setAlpha(1);d.show();
a.b.ba()?G.play(xb):a.b.d()&&(G.play(vb),G.play(wb),a.setTimeout(function(){G.play(yb)},2E3));a.c(d.attrs).to({x:o-50,y:l},1.2*m).to({rotation:4*Math.PI/3,x:o-50,y:l-30},300).to({rotation:5*Math.PI/3,x:o-25,y:l-25},300).to({rotation:6*Math.PI/3,x:o,y:l},300).call(function(){G.play(Ab);f.show();a.c(e.attrs).to({height:e.getHeight()-6.9},1E3);a.c(d.attrs).to({alpha:0},1E3).wait(1E3).call(function(){d.hide();d.setRotation(Math.PI);b.callback!=i&&b.callback()})})})})(this)}
function db(){Z.call(this,"MonkeyWorldView");var b=this.e,a=b.U;this.p=function(){this.u()};(function(b){var d=[];b.on("Game.showMiniGameChooser",function(b){var c=b.callback,g=b.Uc,j=T.$(200,200,300,100,2),n;for(n in g)(function(){for(var b=0;b<g[n].Kd();b++)(function(){var f=g[n].ec[b],m=j.next(),m=new Kinetic.Group(m),p=new Kinetic.Rect({width:280,height:100,stroke:"black",strokeWidth:4}),x=new Kinetic.Text({text:f.title,fontSize:20,fontFamily:"sans-serif",textFill:"black",align:"center",verticalAlign:"center",
width:280,height:100,y:40});x.setAlign("center");m.add(p);m.add(x);m.on("mousedown touchstart",function(){p.setFill("yellow");c(f)});d.push(m);a.add(m)})()})()});b.on("Game.hideMiniGameChooser",function(){for(var b=0;b<d.length;b++)a.remove(d[b]);d=[]})})(this);(function(c){var d=new Kinetic.Rect({x:b.getWidth()/2,y:b.getHeight()/2,width:320,height:50,cornerRadius:10,offset:{x:160,y:25},fill:"#333",alpha:0}),f=new Kinetic.Rect({x:b.getWidth()/2,y:b.getHeight()/2,width:0,height:30,offset:{x:150,y:15},
fill:"#FFCC00"}),e=new Kinetic.Text({fontFamily:"Arial",fontSize:10,textFill:"black",fontStyle:"bold",Pf:"black",text:"Monkey World Demo",align:"center",width:b.getWidth(),height:50,y:b.getHeight()/2-50,x:0});c.on("Game.showLoadingScreen",function(b){a.add(d);a.add(f);a.add(e);d.transitionTo({alpha:1,duration:b.time/1E3})});c.on("Game.loadingSounds",function(){e.setText(Q.get("INIT_LOADING_SOUNDS"))});c.on("Game.loadingImages",function(){e.setText(Q.get("INIT_LOADING_IMAGES"))});c.on("Game.loadingDone",
function(){a.remove(e);a.remove(d);a.remove(f)});c.on("Game.updateSoundLoading",function(a){f.setWidth(300*a.progress)});c.on("Game.updateImageLoading",function(a){f.setWidth(300*a.progress)})})(this)}
Kinetic.t.rc=function(b,a){function c(b){a.c(e.attrs).to({image:X.kb}).wait(n).to({image:X.lb}).wait(n).to({image:X.mb}).wait(n).to({image:X.nb}).call(b)}function d(b){a.c(l.attrs).to({image:X.rb}).wait(o).to({image:X.qb}).wait(o).to({image:X.pb}).wait(o).to({image:X.S}).wait(o).to({visible:r}).call(b)}var f=new Kinetic.Group(b),e,g,j,n=200,o=200,l;e=new Kinetic.Image({image:X.s,width:X.s.width,height:X.s.height});l=new Kinetic.Image({image:X.S,width:X.S.width,height:X.S.height,visible:r,x:109,y:81,
offset:{x:279,y:281}});f.add(l);f.add(e);this.ga=function(){e.attrs.image=X.ob;g=a.setInterval(function(){e.attrs.image=X.yc;j=a.setTimeout(function(){e.attrs.image=X.ob},140)},280)};this.L=function(){a.clearInterval(g);a.clearTimeout(j);e.attrs.image=X.s};this.Ab=function(b){var c=X.s.height/X.R.height;a.c(e.attrs).to({image:X.la,width:X.la.width*c,height:X.la.height*c}).wait(2E3).to({image:X.ma,width:X.ma.width*c,height:X.ma.height*c}).wait(2E3).call(function(){f.setX(f.getX()-15)}).to({image:X.R,
width:X.R.width*c,height:X.R.height*c}).wait(2E3).to({image:X.s,width:X.s.width,height:X.s.height}).call(b)};f.ga=this.ga;f.L=this.L;this.Ea=function(b){c(function(){l.show();a.c(l.attrs).to({image:X.pb}).wait(o).to({image:X.qb}).wait(o).to({image:X.rb}).wait(o).to({image:X.zc}).call(b)})};this.Da=function(b){d(function(){a.c(e.attrs).to({image:X.nb}).wait(n).to({image:X.mb}).wait(n).to({image:X.lb}).wait(n).to({image:X.kb}).wait(n).to({image:X.s}).call(b)})};f.Da=this.Da;f.Ea=this.Ea;f.Ab=this.Ab;
return f};
Kinetic.t.tc=function(b){var a={x:750,y:600,alpha:0};a.image=X.I;a.width=128;a.height=128;a.offset={x:64,y:64};var c=new Kinetic.Image(a);this.animate=function(){b.c(c.attrs).to({image:X.bb}).wait(300).to({image:X.cb}).wait(300).to({image:X.eb}).wait(300).to({image:X.I}).wait(300).to({image:X.fb}).wait(300).to({image:X.gb}).wait(300).to({image:X.hb}).wait(300).to({image:X.I}).wait(300).to({image:X.bb}).wait(300).to({image:X.cb}).wait(300).to({image:X.eb}).wait(300).to({image:X.I}).wait(300).to({image:X.fb}).wait(300).to({image:X.gb}).wait(300).to({image:X.hb}).wait(300).to({image:X.I}).wait(300)};c.animate=
this.animate;return c};
Kinetic.t.xc=function(b){var a,c;a=new Kinetic.Group(b);switch(b.type){case 1:c=X.uc;break;case 2:c=X.vc;break;case 3:c=X.wc;break;default:h("NoSuchParcelTypeException")}b=new Kinetic.Image({image:c,width:c.width,height:c.height,scale:0.6+0.4*Math.random(),offset:{x:c.width/2,y:c.height/2}});a.add(b);a.Cd=function(b){var c=a.getX(),e=a.getY();b.c(a.attrs).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c},
100);b.c(a.attrs).to({y:e-5},100).to({y:e+5},100).to({y:e-5},100).to({y:e+5},100).to({y:e-5},100).to({y:e+5},100).to({y:e-5},100).to({y:e+5},100).to({y:e-5},100).to({y:e},100)};a.rd=function(b){a.on("mousedown touchstart",b)};a.qd=function(){a.off("mousedown touchstart")};a.open=s();return a};
Kinetic.t.Bc=function(b){var a={x:900,y:600,alpha:0};a.image=X.ja;a.width=128;a.height=128;a.offset={x:64,y:64};var c=new Kinetic.Image(a);this.animate=function(){b.c(c.attrs).to({image:X.N}).wait(300).to({image:X.O}).wait(300).to({image:X.ib}).wait(300).to({image:X.O}).wait(300).to({image:X.N}).wait(300).to({image:X.ja}).wait(300).to({image:X.N}).wait(300).to({image:X.O}).wait(300).to({image:X.ib}).wait(300).to({image:X.O}).wait(300).to({image:X.N}).wait(300).to({image:X.ja}).wait(300)};c.animate=
this.animate;return c};
function oc(b){Z.call(this,b);var a=q,c=0,d=0,f=this.e.U;(function(a){var b=new Kinetic.Text({text:"Backend Score (current mode):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:a.e.getWidth()-700,y:15});f.add(b);var c=k,d=c;a.on(na,function(a){b.setText("Backend Score (current mode): "+a.zb)});a.on(ma,function(){d&&!c?(f.add(b),c=k):d&&c&&(f.remove(b),c=r)});a.k(function(){c&&f.remove(b);c=d=r})})(this);(function(b){var g=b.b.f().G(),j=(new b.b.f).Gb(b,
b.getStage().getWidth()-g.width-30,12);j.setScale(0.5);b.m(function(){b.b.ca()?(f.add(j),b.b.f().Sc(),b.on(qa,function(a){G.play(Ib);setTimeout(a,2E3)})):b.b.ba()?(a=b.b.f().F(b,b.getStage().getWidth()-g.width-30,12),a.setAlpha(0),f.add(j),b.on(qa,function(a){G.play(Jb);b.setTimeout(function(){G.play(Kb);b.setTimeout(function(){b.c(j.attrs).to({alpha:0},2E3);b.b.f().kd(c,d);b.setTimeout(function(){b.b.f().Fd();G.play(Lb);b.setTimeout(function(){G.play(Mb);b.setTimeout(function(){b.b.f().Hd()},1500);
b.setTimeout(a,2E3)},2E3)},2E3)},3E3)},2E3)})):b.b.d()&&(a=b.b.f().F(b,c,d),a.hide(),b.on(qa,function(a){b.b.f().od(c,d);b.b.f().Dd();a()}))});b.k(function(){f.remove(j)})})(this);this.Fb=function(){a===q&&h({name:"AgentBodyNotInitiatedYet",message:"The body view of the agent has not yet been initated"});return a};this.zd=function(a,b){c=a;d=b}}
function pc(b,a){oc.call(this,b);this.Zb(b);z.debug("Creating LadderView","object");var c=this,d=q,f=q;this.wb=function(a){d=new Kinetic.t.tc(c);f=new Kinetic.t.Bc(c);d.setScale(0.7);f.setScale(0.7);a.add(d);a.add(f)};this.vb=function(a,b,d){c.b.ca()||(c.zd(a,b),c.Fb().setScale(0.8),d.add(c.Fb()))};c.on(Ja,function(){c.aa();c.b.d()&&(c.b.f().jd(),G.play(zb))});c.on(za,function(b){d.on("mousedown touchstart",function(){d.animate();G.play(mb);a.hd()});f.on("mousedown touchstart",function(){f.animate();
G.play(nb)});b()});c.on(Aa,function(){d.off("mousedown touchstart");f.off("mousedown touchstart")});c.on(Ka,function(a){G.play(Nb);c.setTimeout(function(){a();c.c(d.attrs).to({alpha:1},1E3);c.c(f.attrs).to({alpha:1},1E3)},2E3)});c.on(Fa,function(a){G.play(lb);c.b.ca()?c.setTimeout(a,4E3):(c.b.f().D(),c.setTimeout(function(){c.b.f().Gd();c.setTimeout(a,1500)},3E3))});c.on(Ia,function(a){c.Ib(a)});c.on(Ea,function(){c.Db()});c.on("Ladder.betterBecauseBigger",function(){G.play(c.Bb)});c.on("Ladder.betterBecauseSmaller",
function(){G.play(c.Cb)});c.on("Ladder.hmm",function(){G.play(ub)});c.on("Ladder.agentSuggestSolution",function(){c.setTimeout(function(){G.play(c.Aa);c.setTimeout(function(){G.play(c.Aa)},2E3)},2E3)});c.on("Ladder.tooLow",function(){G.play(c.bc);setTimeout(function(){G.play(c.cc)},2E3)});c.on("Ladder.tooHigh",function(){G.play(c.ac);setTimeout(function(){G.play(c.dc)},2E3)});c.on("Ladder.agentTooLow",function(){G.play(c.yb)});c.on("Ladder.agentTooHigh",function(){G.play(c.xb)})}
function ib(b){var a=this;pc.call(this,"MtView",b);z.debug("Constructing MountainView",this.l);a.bc=ac;a.ac=$b;a.cc=cc;a.dc=bc;a.Aa=dc;a.Jd=ec;a.yb=hc;a.xb=ic;a.Bb=fc;a.Cb=gc;a.Mc=jc;var c=r,d=q,f=r,e=new Kinetic.Layer,g=new Kinetic.Layer,j=[],n=new Kinetic.Group({x:400,y:600}),o=new Kinetic.Rect({width:50,height:50,fill:"blue",stroke:"black",strokeWidth:4,offset:{x:25,y:50}});Kinetic.hc=function(a,b){var c=new Kinetic.Group({x:a,y:b}),d=new Kinetic.Circle({fill:"red",stroke:"black",strokeWidth:4,
radius:20}),e=new Kinetic.Line({stroke:"black",strokeWidth:4,points:[0,20,0,65]});c.add(e);c.add(d);return c};a.m(function(){z.debug("Setting up MountainView","mt-view");a.e.add(g);a.e.add(e);var d=new Kinetic.Polygon({points:[50,600,350,600,150,100],fill:"gray",stroke:"black",strokeWidth:4});n.add(new Kinetic.Polygon({points:[0,0,100,0,110,-50,-10,-50],fill:"#993300",stroke:"black",strokeWidth:4}));for(var m=new T.$(730,180,140,140,2),p=0;6>p;p++)(function(d){var g=m.next(),g=new Kinetic.Group({x:g.x,
y:g.y}),l=new Kinetic.Group({x:40,y:40}),n=new Kinetic.Rect({width:140,height:140,fill:"yellow",strokeWidth:4,stroke:"black"});g.add(n);j.push(g);for(var p=0,o=0;o<=d;o++)3===o&&p++,l.add(new Kinetic.hc(30*o-81*p,30*p));g.add(l);g.A=n;g.sb=l;g.on("mousedown touchstart",function(){c&&a.b.Nb()?b.o(d+1):a.b.Mb()&&!f&&(f=k,G.play(pb),setTimeout(function(){G.play(sb);setTimeout(function(){f=r},2E3)},2E3))});e.add(g)})(p);g.add(d);d=b.qa();for(p=0;p<d.length;p++){var x=new Kinetic.Line({points:[280-24*
p,430-60*p,280-24*p+100,430-60*p],stroke:"black",strokeWidth:4});g.add(x)}o.hide();e.add(o);e.add(n);a.on("frame",function(){e.draw()});a.wb(e);a.vb(a.getStage().getWidth()-500,a.getStage().getHeight()-50-252,e);g.draw()});a.aa=function(){d!=q&&d();a.da(n.attrs);a.c(n.attrs).to({x:400,y:600})};a.on(ra,function(a){var c=b.K()-1;o.setX(280-24*c);o.setY(430-60*c);o.show();a()});a.on(Ga,function(){c=r});a.on(N,function(){c=k});a.on(O,s());a.on(Ha,s());this.ra=function(a){a=j[a-1];return{x:a.getX()+a.A.getWidth()/
2,y:a.getY()+a.A.getHeight()/2}};this.o=function(b,e){c=r;var f=j[b-1].sb,g=j[b-1];g.A.setFill("red");var o=g.sb.getX(),D=f.getY();d=function(){a.da(f.attrs);f.setX(o);f.setY(D);f.moveTo(g);g.A.setFill("yellow")};a.c(f.attrs).to({x:-Math.abs(400-g.getX())+20,y:600-g.getY()+-110},4E3).call(function(){f.moveTo(n);f.setX(20);f.setY(-110);f.moveDown();e()})};a.on(ya,function(c){if(a.b.d()&&!b.i()&&!b.h()){a.ra(b.n());G.play(tb);var d=q;a.setTimeout(function(){d=a.b.f().Pb(b.n(),function(){a.setTimeout(function(){b.i()||
(a.o(b.n(),c),a.setTimeout(function(){d(s())},1E3))},3E3)})},1500)}else a.o(b.n(),c)});a.on(xa,function(c){var d=b.n();a.c(n.attrs).to({x:280-24*(d-1)+100,y:430-60*(d-1)},2E3).call(c)});a.on(Ca,function(b){G.play(kc);a.setTimeout(function(){G.play(lc)},2E3);a.c(o.attrs).to({x:n.getX()+50,y:n.getY()+-25},1E3).call(function(){a.c(n.attrs).to({x:400,y:600},3E3);a.c(o.attrs).to({x:450,y:575},3E3).call(function(){a.c(o.attrs).to({x:550,y:600},2E3).call(b)})})});a.on(Da,function(){a.b.d()||b.va()});a.Db=
s();a.Ib=function(a){a()};a.on(M,function(b){function c(){d!=q&&d();b()}600!=n.getY()?a.c(n.attrs).to({x:400,y:600},2E3).call(c):c()});this.k(function(){z.debug("Tearing down MountainView",this.l);a.e.remove(g);a.e.remove(e)})}
function qc(b){b.x===i&&(b.x=0);b.y===i&&(b.y=0);b.min===i&&(b.min=1);b.max===i&&(b.max=6);b.step===i&&(b.step=1);b.width===i&&(b.width=2);b.xa===i&&(b.xa=s());b.C===i&&(b.C=10);b.oa===i&&(b.oa={x:0,y:0});b.ea===i&&(b.ea=1);for(var a=[],c=r,d=r,f={color:"black",blur:10,offset:[3,3],alpha:0.5},e=new T.$(b.oa.x+(b.W+b.C),b.oa.y+(b.max/b.width-1)*(b.V+b.C),-(b.W+b.C),-(b.V+b.C),b.width),g=new Kinetic.Group({x:b.x,y:b.y}),j=b.min;j<=b.max;j+=b.step)(function(j){function o(a,e){e===i&&(e=r);if(!d)if(!e&&
c)b.Tc(j);else if(e||!c){g.ta();b.xa(j);m.attrs.image=b.Oc;m.attrs.shadow=q}}var l=e.next(),l=new Kinetic.Group({x:l.x,y:l.y}),m=new Kinetic.Image({image:b.button,width:b.W,height:b.V,shadow:f}),p=new Kinetic.Image({image:b.za[j],scale:{x:b.ea,y:b.ea},offset:{x:b.za[j].width/2,y:b.za[j].height/2},x:b.W/2,y:b.V/2});l.on("mousedown touchstart",function(){o(0,r)});l.add(m);l.add(p);m.push=o;g.add(l);a[j]=m;a[j].Jb=l})(j);g.Sb=function(){for(var c=b.min;c<=b.max;c=c+b.step){a[c].attrs.image=b.button;
a[c].setShadow(f)}};g.ta=function(){c=k};g.Md=function(){c=r};g.fd=function(){d=k};g.Hc=function(){d=r};g.Yc=function(b){return{x:g.getX()+a[b].Jb.getX()+a[b].getWidth()/2,y:g.getY()+a[b].Jb.getY()+a[b].getHeight()/2}};g.push=function(b){a[b].push(q,k)};return g}
function hb(b){pc.call(this,"TreeView",b);var a=this,c=1/2.083168317,d,f,e,g,j,n=[],o,l,m,p,x,u=q,D,I,A=0,F={},J,W=a.getStage().getHeight()-160,ha=a.getStage().getHeight()-120,y={1:{x:100,y:40,rotation:-Math.PI/9},2:{x:100,y:100,rotation:Math.PI/11},3:{x:200,y:40,rotation:-Math.PI/12},4:{x:200,y:100,rotation:Math.PI/9}};a.bc=Pb;a.ac=Ob;a.cc=Rb;a.dc=Qb;a.Aa=Sb;a.Jd=Tb;a.yb=Wb;a.xb=Xb;a.Bb=Ub;a.Cb=Vb;a.Mc=Yb;f=new qc({x:575,y:180,button:X.ia,Oc:X.gc,W:X.ia.width,V:X.ia.height,C:15,Tc:function(){G.play(pb);
a.setTimeout(function(){G.play(sb);a.setTimeout(s(),2E3)},2E3)},xa:function(c){a.b.Nb()&&b.o(c)},za:{1:X.ic,2:X.jc,3:X.kc,4:X.lc,5:X.mc,6:X.nc},ea:0.75});f.ta();l=new Kinetic.Layer;m=new Kinetic.Layer;a.getStage().add(l);a.getStage().add(m);e=new Kinetic.t.rc({x:244,y:580,scale:0.7*c},a);j=function(){g=a.setInterval(function(){n[b.Z()-1].Cd(a)},4E3)};x=function(){a.clearInterval(g)};I=function(){u.rd(b.va)};a.on(oa,function(){a.a(pa,{x:n[b.Z()-1].getX(),y:n[b.Z()-1].getY()})});a.on(Ga,function(){f.fd()});
a.on(N,function(){f.Hc()});a.on(O,function(){f.Md()});a.on(Ha,function(){f.ta()});D=function(c){u=n[b.Z()-1];a.c(u.attrs).wait(2E3).to({x:100,y:150,rotation:2*Math.PI},1E3).to({rotation:0}).to({y:F[b.K()].getY()+25,rotation:2*Math.PI*(7-b.K())},1E3).to({rotation:0}).call(c)};a.Db=function(){u.qd();x();u.open();f.Sb();l.draw()};a.Ib=function(b){var c=new Kinetic.Image({x:u.getX(),y:u.getY(),image:X.fc,width:128,height:128,offset:{x:64,y:64},scale:{x:0.1,y:0.1}});m.add(c);a.c(c.attrs.scale).to({x:1,
y:1},500).call(function(){a.c(c.attrs).to({y:200},2E3).call(b)})};a.on(ra,function(a){A+=1;D(a)});a.on(ya,function(c){if(a.b.d()&&!b.i()&&!b.h()){a.ra(b.n());G.play(tb);var d=q;a.setTimeout(function(){d=a.b.f().Pb(b.n(),function(){a.setTimeout(function(){b.i()||(a.o(b.n(),c),a.setTimeout(function(){d(s())},1E3))},3E3)})},1500)}else a.o(b.n(),c)});a.on(xa,function(c){p=b.n();a.c(e.attrs).to({y:480},2E3).to({rotation:-Math.PI/8,x:219},1E3).call(function(){1<p?a.c(e.attrs).to({rotation:0,y:430},1E3).call(function(){2<
p?(e.ga(),a.c(e.attrs).to({y:F[p].getY()},500*p).call(function(){e.L();c()})):(e.L(),c())}):c()})});a.on(M,function(c){var d=0;p!==b.K()&&(d=2E3);a.setTimeout(function(){function b(){a.c(e.attrs).to({rotation:0,x:244,y:580},2E3).call(function(){f.Sb();c()})}function d(b){a.c(e.attrs).to({rotation:-Math.PI/16,x:244,y:510},1E3).to({rotation:0,y:530},1E3).call(b)}function g(b){e.ga();a.c(e.attrs).to({y:430},500*p).call(e.L).call(b)}2<p?g(function(){d(b)}):1<p?d(b):b()},d)});a.on(Ca,function(b){e.Ea(function(){function c(){d+=
1;2===d&&b()}var d=0;a.c(u.attrs).to({x:u.getX()+30,y:u.getY()-30}).wait(200).call(function(){G.play(Zb);e.Da(c)}).to({x:650+75*A,y:ha,rotation:3*Math.PI},2E3).to({rotation:0}).call(c).call(function(){a.b.d()||(I(),j())})})});a.on(L,function(){m.draw()});a.k(function(){a.getStage().remove(l);a.getStage().remove(m)});a.aa=function(){a.da(e.attrs)};o=new Kinetic.Image({image:X.P,x:0,y:a.getStage().getHeight()-X.P.height,width:X.P.width,height:X.P.height});l.add(o);l.add(new Kinetic.Image({image:X.Ac,
x:145,y:161}));a.wb(m);a.on("Ladder.helpAgent",s());for(d=0;d<b.qa().length;d+=1)o=b.qa()[d],J=new Kinetic.Group({x:120,y:W-70*d}),F[o]=J;m.add(e);m.add(new Kinetic.Image({image:X.Q,width:X.Q.width,height:X.Q.height,x:182,y:a.getStage().getHeight()-X.Q.height}));this.o=function(b,c){G.play(ob);a.b.Mb()&&f.push(b);c()};this.ra=function(a){return f.Yc(a)};l.add(new Kinetic.Image({x:395,y:-100,image:X.sc}));m.add(f);a.m(function(){a.vb(a.getStage().getWidth()-248,a.getStage().getHeight()-100-252,m);
var b;for(d=0;3>d;d+=1)b=new Kinetic.t.xc({x:y[d+1].x,y:y[d+1].y,rotation:y[d+1].rotation,type:d%3+1,scale:c}),m.add(b),n.push(b)});l.draw()}
function Z(b){Pa.call(this,b);var a=new function(){var a=[];this.c=function(b){T.gd(a,b)||a.push(b);return Tween.get(b)};this.removeTweens=function(a){Tween.removeTweens(a)};this.Ca=function(){for(var b=0;b<a.length;b++)Tween.removeTweens(a[b])}};this.k(function(){z.debug("Tearing down","ViewModule");a.Ca()});this.c=function(b){return a.c(b)};this.da=function(b){a.removeTweens(b)};this.getStage=t("e")};