function h(c){throw c;}var j=void 0,k=!0,p=null,r=!1;function s(){return function(){}}function t(c){return function(){return this[c]}}function v(c){return function(){return c}}Kinetic.z={};var aa=p;window.egame=p;window.onload=function(){aa=new ba;window.egame=aa};WebFontConfig={google:{families:["Nunito::latin","Doppio+One::latin","Nobile:400,700:latin","Galindo::latin"]}};var y=document.createElement("script");y.src=("https:"==document.location.protocol?"https":"http")+"://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js";
y.type="text/javascript";y.async="true";var fa=document.getElementsByTagName("script")[0];fa.parentNode.insertBefore(y,fa);
function ba(){function c(){i.a("Game.loadingSounds");var a=p,d=p;z.debug("Loading sounds...","game");var c=new PreloadJS(r);c.onComplete=function(){clearInterval(a);d=setInterval(function(){i.a("Game.updateImageLoading",{progress:ga.kc()})},50);z.debug("Sounds loaded.","game");i.a("Game.loadingImages");ga.Wa(function(){clearInterval(d);i.a("Game.updateImageLoading",{progress:1});z.debug("Images loaded.","game");setTimeout(function(){i.a("Game.loadingDone");e.start()},D?0:1E3)})};c.installPlugin(SoundJS);
a=setInterval(function(){i.a("Game.updateSoundLoading",{progress:c.progress})},50);G.Ec(b);i.on(ha,function(){G.Kc()},"game");c.loadManifest(G.lc())}var a=new ia;K.Dc();this.applySettings=function(){a.apply();$.cookie("monkeyWorldSettings",JSON.stringify(K.ca()))};this.hideSettings=function(){a.hide()};this.showSettings=function(){a.show()};var b=new Kinetic.Stage({container:"container",width:1010,height:660});b.ze=b.getWidth()/1024;var d=new Kinetic.Layer,g=new Kinetic.Layer,f=new Kinetic.Layer;
b.add(d);b.add(g);b.add(f);b.Mb=d;b.F=g;b.Nb=f;b.Ob=g;b.De=t("F");b.Ce=t("Mb");b.Ee=t("Nb");b.X=r;b.Ae=0;b.ye=0;b.$a=function(){b.X=k};var e=new ja(b),i=e.j,l=function(){var a=0,b=new Kinetic.Text({text:"",fontFamily:"Arial",textFill:"black",textStroke:"white",textStrokeWidth:1,fontSize:18,x:0,y:0}),d=k;i.on(ka,function(){d?(console.info("Turning off FPS display"),g.remove(b),d=r):(console.info("Turning on FPS display"),g.add(b),d=k)},"game");g.add(b);return{Gc:function(d){if(0==a||10<d.time-a)b.setText("FPS: "+
Math.round(1E3/d.timeDiff)),a=d.time}}}();b.onFrame(function(a){D&&l.Gc(a);i.a("frame",{frame:a});g.draw();b.X&&(f.draw(),b.X=r);Tween.tick(a.timeDiff,r)});b.start();i.on("Game.miniGameListenersInitiated Game.viewInitiated",function(){g.moveToTop();f.moveToTop()},"game");d=D?0:2E3;i.a("Game.showLoadingScreen",{time:d});setTimeout(function(){c()},d);this.cb=function(){e.cb()}}
var L="frame",ha="TRIGGER_SUBTITLES",M="TRIGGER_SCORE",ka="TRIGGER_FPS",la="backendScoreUpdateMode",sa="setPitcherLevelBefore",ta="setPitcherLevelSetDropOrigin",ua="MG_LADDER_PLACE_TARGET",va="MG_LADDER_HELPER_APPROACH_TARGET",wa="MG_LADDER_ALLOW_INTERRUPT",xa="MG_LADDER_FORBID_INTERRUPT",ya="Ladder.readyToPick",N="Ladder.resetScene",za="Ladder.getTarget",Aa="Ladder.hasTarget",Ba="Ladder.confirmTarget",Ca="Ladder.cheer",Da="MG_LADDER_IGNORE_INPUT",P="MG_LADDER_ACKNOWLEDGE_INPUT",Ea="MG_LADDER_FORBID_GAMER_INPUT",
Q="MG_LADDER_ALLOW_GAMER_INPUT",Fa="MG_LADDER_GET_TREAT";
function Ga(){var c={},a=[],b=0;this.sa=v("GameEventManager");this.on=function(a,b,f){for(var a=a.split(" "),e=0;e<a.length;e++)a[e]in c||(c[a[e]]=[]),c[a[e]].push(b),b.v=f,z.debug((f===j?"unnamed":f)+" registerd "+a[e],"evm")};this.off=function(a,b){for(var f=0;f<c[a].length;f++)c[a][f].v===b&&c[a].splice(f,1);0==c[a].length&&delete c[a]};this.print=function(){console.log("-------EVENT MANAGER STATE-----------------");for(var a in c){console.log("key: "+a);for(var b=0;b<c[a].length;b++)console.log("   "+
c[a][b].v)}console.log("-------------------------------------------")};this.o=function(d){if(0<b)a.push(d);else{var g=0,f;for(f in c){for(var e=c[f].length,i=0;i<e;i++)c[f][i].v===d&&(c[f].splice(i,1),i--,e--,g++);0==c[f].length&&delete c[f]}z.debug("Forgot "+g+" event registred by "+d,"evm")}};this.a=function(d,g,f){b++;d=c[d];if(d!=j)for(var e=0;e<d.length;e++){var i=d[e];f!=j&&f&&z.debug("      "+d[e].v);i(g)}b--;if(0==b&&0<a.length){for(e=0;e<a.length;e++)this.o(a[e]);a=[]}};this.jb=function(d,
g,f,e){b++;f=c[f];if(f!=j)for(var i=0;i<f.length;i++){var l=f[i];z.debug("      "+f[i].v);l(d,e);g||d()}b--;if(0==b&&0<a.length){for(i=0;i<a.length;i++)this.o(a[i]);a=[]}};this.n=function(a,b,c){this.jb(b,k,a,c)};this.Wa=function(a,b,c){z.debug("Loading images...","view");var e=0,i=Object.size(a),l;for(l in a)b[l]=new Image,b[l].onload=function(){++e>=i&&c()},b[l].src="../res/img/"+a[l]}}var D=r;Kinetic.wa=s();Kinetic.wa.getWidth=s();
function R(c){this.h=c;var a=this;document.onkeypress=function(b){117===b.keyCode?a.a(ha):105===b.keyCode?a.a(M):111===b.keyCode?a.a(ka):115===b.keyCode?a.a("setPitcherLevel",{callback:s()}):console.info("Unhandles key: "+b.keyCode)};this.on=function(a,c,g){this.j.on(a,c,g===j?this.h:g)};this.off=function(a,c){this.j.off(a,c===j?this.h:c)};this.o=function(a){this.j.o(a===j?this.h:a)};this.a=function(a,c,g){g!=j&&g&&z.debug("Out: "+a,this.h);this.j.a(a,c,g)};this.n=function(a,c,g){z.debug("Out: "+
a,this.h);this.j.n(a,c,g)};this.fb=function(b,c,g){return function(f){z.debug("Out: "+c,this.h);a.j.jb(f,b,c,g)}};this.eb=function(b){return a.fb(r,b,j)};this.t=function(b,c){return a.fb(k,b,c)};this.sa=function(){console.log(this.j.sa())};this.ib=function(a){this.h=a}}R.prototype.j=new function(){this.sa=v("NoEventManager");this.on=s();this.a=s();this.off=s();this.o=s()};R.prototype.d=new Kinetic.wa;R.prototype.b=p;
function Ha(){var c=[];this.ab=function(a){c.push(a)};this.J=function(a){var b=a-1;(0>b||b>=c.length)&&h("MonkeyWorld.NoSuchRoundException ("+a+")");return c[b]}}function Ia(){var c=r,a=[];this.la=function(){z.debug("Got mistake report","game");c=k};this.Xa=function(){return c};this.xc=function(b){a.push(b)};this.ja=function(){a.splice(a.length-1)};this.cc=function(){return a}}
function Ja(){this.ab=function(){h("MonkeyWorld.NoMiniGameResultException")};this.J=function(){h("MonkeyWorld.NoMiniGameResultException")}}
function Ka(c){R.call(this,c);var a=this,b=new function(){var a=[];this.setTimeout=function(b,c){var d=setTimeout(b,c);a.push(d);return d};this.setInterval=function(b,c){var d=setInterval(b,c);a.push(d);return d};this.clearTimeout=function(b){a.remove(b);clearTimeout(b)};this.clearInterval=function(b){a.remove(b);clearInterval(b)};this.oa=function(){for(var b=0;b<a.length;b++)clearTimeout(a[b]);delete a;a=[]}},d=[],g=[];this.i=function(a){d.push(a)};this.m=function(){d===p&&h({name:"MW.TearDownAlreadyCalledException",
message:"This module ("+c+") has already been teared down."});b.oa();a.o();for(var f=0;f<d.length;f++)d[f](),d[f]=p;d=p};this.s=function(a){g.push(a)};this.q=function(){g===p&&h({name:"MW.SetupAlreadyCalledException",message:"This module ("+c+") has already been setted up."});for(var a=0;a<g.length;a++)g[a](),g[a]=p;g=p};this.setTimeout=function(a,c){return b.setTimeout(a,c)};this.setInterval=function(a,c){return b.setInterval(a,c)};this.clearTimeout=function(a){b.clearTimeout(a)};this.clearInterval=
function(a){b.clearInterval(a)}}
var K=new function(){var c={global:{language:{f:"en"},monkeySeeRounds:{f:1},triesBeforeGuardianAngel:{f:3}},miniGames:{fishingGame:{targetNumber:{f:2},numberCorrect:{f:1},numberOfFish:{f:7},maxNumber:{f:9}},ladder:{targetNumber:{f:-1}}}};this.ca=function(){return c};this.get=function(a){for(var b=c,d=0;d<arguments.length;d++)b=b[arguments[d]];return b.f};this.set=function(a){for(var b=c,d=0;d<arguments.length-1;d++)b=b[arguments[d]];b.f=arguments[arguments.length-1]};this.Dc=function(){var a=JSON.parse($.cookie("monkeyWorldSettings"));
a!==p&&(c=a)};this.Cc=function(a,b){for(var d=a.split("-"),g=c,f=0;f<d.length;f++)g=g[d[f]];g.f=b}};
function ia(){function c(a,b){for(var d in a)if("object"===typeof a[d]&&a[d].f===j)c(a[d],b+"-"+d);else if(a[d].f!=j){var f=$("#"+b+"-"+d).val();K.Cc(b+"-"+d,f)}}function a(){$("#settings-panel").append('<div id="settings-panel-content">');f=$("#settings-panel-content");f.append("<h1>"+S.get("SETTINGS_LABEL")+"</h1>");f.append("<form>");var a=g.ca(),c;for(c in a)f.append(d(c,2,"")),f.append(b(a[c],2,c));f.append("<button type=\"button\" onclick=\"window['egame']['hideSettings']()\">"+S.get("SETTINGS_CANCEL")+
"</button>");f.append("<button type=\"button\" onclick=\"window['egame']['applySettings']();window['egame']['hideSettings']()\">"+S.get("SETTINGS_APPLY")+"</button>");f.append("</form>");f.append("</div>")}function b(a,c,f){var g;g="<ul>";for(var n in a)if("object"===typeof a[n]&&a[n].f===j)g+=d(n,c+1,f),g+=b(a[n],c+1,f+"-"+n);else{g+="<li>";g+=d(n,c+1,f);var m="",m=m+('<input type="text" id="'+(f+"-"+n)+'" value="'+a[n].f+'" />');g+=m+"</li>"}return g+"</ul>"}function d(a,b,c){var d="",a="SETTINGS_"+
((c===j?"":c+"_")+a).toUpperCase().replace("-","_")+"_LABEL",a=S.get(a);a!=p&&(d+="<h"+b+">"+a+"</h"+b+">");return d}var g=K,f=$("#settings-panel-content");this.apply=function(){var b=g.ca(),d;for(d in b)"object"===typeof b[d]&&c(b[d],d);f.remove();a()};this.show=function(){a();$("#settings-panel").show()};this.hide=function(){f.remove();$("#settings-panel").hide()}}function La(){}function Ma(){}
function Na(c){Ka.call(this,"AgentChooser");var a=[{ga:La,view:Oa},{ga:Ma,view:Pa},{ga:La,view:Oa},{ga:La,view:Oa}];this.dc=function(){return a};this.Zb=function(a){c(a)}}function T(c,a){this.hc=function(){return c};this.jc=function(){return a}}
function ja(c){function a(a){if(q&&!D){var c=m(Qa,function(){c.m();b(a)});c.q();u.a("Game.viewInitiated")}else b(a)}function b(a){if(q&&!D){var b=m(Ra);b.q();u.a("Game.viewInitiated");u.a("Game.demonstrateGarden",{callback:function(){b.m();a()}})}else a()}function d(a){function b(){O=0;u.a("resetPitcherLevel");c.m();u.a("Game.gardenWatered");a!=j&&a()}if(q){var c=m(Ra);c.q();u.a("Game.waterGarden",{callback:function(){b()}})}else b()}function g(){u.a("Game.stopMiniGame");q&&ma.m();B.stop();B.m();
delete B;U=0;B=E;u.a("miniGameDone")}function f(){na();B.q();q&&(oa=m(pa,B),oa.q(),u.a("Game.miniGameListenersInitiated"));if("Monkey Do"===x){var a=ca.J(da).cc();B.play(H,a)}else B.play(H)}function e(a){if(0<C.length){var b=C[0];C.splice(0);var c=b.hc();o(b.jc());qa=c;na=function(){B=m(c.b);pa=c.view};a()}else u.a("Game.showMiniGameChooser",{callback:function(b){qa=b;na=function(){u.a("Game.hideMiniGameChooser");B=m(b.b);pa=b.view};o(J);a()},bc:Sa})}function i(){ca=new Ha;H=A;x="Child Play";q&&(ma=
m(Ta),ma.q());e(function(){l(0);f();u.a("miniGameStarted",{},k)})}function l(a){U=a;u.a("backendScoreGameUpdateMiniGame",{Bc:U})}function o(a){u.a("learningTrackUpdate",{sc:a},k)}function n(a){a>K.get("global","monkeySeeRounds")&&("Monkey See"===x||"Monkey Do"===x)&&h("MonkeyWorld.MiniGameRoundOverMaxLimit");1>a&&h("MonkeyWorld.MiniGameRoundUnderMinLimit");da=a}function m(a,b){a.prototype.j=u.j;a.prototype.b=u;a.prototype.d=c;var d=p;return d=b===j?new a:b!=j?new a(b):new a(b,j,j,j)}var q=k,w=!D,
u=this;R.call(this,"Game");this.j=new Ga;this.d=c;this.b=this;var E=new Ua,I=new Ja,A=m(Va),F=m(Wa),J=new Xa,V=new Ya,ea=new Za,x="Child Play",B=E,pa=p,oa=p,ma=p,na=p,H=A,da=1,ca=I,U=0,qa=p,O=0,ra=p,C=[];q===j&&(q=k);w===j&&(w=k);q&&m($a);this.tc=function(){B===E&&h({name:"MonkeyWorld.NoActiveMiniGameException",message:"There is no active minigame"});q&&oa.m();l(U+B.ec());if("Child Play"===x)x="Monkey See",f();else if("Monkey See"===x){var a=B.J();ca.ab(a);x="Monkey Do";H=F;f()}else if("Monkey Do"===
x)if(da===K.get("global","monkeySeeRounds")){n(1);x="Child Play";H=A;g();var a=qa,b=U;26<b&&30>=b?(C.push(new T(a,ea)),C.push(new T(a,ea))):22<b&&26>=b?(C.push(new T(a,V)),C.push(new T(a,V)),C.push(new T(a,V))):0<=b&&22>=b?(C.push(new T(a,J)),C.push(new T(a.Yb.ra[0],J)),C.push(new T(a,J)),C.push(new T(a,J)),C.push(new T(a,J))):h("MW.NoSuchMinigameScore");i()}else n(da+1),f()};this.aa=function(){return ra};this.start=function(){var b=p,c=p;a(function(){w?(b=m(Na,function(a){b.m();c!=p&&c.m();ra=new a.view;
i()}),q&&(c=m(ab,b),c.q(),u.a("Game.viewInitiated"))):(ra=new Pa,i())})};this.stop=function(){g();x="Child Play";n(1);H=A;ca=I;this.a("Game.stop")};this.cb=function(){this.stop();this.start()};this.Ub=function(a){console.log("addWaterDrop");u.a(sa);u.a("setPitcherLevel",{callback:function(){6===O?(console.log("OK"),d(a)):a!=j&&a()}});O+=1;console.log(O)};this.mc=function(){return O};this.gb=function(){H=F};this.hb=function(){H=A};this.Za=function(){return H===A};this.Ya=function(){return H===F};this.fa=
function(){return"Child Play"===x};this.ea=function(){return"Monkey See"===x};this.e=function(){return"Monkey Do"===x}}function Za(){}Za.prototype.name=v("Fast");function Ya(){}Ya.prototype.name=v("Medium");function Xa(){}Xa.prototype.name=v("Regular");
function bb(){function c(){E=r;e.b.e()&&e.a(xa)}function a(a){E=k;e.b.e()&&!e.k()?e.n(wa,a):a()}function b(){n=W.I(i,l);I+=1;W.H(e.t(ua),function(){e.a(ya);e.a(P,{},k);e.b.e()||e.a(Q,{},k)})()}function d(a){u=k;W.H(e.t(za),e.t(N),e.eb(Aa),function(){e.Ha("correct");u=r;a()})()}function g(a){e.n(N,function(){e.a(P,{},k);e.b.e()||e.a(Q);e.la();e.a("Ladder.incorrect");4<=F&&e.a("Ladder.agentSuggestSolution");e.Ha("incorrect");a()})}function f(){var a=3<=q,c=1<=w;3===w||a&&c?(console.log("checkok"),W.H(e.t(Ca),
e.Ac)()):(console.log("placetreat"),b())}cb.call(this,"Ladder");var e=this,i=1,l=6,o=[],n=W.I(i,l),m=p,q=0,w=0,u=r,E=r,I=0,A=0,F=0;e.s(function(){var a,b=0;for(a=i;a<=l;a+=1)o[b]=a,b+=1});this.ia=function(){w+=1;e.b.fa()?(e.n(Ba),e.n(Fa,f)):(e.a(Ba),e.b.Ub(f))};this.p=function(b){m=b;q+=1;W.H(a,e.t("Ladder.picked",{ha:b,Be:b===n}),e.eb(Da),function(a){F=e.g()?F+1:0;e.g()&&b===n&&e.oc();a()},function(a){b===n&&(b<A&&(e.k()||e.g()))&&e.a("Ladder.betterBecauseSmaller");b===n&&(b>A&&(e.k()||e.g()))&&
e.a("Ladder.betterBecauseBigger");b!==n&&(e.k()||e.g())&&e.a("Ladder.hmm");e.b.e()&&(A=b);if(e.b.e()&&!e.g()||e.g()&&b===n)e.zc(),e.a(Ea,{},k);a()},e.t(va),function(a){c();b===n?d(a):g(a);b<n&&(e.b.e()&&!e.k()&&!e.g())&&e.a("Ladder.agentTooLow");b>n&&(e.b.e()&&!e.k()&&!e.g())&&e.a("Ladder.agentTooHigh");b<n&&(e.b.ea()||e.k()||e.g())&&e.a("Ladder.tooLow");b>n&&(e.b.ea()||e.k()||e.g())&&e.a("Ladder.tooHigh");m=p})()};this.L=function(){return n};this.Ra=function(){var a=W.I(0,o.length-1);return o[a]===
n?this.Ra():o[a]};this.Qa=function(){m===p&&h({name:"No number chosen yet",b:"Ladder",message:"A chosen number was asked for in the Ladder Game, but no number has yet been chosen by the user or the agent."});return m};this.K=function(){0===I&&h("MinigameNotStartedException");return I};this.ba=function(){return o};this.Rb(function(){E&&e.b.e()&&(c(),e.ja(),u||(e.a(Q,{},k),e.a("Ladder.interrupt",{}),e.n(N,function(){e.a(P,{},k)})))});this.Sb(function(){e.a(Da,{},k);e.a(Ea,{},k);e.a("Ladder.start");
e.b.ea()?e.n("Ladder.introduceAgent",b):e.b.e()?e.n("Ladder.startAgent",b):b()});this.Tb(function(){e.a("Game.roundDone")})}
function cb(c){Ka.call(this,c);var a=this,b=[],d=[],g=r,f=r,e=p,i=10,l=p;this.Ha=function(a){e.xc(a)};this.ja=function(){e.ja()};this.Sb=function(a){b.push(a)};this.Tb=function(a){d.push(a)};this.start=function(){g&&h({name:"MW.MinigameModuleAlreadyStarted",message:"This minigame module ("+c+") has already been started."});for(g=k;0<b.length;)b.shift()()};this.stop=function(){f&&h({name:"MW.MinigameModuleAlreadyStopped",message:"This minigame module ("+c+") has already been stopped."});for(f=k;0<
d.length;)d.shift()()};this.la=function(){0<i&&(i--,a.a(la,{Ma:i},k));e.la()};this.Xa=function(){return e.Xa()};this.J=function(){return e};this.ec=function(){return i};this.Ac=function(){z.debug("Round done","game");a.a("Game.roundDone");a.a("Game.nextRound");a.b.tc()};this.play=function(b,c){i=10;a.a(la,{Ma:i},k);e=new Ia;console.log(this.h);l=new b.U[this.h](this,c);this.start()};var o=r,n=r,m=[];this.rc=function(){o=k;l.N();a.b.hb();for(var b=0;b<m.length;b+=1)m[b]()};this.Rb=function(a){m.push(a)};
this.zc=function(){o=r;a.b.gb();l.yc()};this.k=function(){return o};this.nc=function(){n=k;a.b.hb()};this.oc=function(){n=r;a.b.gb()};this.g=function(){return n}}function Ua(){this.play=function(){h("No implemented mini game")}}Ua.prototype=new cb("NoMiniGame");var Sa=function(){var c={xd:{se:{b:bb,view:db,title:"Tree Game"},me:{b:bb,view:eb,title:"Mountain Game"}}},a;for(a in c){var b=0,d=c[a],g=[],f;for(f in d)g.push(d[f]),d[f].Yb=d,b++;d.ra=g;d.Jc=function(){return b}}return c}();
function Va(){R.call(this,"GamerPlayer");this.ib("GamerPlayer");z.debug("Creating GamerPlayer","player");this.U=s();this.U.Ladder=s()}
function Wa(){z.debug("Creating MonkeyPlayer","player");R.call(this,"MonkeyPlayer");var c=this;this.U=s();this.U.Ladder=function(a,b){function d(c){f||(i++,setTimeout(function(){z.debug("Picking a number","agent");c===e||"incorrect"===b[c]?a.p(a.Ra()):a.p(a.L())},2E3))}z.debug("Applying MonkeyPlayer's strategy to the Ladder","player");var g=0,f=r,e=W.I(0,b.length-1);z.debug("Will make mistake on try number "+e+1,"agent");var i=0;c.on("Ladder.readyToPick",function(){d(g++)});c.on("Ladder.incorrect",
function(){a.k()||(4>i?d(g++):4===i&&!a.g()&&(G.play(fb),a.nc()))});c.on("Ladder.correct",function(){i=0});this.N=function(){z.debug("Interrupting agent","agent");f=k;i=0};this.yc=function(){z.debug("Resuming agent","agent");f=r};c.on("Ladder.hasTarget",function(){setTimeout(function(){a.ia()},1500)});c.on("Game.stopMiniGame",function(){c.o()})}}
var gb={ie:"monkey.png",ob:"balloons.png",Hb:"Symbol-Stop.png",Gb:"Symbol-Check.png",zb:"Jungle_Bkg.png",Zc:"elephant.png",fe:"lion.png",od:"giraff.png",xb:"bg-garden.png",yb:"bg-sadgarden.png",A:"minigames/treegame/background.png",Kb:"minigames/treegame/treedots.png",B:"minigames/treegame/lizard_cover.png",u:"minigames/treegame/lizard/lizard-standing.png",Ib:"minigames/treegame/lizard/lizard-step1.png",Ba:"minigames/treegame/lizard/lizard-step2.png",xa:"minigames/treegame/lizard/mouth-1.png",ya:"minigames/treegame/lizard/mouth-2.png",
za:"minigames/treegame/lizard/mouth-3.png",Aa:"minigames/treegame/lizard/mouth-4.png",C:"minigames/treegame/lizard/tongue/tongue-1.png",Ca:"minigames/treegame/lizard/tongue/tongue-2.png",Da:"minigames/treegame/lizard/tongue/tongue-3.png",Ea:"minigames/treegame/lizard/tongue/tongue-4.png",Jb:"minigames/treegame/lizard/tongue/tongue-last.png",Bb:"nrpad.png",Cb:"minigames/treegame/paket-1.png",Db:"minigames/treegame/paket-2.png",Eb:"minigames/treegame/paket-3.png",V:"buttons/wood.png",pb:"buttons/wood-selected.png",
rb:"numbers/dots/prick-1.png",sb:"numbers/dots/prick-2.png",tb:"numbers/dots/prick-3.png",ub:"numbers/dots/prick-4.png",vb:"numbers/dots/prick-5.png",wb:"numbers/dots/prick-6.png",Xc:"moln.png",D:"vattendroppe.png",l:"vattenkanna.png",W:"vattenkanna-botten.png",va:"agents/mouse/normal.png",Oc:"agents/mouse/normal-no-arm.png",ua:"agents/mouse/head.png",ta:"agents/mouse/facials/m-normal.png",Mc:"agents/mouse/facials/m-glad.png",Nc:"agents/mouse/facials/m-suprised.png"},X={},ga=function(){var c={},a=
0,b=0,d;for(d in X)a++;c.kc=function(){return b};c.Wa=function(c){z.debug("Loading images...","images");var d=0,e=Object.size(gb),i;for(i in gb){var l=gb[i];X[i]=new Image;X[i].onload=function(){++d>=e&&c();b=d/a};X[i].src="../res/img/"+l}};return c}();function Y(c,a,b){this.R=c;this.Hc=a;this.Pb=a!=p;this.Va=b}
var hb=new Y("19446__totya__yeah","YAY"),ib=new Y("27882__stickinthemud__bike-horn-double-toot",p),jb=new Y("60443__jobro__tada1",p),kb=new Y("406__tictacshutup__click-1-d",p,4),lb=new Y(p,"NO_MY_TURN"),mb=new Y(p,"CHOOSE_YOUR_FRIEND"),nb=new Y(p,"THANKS_FOR_CHOOSING_ME"),ob=new Y(p,"BUT_YOU_CAN_INTERRUPT"),pb=new Y(p,"IM_GOING_TO_PICK_THIS_ONE"),qb=new Y(p,"MAYBE_THAT_WORKS"),rb=new Y(p,"YAY_HELPED_ME_GET_WATER_DROP_1"),sb=new Y(p,"YAY_HELPED_ME_GET_WATER_DROP_2"),tb=new Y(p,"LETS_FILL_THE_BUCKET"),
ub=new Y(p,"WHICH_ONE_DO_YOU_THINK_IT_IS"),vb=new Y("25879__acclivity__drip1",p),wb=new Y(p,"INTRO_1"),xb=new Y(p,"INTRO_2"),yb=new Y(p,"INTRO_3"),zb=new Y(p,"INTRO_4"),Ab=new Y(p,"INTRO_5"),Bb=new Y(p,"INTRO_GARDEN_1"),Cb=new Y(p,"INTRO_GARDEN_2"),Db=new Y(p,"LADDER_LOOKS_FUN"),Eb=new Y(p,"LADDER_SHOW_ME"),Fb=new Y(p,"LADDER_MY_TURN"),fb=new Y(p,"LADDER_PLEASE_HELP_ME"),Gb=new Y(p,"LADDER_TREE_OOPS_TOO_HIGH"),Hb=new Y(p,"LADDER_TREE_OOPS_TOO_LOW"),Ib=new Y(p,"LADDER_TREE_TRY_A_SMALLER_NUMBER"),Jb=
new Y(p,"LADDER_TREE_TRY_A_BIGGER_NUMBER"),Kb=new Y(p,"LADDER_TREE_AGENT_SUGGEST_SOLUTION_1"),Lb=new Y(p,"LADDER_TREE_AGENT_SUGGEST_SOLUTION_2"),Mb=new Y(p,"LADDER_TREE_BETTER_BECAUSE_BIGGER"),Nb=new Y(p,"LADDER_TREE_BETTER_BECAUSE_SMALLER"),Ob=new Y(p,"LADDER_TREE_AGENT_PLAY_TOO_LOW"),Pb=new Y(p,"LADDER_TREE_AGENT_PLAY_TOO_HIGH"),Qb=new Y(p,"LADDER_TREE_AGENT_SEE_CORRECT"),Rb=new Y("34208__acclivity__tongueclick1",p),Sb=new Y(p,"LADDER_MOUNTAIN_IM_DOWN_HERE"),Tb=new Y(p,"LADDER_MOUNTAIN_IM_UP_HERE"),
Ub=new Y(p,"LADDER_MOUNTAIN_TRY_FEWER_BALLOONS"),Vb=new Y(p,"LADDER_MOUNTAIN_TRY_MORE_BALLOONS"),Wb=new Y(p,"LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_1"),Xb=new Y(p,"LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_2"),Yb=new Y(p,"LADDER_MOUNTAIN_BETTER_BECAUSE_BIGGER"),Zb=new Y(p,"LADDER_MOUNTAIN_BETTER_BECAUSE_SMALLER"),$b=new Y(p,"LADDER_MOUNTAIN_AGENT_PLAY_TOO_LOW"),ac=new Y(p,"LADDER_MOUNTAIN_AGENT_PLAY_TOO_HIGH"),bc=new Y(p,"LADDER_MOUNTAIN_AGENT_SEE_CORRECT"),cc=new Y(p,"LADDER_MOUNTAIN_YOU_SAVED_ME"),
dc=new Y(p,"LADDER_MOUNTAIN_IM_HUNGRY"),ec={ue:hb,Qc:ib,pe:jb,Wc:kb,oe:lb,Vc:mb,qe:nb,Tc:ob,pd:pb,xe:new Y(p,"YES_I_THINK_THAT_ONE_IS_BETTER"),he:qb,ve:rb,we:sb,de:tb,te:ub,ke:new Y(p,"MONKEY_HMM"),ge:new Y("51710__bristolstories__u-chimes3_short",p),Yc:vb,qd:wb,rd:xb,sd:yb,td:zb,ud:Ab,vd:Bb,wd:Cb,Bd:Db,Rd:Eb,Pd:Fb,zd:new Y(p,"LADDER_IS_IT_RIGHT"),Ad:new Y(p,"LADDER_IT_WAS_RIGHT"),Qd:fb,yd:new Y(p,"LADDER_AGENT_HELP_IN_INTERRUPT"),Zd:Gb,$d:Hb,ce:Ib,be:Jb,Vd:Kb,Wd:Lb,Xd:Mb,Yd:Nb,Td:Ob,Sd:Pb,Ud:Qb,
ae:Rb,Jd:Sb,Ld:Tb,Md:Ub,Nd:Vb,Fd:Wb,Gd:Xb,Hd:Yb,Id:Zb,Dd:$b,Cd:ac,Ed:bc,Od:cc,Kd:dc,NUMBER_1:new Y(p,"NUMBER_1"),NUMBER_2:new Y(p,"NUMBER_2"),NUMBER_3:new Y(p,"NUMBER_3"),NUMBER_4:new Y(p,"NUMBER_4"),NUMBER_5:new Y(p,"NUMBER_5"),NUMBER_6:new Y(p,"NUMBER_6"),NUMBER_7:new Y(p,"NUMBER_7"),NUMBER_8:new Y(p,"NUMBER_8"),NUMBER_9:new Y(p,"NUMBER_9"),NUMBER_10:new Y(p,"NUMBER_10"),Pc:new Y(p,"ARE_YOU_READY_TO_TEACH"),nd:new Y(p,p,2),fd:new Y(p,"FISHING_FREE_WRONG_ONES"),cd:new Y(p,"FISHING_CATCH"),hd:new Y(p,
"FISHING_NOT_THIS_ONE"),ld:new Y(p,"FISHING_THERE_ARE_MORE"),gd:new Y(p,"FISHING_KEEP_GOING"),bd:new Y(p,"FISHING_ARE_YOU_SURE"),dd:new Y(p,"FISHING_COUNT_FISH"),ed:new Y(p,"FISHING_COUNT_TARGET_FISH"),md:new Y(p,p),jd:new Y(p,p),kd:new Y(p,p),$c:new Y(p,"FISHING_ANGEL_CHOOSE_FISH"),ad:new Y(p,"FISHING_ANGEL_COUNT"),Sc:new Y(p,"BUBBA_HI"),Rc:new Y(p,"BUBBA_HERE_TO_HELP"),le:new Y(p,"MONKEY_LEARNED_WELL"),je:new Y(p,"MONKEY_DIDNT_LEARN_WELL"),ee:new Y(p,"LETS_SHOW_HIM_AGAIN"),re:new Y(p,"THANK_YOU_FOR_HELPING"),
ne:new Y(p,"NOW_MONKEY_SHOW_YOU")},G=function(){function c(a){for(var b=0;b<g.length;b++)g[b].attrs.y-=30;g.push(a)}var a={},b=p,d=p,g=[],f=p,e=k;a.Ec=function(a){b=a;d=b.Ob};a.lc=function(){if(f===p){f=[];for(var a in ec){var b=ec[a];ec[a].Ga=a;if(b.R!=p){var c={id:a,src:"../res/sound/"+b.R+".ogg|../res/sound/"+b.R+".mp3"};b.Va!=j&&(c.data=b.Va);f.push(c)}}}return f};a.play=function(a){var f=a.Hc;z.uc('"'+f+'"');if(e&&a.Pb){var o=new Kinetic.Text({x:0,y:d.getParent().attrs.height-50,text:S.get(f),
fontSize:26,fontFamily:"Nobile",textFill:"white",textStroke:"black",align:"center",fontStyle:"bold",width:d.getParent().getWidth(),height:50,verticalAlign:"middle",textStrokeWidth:2});c(o);d.add(o);b.$a();setTimeout(function(){d.remove(o);b.$a();for(var a=0;a<g.length;a++)g[a]===o&&g.splice(a,1)},3E3)}a.R!=p&&SoundJS.play(a.Ga)};a.stop=function(a){SoundJS.stop(a.Ga)};a.Kc=function(){e?(e=r,console.info("Turning off subtitles")):(e=k,console.info("Turning on subtitles"))};return a}(),S=function(){var c=
{INIT_LOADING_SOUNDS:{sv:"Laddar ner ljud...",en:"Downloading sounds..."},INIT_LOADING_IMAGES:{sv:"Laddar ner bilder...",en:"Downloading images..."},RESTART:{sv:"Starta om",en:"Restart"},SETTINGS:{sv:"Inst\u00e4llningar",en:"Settings"},YAY:{sv:"Hurra!",en:"Yay!"},INTRO_1:{sv:"Hej! De h\u00e4r v\u00e4nnerna beh\u00f6ver din hj\u00e4lp",en:"Hello! These friends need your help"},INTRO_2:{sv:"med att f\u00e5 deras tr\u00e4dg\u00e5rd att v\u00e4xa.",en:"to make their garden grow."},INTRO_3:{sv:"Om du kan l\u00e4ra din v\u00e4n hur man spelar spelen",
en:"If you can teach your friend how to do the games"},INTRO_4:{sv:"kan han eller hon samla vattendroppar -",en:"he or she can collect water drops -"},INTRO_5:{sv:"- f\u00f6r att f\u00e5 deras tr\u00e4dg\u00e5rd att v\u00e4xa -",en:"- to make their garden grow again -"},INTRO_GARDEN_1:{sv:"- fr\u00e5n det h\u00e4r...",en:"- from this..."},INTRO_GARDEN_2:{sv:"...till det h\u00e4r!",en:"...to this!"},CHOOSE_YOUR_FRIEND:{sv:"B\u00f6rja med att v\u00e4lja vilken v\u00e4n du vill hj\u00e4lpa!",en:"First, choose the friend you would like to teach!"},
THANKS_FOR_CHOOSING_ME:{sv:"Ja! Tack f\u00f6r att du valde mig!",en:"Yay! Thanks for choosing me!"},ARE_YOU_READY_TO_TEACH:{sv:"\u00c4r du redo att l\u00e4ra apan?",en:"Are you ready to teach monkey?"},NO_MY_TURN:{sv:"Gl\u00f6m inte att det \u00e4r MIN tur nu!",en:"Remember it\u2019s MY turn now!"},BUT_YOU_CAN_INTERRUPT:{sv:"Men du kan avbryta mig om jag g\u00f6r fel.",en:"But you can interrupt me if I'm making a mistake."},MAYBE_THAT_WORKS:{sv:"Okej, vi testar och ser om det \u00e4r r\u00e4tt.",
en:"OK, let's see if this works."},YAY_HELPED_ME_GET_WATER_DROP_1:{sv:"Hurra! Du hj\u00e4lpte mig att f\u00e5 en vattendroppe",en:"Yay! You helped me get a water drop"},YAY_HELPED_ME_GET_WATER_DROP_2:{sv:"till min tr\u00e4dg\u00e5rd, s\u00e5 den kan v\u00e4xa!",en:"for my garden to grow again!"},LETS_FILL_THE_BUCKET:{sv:"Kom igen och fyll kannan!",en:"Let's fill the bucket!"},WHICH_ONE_DO_YOU_THINK_IT_IS:{sv:"Vilken tror du att det \u00e4r?",en:"Which one do you think it is?"},YES_I_THINK_THAT_ONE_IS_BETTER:{sv:"Ja, det d\u00e4r fungerar nog b\u00e4ttre!",
en:"Yes, I think that one is better!"},LADDER_TREE_BETTER_BECAUSE_BIGGER:{sv:"Ja, det verkar vara ett bra val, eftersom den \u00c4R st\u00f6rre!",en:"Yes, that seems to be a good choice because it IS bigger!"},LADDER_TREE_BETTER_BECAUSE_SMALLER:{sv:"Ja, det verkar vara ett bra val, eftersom den \u00c4R mindre!",en:"Yes, that seems to be a good choice because it IS smaller!"},IM_GOING_TO_PICK_THIS_ONE:{sv:"Okej, f\u00e5r se om den h\u00e4r fungerar. Hmm...",en:"Ok, let's see if this works. Hmm..."},
FISHING_CATCH_NUMBER:{sv:"F\u00e5nga nummer %1",en:"Catch number %1"},FISHING_CATCH:{sv:"F\u00e5nga",en:"Catch"},FISHING_FREE_WRONG_ONES:{sv:"Frige fiskarna som \u00e4r fel",en:"Put back the wrong fish"},FISHING_NOT_THIS_ONE:{sv:"Inte den!",en:"Not this one!"},FISHING_THERE_ARE_MORE:{sv:"Det finns mer fiskar att f\u00e5nga. Forts\u00e4tt leta!",en:"There are more fish to catch. Keep looking!"},FISHING_ARE_YOU_SURE:{sv:"\u00c4r du s\u00e4ker?",en:"Are you sure?"},FISHING_COUNT_FISH:{sv:"R\u00e4kna fiskarna!",
en:"Count the fish!"},FISHING_COUNT_TARGET_FISH:{sv:"R\u00e4kna fiskarna med",en:"Count the fish with"},FISHING_ANGEL_CHOOSE_FISH:{sv:"Jag v\u00e4ljer den h\u00e4r fisken eftersom...",en:"I choose this fish, because it..."},FISHING_ANGEL_COUNT:{sv:"Jag v\u00e4ljer den h\u00e4r siffran eftersom...",en:"I choose this number, because..."},LADDER_LOOKS_FUN:{sv:"Det d\u00e4r s\u00e5g kul ut!",en:"That looked fun!"},LADDER_SHOW_ME:{sv:"Visa mig hur man g\u00f6r!",en:"Now show me how to do it!"},LADDER_MY_TURN:{sv:"Okej, nu ska vi se om jag klarar det h\u00e4r sj\u00e4lv!",
en:"Ok, now let's see if I can do this on my own!"},LADDER_IS_IT_RIGHT:{sv:"G\u00f6r jag r\u00e4tt eller fel?",en:"Am I doing it right or wrong?"},LADDER_IT_WAS_RIGHT:{sv:"Ja! Du fick presenten!",en:"Yeah! You got it!"},LADDER_TREE_OOPS_TOO_HIGH:{sv:"Oj, kanske tog vi i f\u00f6r mycket!",en:"Oops! Maybe we overdid it!"},LADDER_TREE_OOPS_TOO_LOW:{sv:"Hmm... Kanske var det inte tillr\u00e4ckligt!",en:"Hmm... Maybe it wasn't enough!"},LADDER_TREE_TRY_A_SMALLER_NUMBER:{sv:"Vi kan v\u00e4l testa en mindre och se vad som h\u00e4nder!",
en:"Let's try a smaller one and see what happens!"},LADDER_TREE_TRY_A_BIGGER_NUMBER:{sv:"Vad tror du? Ska vi testa en st\u00f6rre?",en:"What do you think? Shall we try a bigger one?"},LADDER_TREE_AGENT_PLAY_TOO_LOW:{sv:"Hmm, det gick inte. Jag undrar varf\u00f6r. Jag testar en st\u00f6rre!",en:"Hmm, that didn't work. I wonder why. Let me try a bigger one!"},LADDER_TREE_AGENT_PLAY_TOO_HIGH:{sv:"\u00c5h, nej! Var den f\u00f6r stor?",en:"Oh no! Was that too big?"},LADDER_TREE_AGENT_SEE_CORRECT:{sv:"WOO! Tack f\u00f6r hj\u00e4lpen! Vilken fin present!",
en:"WOO! Thank you for helping me! What a great surprise!"},LADDER_TREE_AGENT_SUGGEST_SOLUTION_1:{sv:"Kanske kan vi f\u00f6rs\u00f6ka med samma siffra p\u00e5",en:"Maybe we should match the number on"},LADDER_TREE_AGENT_SUGGEST_SOLUTION_2:{sv:"nummerplattan som vid presenten?",en:"the number pad to the number by the gift?"},LADDER_PLEASE_HELP_ME:{sv:"Kan du hj\u00e4lpa mig att v\u00e4lja r\u00e4tt?",en:"Can you please help me find the right one?"},LADDER_MOUNTAIN_IM_DOWN_HERE:{sv:"Jag \u00e4r h\u00e4r nere!",
en:"I'm down here!"},LADDER_MOUNTAIN_IM_UP_HERE:{sv:"Jag \u00e4r h\u00e4r uppe!",en:"I'm up here!"},LADDER_MOUNTAIN_YOU_SAVED_ME:{sv:"Du r\u00e4ddade mig!!!",en:"You saved me!!!"},LADDER_MOUNTAIN_IM_HUNGRY:{sv:"Jag \u00e4r hungrig. Kom s\u00e5 g\u00e5r vi och \u00e4ter!",en:"I'm hungry. Let's go eat!"},LADDER_MOUNTAIN_TRY_FEWER_BALLOONS:{sv:"Kanske ska vi testa med f\u00e4rre ballonger?",en:"Perhaps we should try with fewer balloons?"},LADDER_MOUNTAIN_TRY_MORE_BALLOONS:{sv:"Vi kan v\u00e4l testa med fler ballonger och se vad som h\u00e4nder?",
en:"Let's try with more balloons and see what happens!"},LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_1:{sv:"Kanske kan vi f\u00f6rs\u00f6ka med lika m\u00e5nga ballonger",en:"Maybe we should match the number of balloons"},LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_2:{sv:"som niv\u00e5er upp din v\u00e4n \u00e4r.",en:"to the level your friend is stuck on."},LADDER_MOUNTAIN_AGENT_PLAY_TOO_LOW:{sv:"Oj, det kanske var f\u00f6r f\u00e5 ballonger.",en:"Oops, maybe I used to few balloons."},LADDER_MOUNTAIN_AGENT_PLAY_TOO_HIGH:{sv:"Hoppsan, det var nog f\u00f6r m\u00e5nga ballonger!",
en:"Oops, I think there were too many balloons!"},LADDER_MOUNTAIN_BETTER_BECAUSE_BIGGER:{sv:"Ja, det fungerar nog, f\u00f6r det \u00c4R fler ballonger!",en:"Yes, this can work, beacuse that IS more ballons!"},LADDER_MOUNTAIN_BETTER_BECAUSE_SMALLER:{sv:"Ja, det fungerar nog, f\u00f6r det \u00c4R f\u00e4rre ballonger!",en:"Yes, this will probably work, beacuse that IS fewer balloons!"},LADDER_MOUNTAIN_AGENT_SEE_CORRECT:{sv:"WOO! Tack f\u00f6r hj\u00e4lpen! Vi r\u00e4ddade v\u00e5r v\u00e4n!",en:"WOO! Thank you for helping me! We saved our friend!"},
BUBBA_HI:{sv:"Hej! Mitt namn \u00e4r Bubba!",en:"Hi, my name is Bubba!"},BUBBA_HERE_TO_HELP:{sv:"Jag ska hj\u00e4lpa dig och apan l\u00e4ngs v\u00e4gen.",en:"I'm here to help you and monkey throughout his journey."},MONKEY_LEARNED_WELL:{sv:"Toppen! Apan l\u00e4rde sig bra!",en:"Great! Monkey learned well!"},MONKEY_DIDNT_LEARN_WELL:{sv:"\u00c5h, nej! Apan l\u00e4rde sig inte riktigt.",en:"Oh no! Monkey didn't learn well."},LETS_SHOW_HIM_AGAIN:{sv:"Visa honom igen!",en:"Let's show him again!"},THANK_YOU_FOR_HELPING:{sv:"Tack f\u00f6r att du hj\u00e4lpte apan!",
en:"Thank you for helping monkey!"},NOW_MONKEY_SHOW_YOU:{sv:"Nu visar apan dig vad den har l\u00e4rt sig!",en:"Now monkey show you what it learned!"},MONKEYS_TURN:{sv:"Apans tur!",en:"Monkey's turn!"},MONKEY_HMM:{sv:"Apan: Hmmm...",en:"Monkey: Hmm..."},FISHING_KEEP_GOING:{sv:"Forts\u00e4tt!",en:"Keep going!"},NUMBER_1:{sv:"nummer 1",en:"number 1"},NUMBER_2:{sv:"nummer 2",en:"number 2"},NUMBER_3:{sv:"nummer 3",en:"number 3"},NUMBER_4:{sv:"nummer 4",en:"number 4"},NUMBER_5:{sv:"nummer 5",en:"number 5"},
NUMBER_6:{sv:"nummer 6",en:"number 6"},NUMBER_7:{sv:"nummer 7",en:"number 7"},NUMBER_8:{sv:"nummer 8",en:"number 8"},NUMBER_9:{sv:"nummer 9",en:"number 9"},NUMBER_10:{sv:"nummer 10",en:"number 10"},SETTINGS_LABEL:{sv:"Inst\u00e4llningar",en:"Settings"},SETTINGS_APPLY:{sv:"Verkst\u00e4ll",en:"Apply"},SETTINGS_SHOW:{sv:"Visa inst\u00e4llningar",en:"Show settings"},SETTINGS_HIDE:{sv:"G\u00f6m inst\u00e4llningar",en:"Hide settings"},SETTINGS_CANCEL:{sv:"Avbryt",en:"Cancel"},SETTINGS_GLOBAL_LABEL:{sv:"Globala",
en:"Global"},SETTINGS_GLOBAL_LANGUAGE_LABEL:{sv:'Spr\u00e5k (kan vara "sv" eller "en" och kr\u00e4ver omstart)',en:'Language (can be "sv" or "en" and requires restart)'},SETTINGS_GLOBAL_MONKEYSEEROUNDS_LABEL:{sv:"Monkey See-rundor",en:"Monkey See rounds"},SETTINGS_GLOBAL_TRIESBEFOREGUARDIANANGEL_LABEL:{sv:"F\u00f6rs\u00f6k innan skydds\u00e4ngel",en:"Tries before guardian angel"},SETTINGS_MINIGAMES_LABEL:{sv:"Minispel",en:"Mini-games"},SETTINGS_MINIGAMES_FISHINGGAME_LABEL:{sv:"Fiskespel",en:"Fishing Game"},
SETTINGS_MINIGAMES_FISHINGGAME_TARGETNUMBER_LABEL:{sv:"M\u00e5lnummer",en:"Target number"},SETTINGS_MINIGAMES_FISHINGGAME_NUMBERCORRECT_LABEL:{sv:"Antal korrekta fiskar",en:"Number of correct fish"},SETTINGS_MINIGAMES_FISHINGGAME_NUMBEROFFISH_LABEL:{sv:"Antal fiskar totalt",en:"Number of fish totally"},SETTINGS_MINIGAMES_FISHINGGAME_MAXNUMBER_LABEL:{sv:"H\u00f6gsta m\u00f6jliga nummer",en:"Maximum number on fish"},SETTINGS_MINIGAMES_LADDER_LABEL:{sv:"Stegen",en:"The Ladder"},SETTINGS_MINIGAMES_LADDER_TARGETNUMBER_LABEL:{sv:"M\u00e5lnummer",
en:"Target number"}};return{get:function(a,b){if(c[a]===j)return p;for(var d=c[a][K.get("global","language")],g=1;g<arguments.length;g++)d=d.replace("%"+g,arguments[g]);return d}}}();Object.size=function(c){var a=0,b;for(b in c)c.hasOwnProperty(b)&&a++;return a};
var z=new function(){function c(a,b,c,g){var f=console;c===j?c="":"string"!==typeof c&&(c="");if("evm"!=c&&"sound"!=c){for(var c=c.substr(0,8),c=c.toUpperCase(),e=8-c.length,i=0;i<e;i++)c=" "+c;g.call(f,a+" "+c+" "+b)}}console.log("Creating Log");this.debug=function(a,b){c("DEBUG  ",a,b,console.debug)};this.uc=function(a){c("NOTIFY ",a,"sound",console.info)};this.error=function(a,b){c("ERROR  ",a,b,console.error)}};Array.prototype.remove=function(c){for(var a=0;a<this.length;a++)this[a]===c&&this.splice(a)};
var W=new function(){function c(a,b,c,g,f){var e=0,i=0;this.next=function(){var l=a+e*c,o=b+i*g;e=(e+1)%f;0==e&&i++;return{x:l,y:o}}}this.H=function(a){var b=arguments;return function(a){var c,f=[],e=p,i=k;for(c=0;c<b.length;c+=1)f.push(b[c]);e=function(b){i&&(b=a,i=r);var c=f.shift();c!=j&&c(e,b)};e()}};this.I=function(a,b){return Math.floor(Math.random()*(b-a+1))+a};this.qc=function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return k;return r};this.M=function(a,b,d,g,f){return new c(a,b,d,g,f)}};
Kinetic.Uc=function(c){var a=new Kinetic.Group({x:c.x,y:c.y,width:c.width,height:c.height}),b=new Kinetic.Rect({x:0,y:0,width:c.width,height:c.height,fill:"#ccc",strokeWidth:1,stroke:"white"}),d=new Kinetic.Text({text:c.text,fontFamily:"Arial",textFill:"black",fontSize:c.fontSize,x:c.width/2,y:c.height/2,verticalAlign:"middle",align:"center"});a.add(b);a.add(d);a.on("mousedown touchstart",c.callback);return a};
function fc(){var c=this;this.fc=function(a,b){var d=new Kinetic.Group({x:a,y:b}),g=new Kinetic.Image({image:c.S(),offset:{x:0,y:0},width:c.S().width,height:c.S().height}),f=new Kinetic.Image({image:c.O(),x:-12,y:-11});d.add(g);d.add(f);return d};this.ic=function(a){var a=new Kinetic.Group({x:a,y:12}),b=new Kinetic.Image({image:c.head(),width:c.head().width,height:c.head().height}),d=new Kinetic.Image({image:c.O(),x:-12,y:-11});a.add(b);a.add(d);return a}}
function Oa(){fc.call(this);fc.call(this);this.head=function(){return X.ua};this.S=function(){return X.va};this.O=function(){return X.ta}}function Pa(){fc.call(this);this.head=function(){return X.ua};this.S=function(){return X.va};this.O=function(){return X.ta}}
function ab(c){function a(a,b,d){var l=new Kinetic.Group({x:b,y:d}),b=new Kinetic.Rect({width:250,height:250,fill:{start:{x:125,y:125,radius:0},end:{x:125,y:125,radius:187.5},colorStops:[0,"#00FF7F",1,"#556B2F"]},shadow:{color:"black",blur:15,offset:[15,15],alpha:0.5},alpha:0.6,cornerRadius:10,strokeWidth:4,stroke:"white",offset:{x:125,y:125}});l.add(b);l.r=b;l.Lb=a;a=new a.view;a=new Kinetic.Image({image:a.head(),offset:{x:a.head().width/2,y:a.head().height/2}});l.add(a);l.on("mousedown touchstart",
function(){G.play(kb);l.r.setFill("white");l.moveToTop();g.Wb(l,function(){c.Zb(l.Lb)});g.$b()});return l}Z.call(this,"AgentChooserView");var b=this,d=p,g=function(){var a=[];this.add=function(b){a.push(b);d.add(b)};this.$b=function(){for(var b=0;b<a.length;b++)a[b].attrs.listening=r};this.Wb=function(c,d){for(var g=0;g<a.length;g++)a[g]===c?(b.c(a[g].attrs).wait(1E3).to({x:b.d.getWidth()/2,y:b.d.getHeight()/2},1E3),b.c(a[g].attrs.scale).wait(1E3).to({x:1.5,y:1.5},1E3).call(function(){G.play(nb)}).wait(5E3).call(d)):
b.c(a[g].attrs).to({alpha:0},1E3)};return this}();b.q=function(){d=new Kinetic.Layer;b.d.add(d);var f=new Kinetic.Image({image:X.zb});d.add(f);for(var f=W.M(363,230,310,310,2),e=c.dc(),i=0;i<e.length;i++){var l=f.next();g.add(new a(e[i],l.x,l.y))}G.play(mb)};b.i(function(){b.d.remove(d)});b.on(L,function(){d.draw()})}
function Ra(){Z.call(this,"GardenView");var c=this,a,b,d,g,f,e;c.s(function(){a=new Kinetic.Image({image:X.yb});b=new Kinetic.Image({image:X.xb});g=new Kinetic.Group({x:300,y:300,visible:r});f=new Kinetic.Image({image:X.l,offset:{x:X.l.width/2,y:X.l.height/2}});e=new Kinetic.Polygon({points:[{x:40,y:0},{x:60,y:0},{x:80,y:40},{x:41,y:63},{x:15,y:17}],offset:{x:X.l.width/2,y:X.l.height/2},fill:"blue"});d=new Kinetic.Layer;c.getStage().add(d);d.add(a);d.add(g);g.add(e);g.add(f)});c.i(function(){c.getStage().remove(d)});
c.on(L,function(){d.draw()});c.on("Game.demonstrateGarden",function(e){G.play(Bb);b.setAlpha(0);d.add(a);d.add(b);setTimeout(function(){G.play(Cb);c.c(a.attrs).to({alpha:0},2E3);c.c(b.attrs).to({alpha:1},2E3).wait(3E3).call(e.callback)},3E3)});c.on("Game.waterGarden",function(a){var b=e.attrs.points,d=(b[0].y-b[4].y)/(b[0].x-b[4].x),n=(b[2].y-b[1].y)/(b[2].x-b[1].x),m=b[0].y+17,q=b[0].y-d*b[0].x,w=b[2].y-n*b[2].x;g.show();setTimeout(function(){c.c(f.attrs).to({rotation:Math.PI/3});setTimeout(function(){e.transitionTo({points:{"0":{x:(m-
q)/d,y:m},1:{x:(m-w)/n,y:m}},duration:3,callback:function(){var c=(b[3].y-b[4].y)/(b[3].x-b[4].x),d=b[3].y-c*b[3].x;m+=b[3].y-b[2].y;e.transitionTo({points:{"0":{x:(m-d)/c,y:m},1:{x:(m-w)/n,y:m}},duration:3,callback:function(){m+=b[3].y-b[2].y;e.transitionTo({points:{"0":{x:(m-d)/c,y:m},1:{x:(m-d)/c,y:m}},duration:2,callback:function(){setTimeout(function(){a.callback()},3E3)}})}})}})},1E3)},1E3)})}
function Qa(c){Z.call(this,"IntroductionView");var a=this,b,d;a.s(function(){b=a.getStage();d=new Kinetic.Layer;b.add(d);a.setTimeout(function(){G.play(wb)},2E3);a.setTimeout(function(){G.play(xb)},2E3);a.setTimeout(function(){G.play(yb)},7E3);a.setTimeout(function(){G.play(zb)},7E3);a.setTimeout(function(){G.play(Ab)},12E3);a.setTimeout(function(){c()},14E3)});a.i(function(){b.remove(d)});a.on(L,function(){d.draw()})}
function Ta(){Z.call(this,"MinigameHandlerView");var c=this.d.F;(function(a){var b=new Kinetic.Text({text:"Backend Score (current minigame):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:a.d.getWidth()-700,y:35}),d=r,g=r;a.on("backendScoreGameUpdateMiniGame",function(a){b.setText("Backend Score (current minigame): "+a.Bc)});a.on("miniGameStarted",function(){g=d=k;c.add(b)});a.on(M,function(){g&&!d?(c.add(b),d=k,console.info("Turning off backend score display")):
g&&d&&(c.remove(b),d=r,console.info("Turning on backend score display"))});a.i(function(){d=g=r;c.remove(b)})})(this);(function(a){var b=new Kinetic.Text({text:"Learning track (current game):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:a.d.getWidth()-700,y:55}),d=r,g=r;a.on("miniGameStarted",function(){c.add(b);d=g=k});a.on("learningTrackUpdate",function(a){b.setText("Learning track (current game): "+a.sc.name())});a.on(M,function(){g&&!d?(c.add(b),
d=k):g&&d&&(c.remove(b),d=r)});a.i(function(){d=g=r;c.remove(b)})})(this);(function(a){var b,d,g,f,e=10,i=20;a.s(function(){b=new Kinetic.Image({image:X.l,x:c.getStage().getWidth()-X.l.width-20,y:20,width:X.l.width,height:X.l.height,visible:r});d=new Kinetic.Image({image:X.D,offset:{x:X.D.width/2,y:0},width:X.D.width,height:X.D.height,visible:r,rotation:Math.PI});g=new Kinetic.Image({image:X.W,x:b.getX(),y:b.getY(),width:X.W.width,height:X.W.height,visible:r});f=new Kinetic.Rect({fill:"#379de4",x:b.getX()+
20,y:b.getY()+b.getHeight()-4,width:54,height:0});c.add(g);c.add(f);c.add(d);c.add(b)});a.i(function(){c.remove(d);c.remove(b);c.remove(g);c.remove(f)});a.on("miniGameStarted",function(){b.show();var c=a.b.mc();0<c&&g.show();f.setHeight(f.getHeight()-6.9*c)});a.on("resetPitcherLevel",function(){g.hide();f.setHeight(0)});a.on(ta,function(a){e=a.x;i=a.y});a.on("setPitcherLevel",function(c){var o=b.getX()+b.getWidth()/2,n=b.getY()+b.getHeight()-d.getHeight(),m=1E3*(Math.sqrt(Math.pow(e-o,2)+Math.pow(i-
n,2))/200);d.setX(e);d.setY(i);d.setAlpha(1);d.show();G.play(rb);G.play(sb);a.setTimeout(function(){G.play(tb)},2E3);a.c(d.attrs).to({x:o-50,y:n},1.2*m).to({rotation:4*Math.PI/3,x:o-50,y:n-30},300).to({rotation:5*Math.PI/3,x:o-25,y:n-25},300).to({rotation:6*Math.PI/3,x:o,y:n},300).call(function(){G.play(vb);g.show();a.c(f.attrs).to({height:f.getHeight()-6.9},1E3);a.c(d.attrs).to({alpha:0},1E3).wait(1E3).call(function(){d.hide();d.setRotation(Math.PI);c.callback!=j&&c.callback()})})})})(this)}
function $a(){Z.call(this,"MonkeyWorldView");var c=this.d,a=c.F;this.m=function(){this.o()};(function(b){var c=[];b.on("Game.showMiniGameChooser",function(b){var f=b.callback,e=b.bc,i=W.M(200,200,300,100,2),l;for(l in e)(function(){for(var b=0;b<e[l].Jc();b++)(function(){console.log(e[l].ra[b]);var g=e[l].ra[b],m=i.next(),m=new Kinetic.Group(m),q=new Kinetic.Rect({width:280,height:100,stroke:"black",strokeWidth:4}),w=new Kinetic.Text({text:g.title,fontSize:20,fontFamily:"sans-serif",textFill:"black",
align:"center",verticalAlign:"center",width:280,height:100,y:40});w.setAlign("center");m.add(q);m.add(w);m.on("mousedown touchstart",function(){q.setFill("yellow");f(g)});c.push(m);a.add(m)})()})()});b.on("Game.hideMiniGameChooser",function(){for(var b=0;b<c.length;b++)a.remove(c[b]);c=[]})})(this);(function(b){var d=new Kinetic.Rect({x:c.getWidth()/2,y:c.getHeight()/2,width:320,height:50,cornerRadius:10,offset:{x:160,y:25},fill:"#333",alpha:0}),g=new Kinetic.Rect({x:c.getWidth()/2,y:c.getHeight()/
2,width:0,height:30,offset:{x:150,y:15},fill:"#FFCC00"}),f=new Kinetic.Text({fontFamily:"Arial",fontSize:10,textFill:"black",fontStyle:"bold",Fe:"black",text:"Monkey World Demo",align:"center",width:c.getWidth(),height:50,y:c.getHeight()/2-50,x:0});b.on("Game.showLoadingScreen",function(b){a.add(d);a.add(g);a.add(f);d.transitionTo({alpha:1,duration:b.time/1E3})});b.on("Game.loadingSounds",function(){f.setText(S.get("INIT_LOADING_SOUNDS"))});b.on("Game.loadingImages",function(){f.setText(S.get("INIT_LOADING_IMAGES"))});
b.on("Game.loadingDone",function(){a.remove(f);a.remove(d);a.remove(g)});b.on("Game.updateSoundLoading",function(a){g.setWidth(300*a.progress)});b.on("Game.updateImageLoading",function(a){g.setWidth(300*a.progress)})})(this)}
Kinetic.z.Ab=function(c,a){function b(b){a.c(f.attrs).to({image:X.xa}).wait(l).to({image:X.ya}).wait(l).to({image:X.za}).wait(l).to({image:X.Aa}).call(b)}function d(b){a.c(n.attrs).to({image:X.Ea}).wait(o).to({image:X.Da}).wait(o).to({image:X.Ca}).wait(o).to({image:X.C}).wait(o).to({visible:r}).call(b)}var g=new Kinetic.Group(c),f,e,i,l=200,o=200,n;f=new Kinetic.Image({image:X.u,width:X.u.width,height:X.u.height});n=new Kinetic.Image({image:X.C,width:X.C.width,height:X.C.height,visible:r,x:109,y:81,
offset:{x:279,y:281}});g.add(n);g.add(f);this.T=function(){f.attrs.image=X.Ba;e=a.setInterval(function(){f.attrs.image=X.Ib;i=a.setTimeout(function(){f.attrs.image=X.Ba},140)},280)};this.w=function(){a.clearInterval(e);a.clearTimeout(i);f.attrs.image=X.u};g.T=this.T;g.w=this.w;this.qa=function(c){b(function(){n.show();a.c(n.attrs).to({image:X.Ca}).wait(o).to({image:X.Da}).wait(o).to({image:X.Ea}).wait(o).to({image:X.Jb}).call(c)})};this.pa=function(b){d(function(){a.c(f.attrs).to({image:X.Aa}).wait(l).to({image:X.za}).wait(l).to({image:X.ya}).wait(l).to({image:X.xa}).wait(l).to({image:X.u}).call(b)})};
g.pa=this.pa;g.qa=this.qa;return g};
Kinetic.z.Fb=function(c){var a,b;a=new Kinetic.Group(c);switch(c.type){case 1:b=X.Cb;break;case 2:b=X.Db;break;case 3:b=X.Eb;break;default:h("NoSuchParcelTypeException")}c=new Kinetic.Image({image:b,width:b.width,height:b.height,offset:{x:b.width/2,y:b.height/2},shadow:{color:"black",blur:10,offset:[3,3],alpha:0.5}});a.add(c);a.Fc=function(b){var c=a.getX(),f=a.getY();b.c(a.attrs).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+
5},100).to({x:c-5},100).to({x:c},100);b.c(a.attrs).to({y:f-5},100).to({y:f+5},100).to({y:f-5},100).to({y:f+5},100).to({y:f-5},100).to({y:f+5},100).to({y:f-5},100).to({y:f+5},100).to({y:f-5},100).to({y:f},100)};a.wc=function(b){a.on("mousedown touchstart",b)};a.vc=function(){a.off("mousedown touchstart")};a.open=s();return a};
function gc(c){Z.call(this,c);var a=this.d.F;(function(b){var c=new Kinetic.Text({text:"Backend Score (current mode):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:b.d.getWidth()-700,y:15});a.add(c);var g=k,f=g;b.on(la,function(a){c.setText("Backend Score (current mode): "+a.Ma)});b.on(M,function(){f&&!g?(a.add(c),g=k):f&&g&&(a.remove(c),g=r)});b.i(function(){a.remove(c);g=f=r})})(this);(function(b){var c=b.b.aa().O(),g=(new b.b.aa).ic(b.getStage().getWidth()-
c.width-30);g.setScale(0.5);b.s(function(){b.b.fa()&&a.add(g)});b.i(function(){a.remove(g)})})(this)}
function hc(c,a){gc.call(this,c);this.ib(c);z.debug("Creating LadderView","object");var b=this,d=p,g=p,f=p,e=p,i={x:800,y:650};this.Ja=function(a){d=new Kinetic.Image({image:X.Hb,x:750,y:600,offset:{x:64,y:64},alpha:0});g=new Kinetic.Image({image:X.Gb,x:900,y:600,offset:{x:64,y:64},alpha:0});a.add(d);a.add(g)};this.Ia=function(a,c,d){b.b.fa()||(f=(new b.b.aa).fc(a,c),f.setScale(0.8),d.add(f),b.b.e()&&(e=new Kinetic.Line({points:[660,570,i.x,i.y],stroke:"brown",strokeWidth:2,lineCap:"round"}),d.add(e)))};
b.on("Ladder.interrupt",function(){b.b.e()&&(b.P(e.attrs.points[1]),b.c(e.attrs.points[1]).to(i,1E3).call(function(){G.play(ub)}));b.N()});b.on("Ladder.introduceAgent",function(a){G.play(Db);b.setTimeout(function(){G.play(Eb);b.setTimeout(function(){a()},2E3)},2E3)});b.on(wa,function(c){d.on("mousedown touchstart",function(){b.c(d.attrs).to({rotation:8*Math.PI},1200).to({rotation:0});G.play(ib);a.rc()});g.on("mousedown touchstart",function(){b.c(g.attrs).to({rotation:8*Math.PI},1200).to({rotation:0});
G.play(jb)});c()});b.on(xa,function(){d.off("mousedown touchstart");g.off("mousedown touchstart")});b.on("Ladder.startAgent",function(a){G.play(Fb);b.setTimeout(function(){a();b.c(d.attrs).to({alpha:1},1E3);b.c(g.attrs).to({alpha:1},1E3)},2E3)});b.on(Ca,function(a){G.play(hb);b.setTimeout(a,1500)});b.on(Fa,function(a){b.Ta(a)});b.on(Ba,function(){b.Pa()});b.on("Ladder.betterBecauseBigger",function(){G.play(b.Na)});b.on("Ladder.betterBecauseSmaller",function(){G.play(b.Oa)});b.on("Ladder.hmm",function(){G.play(qb)});
b.on("Ladder.agentSuggestSolution",function(){b.setTimeout(function(){G.play(b.na);b.setTimeout(function(){G.play(b.na)},2E3)},2E3)});b.on("Ladder.tooLow",function(){G.play(b.lb);setTimeout(function(){G.play(b.mb)},2E3)});b.on("Ladder.tooHigh",function(){G.play(b.kb);setTimeout(function(){G.play(b.nb)},2E3)});b.on("Ladder.agentTooLow",function(){G.play(b.La)});b.on("Ladder.agentTooHigh",function(){G.play(b.Ka)});b.on("Ladder.picked",function(c,d){if(b.b.e()&&!a.k()&&!a.g()){var f=b.Sa(d.ha);G.play(pb);
b.c(e.attrs.points[1]).wait(1500).to(f,3E3).wait(3E3).call(function(){b.p(d.ha,c)}).wait(1E3).to(i,1E3)}else b.p(d.ha,c)})}
function eb(c){var a=this;hc.call(this,"MtView",c);z.debug("Constructing MountainView",this.h);a.lb=Tb;a.kb=Sb;a.mb=Vb;a.nb=Ub;a.na=Wb;a.Ic=Xb;a.La=$b;a.Ka=ac;a.Na=Yb;a.Oa=Zb;a.Vb=bc;var b=r,d=p,g=r,f=new Kinetic.Layer,e=new Kinetic.Layer,i=[],l=new Kinetic.Group({x:400,y:600}),o=new Kinetic.Rect({width:50,height:50,fill:"blue",stroke:"black",strokeWidth:4,offset:{x:25,y:50}});Kinetic.qb=function(a,b){var c=new Kinetic.Group({x:a,y:b}),d=new Kinetic.Circle({fill:"red",stroke:"black",strokeWidth:4,
radius:20}),e=new Kinetic.Line({stroke:"black",strokeWidth:4,points:[0,20,0,65]});c.add(e);c.add(d);return c};a.s(function(){z.debug("Setting up MountainView","mt-view");a.d.add(e);a.d.add(f);var d=new Kinetic.Polygon({points:[50,600,350,600,150,100],fill:"gray",stroke:"black",strokeWidth:4});l.add(new Kinetic.Polygon({points:[0,0,100,0,110,-50,-10,-50],fill:"#993300",stroke:"black",strokeWidth:4}));for(var m=new W.M(730,180,140,140,2),q=0;6>q;q++)(function(d){var e=m.next(),e=new Kinetic.Group({x:e.x,
y:e.y}),l=new Kinetic.Group({x:40,y:40}),n=new Kinetic.Rect({width:140,height:140,fill:"yellow",strokeWidth:4,stroke:"black"});e.add(n);i.push(e);for(var q=0,o=0;o<=d;o++)3===o&&q++,l.add(new Kinetic.qb(30*o-81*q,30*q));e.add(l);e.r=n;e.Fa=l;e.on("mousedown touchstart",function(){b&&a.b.Za()?c.p(d+1):a.b.Ya()&&!g&&(g=k,G.play(lb),setTimeout(function(){G.play(ob);setTimeout(function(){g=r},2E3)},2E3))});f.add(e)})(q);e.add(d);d=c.ba();for(q=0;q<d.length;q++){var w=new Kinetic.Line({points:[280-24*
q,430-60*q,280-24*q+100,430-60*q],stroke:"black",strokeWidth:4});e.add(w)}o.hide();f.add(o);f.add(l);a.on("frame",function(){f.draw()});a.Ja(f);a.Ia(a.getStage().getWidth()-500,a.getStage().getHeight()-50-252,f);e.draw()});a.N=function(){d!=p&&d();a.P(l.attrs);a.c(l.attrs).to({x:400,y:600})};a.on(ua,function(a){var b=c.L()-1;o.setX(280-24*b);o.setY(430-60*b);o.show();a()});a.on(Da,function(){b=r});a.on(P,function(){b=k});a.on(Q,s());a.on(Ea,s());this.Sa=function(a){a=i[a-1];return{x:a.getX()+a.r.getWidth()/
2,y:a.getY()+a.r.getHeight()/2}};this.p=function(c,e){b=r;var f=i[c-1].Fa,g=i[c-1];g.r.setFill("red");var o=g.Fa.getX(),E=f.getY();d=function(){a.P(f.attrs);f.setX(o);f.setY(E);f.moveTo(g);g.r.setFill("yellow")};a.c(f.attrs).to({x:-Math.abs(400-g.getX())+20,y:600-g.getY()+-110},4E3).call(function(){f.moveTo(l);f.setX(20);f.setY(-110);f.moveDown();e()})};a.on(va,function(b){var d=c.Qa();a.c(l.attrs).to({x:280-24*(d-1)+100,y:430-60*(d-1)},2E3).call(b)});a.on(za,function(b){G.play(cc);a.setTimeout(function(){G.play(dc)},
2E3);a.c(o.attrs).to({x:l.getX()+50,y:l.getY()+-25},1E3).call(function(){a.c(l.attrs).to({x:400,y:600},3E3);a.c(o.attrs).to({x:450,y:575},3E3).call(function(){a.c(o.attrs).to({x:550,y:600},2E3).call(b)})})});a.on(Aa,function(){a.b.e()||c.ia()});a.Pa=s();a.Ta=function(a){a()};a.on(N,function(b){function c(){d!=p&&d();b()}600!=l.getY()?a.c(l.attrs).to({x:400,y:600},2E3).call(c):c()});this.i(function(){z.debug("Tearing down MountainView",this.h);a.d.remove(e);a.d.remove(f)})}
function ic(c){c.x===j&&(c.x=0);c.y===j&&(c.y=0);c.min===j&&(c.min=1);c.max===j&&(c.max=6);c.step===j&&(c.step=1);c.width===j&&(c.width=2);c.ka===j&&(c.ka=s());c.G===j&&(c.G=10);c.Z===j&&(c.Z={x:0,y:0});c.Q===j&&(c.Q=1);for(var a=[],b=r,d=r,g={color:"black",blur:10,offset:[3,3],alpha:0.5},f=new W.M(c.Z.x,c.Z.y,c.$+c.G,c.Y+c.G,c.width),e=new Kinetic.Group({x:c.x,y:c.y}),i=c.min;i<=c.max;i+=c.step)(function(i){function o(a,f){f===j&&(f=r);if(!d)if(!f&&b)c.ac(i);else if(f||!b){e.da();c.ka(i);m.attrs.image=
c.Xb;m.attrs.shadow=p}}var n=f.next(),n=new Kinetic.Group({x:n.x,y:n.y}),m=new Kinetic.Image({image:c.button,width:c.$,height:c.Y,shadow:g}),q=new Kinetic.Image({image:c.ma[i],scale:{x:c.Q,y:c.Q},offset:{x:c.ma[i].width/2,y:c.ma[i].height/2},x:c.$/2,y:c.Y/2});n.on("mousedown touchstart",function(){o(0,r)});n.add(m);n.add(q);m.push=o;e.add(n);a[i]=m;a[i].Ua=n})(i);e.bb=function(){for(var b=c.min;b<=c.max;b=b+c.step){a[b].attrs.image=c.button;console.log("shadow",g);a[b].setShadow(g)}};e.da=function(){b=
k};e.Lc=function(){b=r};e.pc=function(){d=k};e.Qb=function(){d=r};e.gc=function(b){return{x:e.getX()+a[b].Ua.getX()+a[b].getWidth()/2,y:e.getY()+a[b].Ua.getY()+a[b].getHeight()/2}};e.push=function(b){a[b].push(p,k)};return e}
function db(c){hc.call(this,"TreeView",c);var a=this,b=1/2.083168317,d,g,f,e,i,l=[],o,n,m,q,w,u=p,E,I,A=0,F={},J,V=a.getStage().getHeight()-160,ea=a.getStage().getHeight()-120,x={1:{x:100,y:40,rotation:-Math.PI/9},2:{x:100,y:100,rotation:Math.PI/11},3:{x:200,y:40,rotation:-Math.PI/12},4:{x:200,y:100,rotation:Math.PI/9}};a.lb=Hb;a.kb=Gb;a.mb=Jb;a.nb=Ib;a.na=Kb;a.Ic=Lb;a.La=Ob;a.Ka=Pb;a.Na=Mb;a.Oa=Nb;a.Vb=Qb;g=new ic({x:550,y:180,button:X.V,Xb:X.pb,$:X.V.width,Y:X.V.height,G:15,ac:function(){G.play(lb);
a.setTimeout(function(){G.play(ob);a.setTimeout(s(),2E3)},2E3)},ka:function(b){a.b.Za()&&c.p(b)},ma:{1:X.rb,2:X.sb,3:X.tb,4:X.ub,5:X.vb,6:X.wb},Q:0.75});g.da();n=new Kinetic.Layer;m=new Kinetic.Layer;a.getStage().add(n);a.getStage().add(m);f=new Kinetic.z.Ab({x:240,y:580,scale:b},a);i=function(){e=a.setInterval(function(){l[c.K()-1].Fc(a)},4E3)};w=function(){a.clearInterval(e)};I=function(){u.wc(c.ia)};a.on(sa,function(){a.a(ta,{x:l[c.K()-1].getX(),y:l[c.K()-1].getY()})});a.on(Da,function(){g.pc()});
a.on(P,function(){g.Qb()});a.on(Q,function(){g.Lc()});a.on(Ea,function(){g.da()});E=function(b){console.log(l);u=l[c.K()-1];a.c(u.attrs).wait(2E3).to({x:100,y:150,rotation:2*Math.PI},1E3).to({rotation:0}).to({y:F[c.L()].getY()+25,rotation:2*Math.PI*(7-c.L())},1E3).to({rotation:0}).call(b)};a.Pa=function(){u.vc();w();u.open();g.bb();n.draw()};a.Ta=function(b){var c=new Kinetic.Image({x:u.getX(),y:u.getY(),image:X.ob,width:128,height:128,offset:{x:64,y:64},scale:{x:0.1,y:0.1}});m.add(c);a.c(c.attrs.scale).to({x:1,
y:1},500).call(function(){a.c(c.attrs).to({y:200},2E3).call(b)})};a.on(ua,function(a){A+=1;E(a)});a.on(va,function(b){q=c.Qa();a.c(f.attrs).to({y:480},2E3).to({rotation:-Math.PI/8,x:215},1E3).call(function(){console.log(F[2].getY());1<q?a.c(f.attrs).to({rotation:0,y:430},1E3).call(function(){2<q?(f.T(),a.c(f.attrs).to({y:F[q].getY()},500*q).call(function(){f.w();b()})):(f.w(),b())}):b()})});a.on(N,function(b){function c(){a.c(f.attrs).to({rotation:0,x:240,y:580},2E3).call(function(){g.bb();b()})}
function d(b){a.c(f.attrs).to({rotation:-Math.PI/16,x:240,y:510},1E3).to({rotation:0,y:530},1E3).call(b)}function e(b){f.T();a.c(f.attrs).to({y:430},500*q).call(f.w).call(b)}2<q?e(function(){d(c)}):1<q?d(c):c()});a.on("Ladder.getTarget",function(b){f.qa(function(){function c(){d+=1;2===d&&b()}var d=0;a.c(u.attrs).to({x:u.getX()+30,y:u.getY()-30}).wait(200).call(function(){G.play(Rb);f.pa(c)}).to({x:650+75*A,y:ea,rotation:3*Math.PI},2E3).to({rotation:0}).call(c).call(function(){a.b.e()||(I(),i())})})});
a.on(L,function(){m.draw()});a.i(function(){a.getStage().remove(n);a.getStage().remove(m)});a.N=function(){a.P(f.attrs)};o=new Kinetic.Image({image:X.A,x:0,y:a.getStage().getHeight()-X.A.height,width:X.A.width,height:X.A.height});n.add(o);n.add(new Kinetic.Image({image:X.Kb,x:144,y:167}));a.Ja(m);a.on("Ladder.helpAgent",s());for(d=0;d<c.ba().length;d+=1)o=c.ba()[d],J=new Kinetic.Group({x:120,y:V-70*d}),F[o]=J;m.add(f);m.add(new Kinetic.Image({image:X.B,width:X.B.width,height:X.B.height,x:184,y:a.getStage().getHeight()-
X.B.height}));this.p=function(b,c){G.play(kb);a.b.Ya()&&g.push(b);c()};this.Sa=function(a){return g.gc(a)};n.add(new Kinetic.Image({x:370,y:-100,image:X.Bb}));m.add(g);a.Ia(a.getStage().getWidth()-248,a.getStage().getHeight()-100-252,m);(function(){var a;for(d=0;3>d;d+=1)a=new Kinetic.z.Fb({x:x[d+1].x,y:x[d+1].y,rotation:x[d+1].rotation,type:d%3+1,scale:b}),m.add(a),l.push(a)})(this);n.draw()}
function Z(c){Ka.call(this,c);var a=new function(){var a=[];this.c=function(c){W.qc(a,c)||a.push(c);return Tween.get(c)};this.removeTweens=function(a){Tween.removeTweens(a)};this.oa=function(){for(var c=0;c<a.length;c++)Tween.removeTweens(a[c])}};this.i(function(){z.debug("Tearing down","ViewModule");a.oa()});this.c=function(b){return a.c(b)};this.P=function(b){a.removeTweens(b)};this.getStage=t("d")};