function h(c){throw c;}var j=void 0,k=!0,p=null,r=!1;function s(){return function(){}}function t(c){return function(){return this[c]}}function v(c){return function(){return c}}Kinetic.A={};var da=p;window.egame=p;window.onload=function(){da=new ea;window.egame=da};WebFontConfig={google:{families:["Nunito::latin","Doppio+One::latin","Nobile:400,700:latin","Galindo::latin"]}};var y=document.createElement("script");y.src=("https:"==document.location.protocol?"https":"http")+"://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js";
y.type="text/javascript";y.async="true";var fa=document.getElementsByTagName("script")[0];fa.parentNode.insertBefore(y,fa);
function ea(){function c(){i.a("Game.loadingSounds");var a=p,d=p;z.debug("Loading sounds...","game");var c=new PreloadJS(r);c.onComplete=function(){clearInterval(a);d=setInterval(function(){i.a("Game.updateImageLoading",{progress:ga.kc()})},50);z.debug("Sounds loaded.","game");i.a("Game.loadingImages");ga.Ra(function(){clearInterval(d);i.a("Game.updateImageLoading",{progress:1});z.debug("Images loaded.","game");setTimeout(function(){i.a("Game.loadingDone");e.start()},D?0:1E3)})};c.installPlugin(SoundJS);
a=setInterval(function(){i.a("Game.updateSoundLoading",{progress:c.progress})},50);F.Fc(b);i.on(ha,function(){F.Nc()},"game");c.loadManifest(F.lc())}var a=new ia;K.Ec();this.applySettings=function(){a.apply();$.cookie("monkeyWorldSettings",JSON.stringify(K.fa()))};this.hideSettings=function(){a.hide()};this.showSettings=function(){a.show()};var b=new Kinetic.Stage({container:"container",width:1010,height:660});b.Ae=b.getWidth()/1024;var d=new Kinetic.Layer,f=new Kinetic.Layer,g=new Kinetic.Layer;
b.add(d);b.add(f);b.add(g);b.Lb=d;b.G=f;b.Mb=g;b.Nb=f;b.Fe=t("G");b.Ee=t("Lb");b.Ge=t("Mb");b.$=r;b.Be=0;b.ze=0;b.Va=function(){b.$=k};var e=new ja(b),i=e.j,l=function(){var a=0,b=new Kinetic.Text({text:"",fontFamily:"Arial",textFill:"black",textStroke:"white",textStrokeWidth:1,fontSize:18,x:0,y:0}),d=k;i.on(qa,function(){d?(console.info("Turning off FPS display"),f.remove(b),d=r):(console.info("Turning on FPS display"),f.add(b),d=k)},"game");f.add(b);return{Hc:function(d){if(0==a||10<d.time-a)b.setText("FPS: "+
Math.round(1E3/d.timeDiff)),a=d.time}}}();b.onFrame(function(a){D&&l.Hc(a);i.a("frame",{frame:a});f.draw();b.$&&(g.draw(),b.$=r);Tween.tick(a.timeDiff,r)});b.start();i.on("Game.miniGameListenersInitiated Game.viewInitiated",function(){f.moveToTop();g.moveToTop()},"game");d=D?0:2E3;i.a("Game.showLoadingScreen",{time:d});setTimeout(function(){c()},d);this.Ya=function(){e.Ya()}}
var L="frame",ha="TRIGGER_SUBTITLES",M="TRIGGER_SCORE",qa="TRIGGER_FPS",ra="backendScoreUpdateMode",sa="setPitcherLevelBefore",ta="setPitcherLevelSetDropOrigin",ua="MG_LADDER_PLACE_TARGET",va="MG_LADDER_HELPER_APPROACH_TARGET",wa="MG_LADDER_ALLOW_INTERRUPT",xa="MG_LADDER_FORBID_INTERRUPT",ya="Ladder.readyToPick",N="Ladder.resetScene",za="Ladder.getTarget",Aa="Ladder.hasTarget",Ba="Ladder.confirmTarget",Ca="Ladder.cheer",Da="MG_LADDER_IGNORE_INPUT",P="MG_LADDER_ACKNOWLEDGE_INPUT",Ea="MG_LADDER_FORBID_GAMER_INPUT",
Q="MG_LADDER_ALLOW_GAMER_INPUT",Fa="MG_LADDER_GET_TREAT";
function Ga(){var c={},a=[],b=0;this.sa=v("GameEventManager");this.on=function(a,b,g){for(var a=a.split(" "),e=0;e<a.length;e++)a[e]in c||(c[a[e]]=[]),c[a[e]].push(b),b.v=g,z.debug((g===j?"unnamed":g)+" registerd "+a[e],"evm")};this.off=function(a,b){for(var g=0;g<c[a].length;g++)c[a][g].v===b&&c[a].splice(g,1);0==c[a].length&&delete c[a]};this.print=function(){console.log("-------EVENT MANAGER STATE-----------------");for(var a in c){console.log("key: "+a);for(var b=0;b<c[a].length;b++)console.log("   "+
c[a][b].v)}console.log("-------------------------------------------")};this.o=function(d){if(0<b)a.push(d);else{var f=0,g;for(g in c){for(var e=c[g].length,i=0;i<e;i++)c[g][i].v===d&&(c[g].splice(i,1),i--,e--,f++);0==c[g].length&&delete c[g]}z.debug("Forgot "+f+" event registred by "+d,"evm")}};this.a=function(d,f,g){b++;d=c[d];if(d!=j)for(var e=0;e<d.length;e++){var i=d[e];g!=j&&g&&z.debug("      "+d[e].v);i(f)}b--;if(0==b&&0<a.length){for(e=0;e<a.length;e++)this.o(a[e]);a=[]}};this.eb=function(d,
f,g,e){b++;g=c[g];if(g!=j)for(var i=0;i<g.length;i++){var l=g[i];z.debug("      "+g[i].v);l(d,e);f||d()}b--;if(0==b&&0<a.length){for(i=0;i<a.length;i++)this.o(a[i]);a=[]}};this.n=function(a,b,c){this.eb(b,k,a,c)};this.Ra=function(a,b,c){z.debug("Loading images...","view");var e=0,i=Object.size(a),l;for(l in a)b[l]=new Image,b[l].onload=function(){++e>=i&&c()},b[l].src="../res/img/"+a[l]}}var D=k;Kinetic.ta=s();Kinetic.ta.getWidth=s();
function T(c){this.h=c;var a=this;document.onkeypress=function(b){117===b.keyCode?a.a(ha):105===b.keyCode?a.a(M):111===b.keyCode?a.a(qa):115===b.keyCode?a.a("setPitcherLevel",{callback:s()}):console.info("Unhandles key: "+b.keyCode)};this.on=function(a,c,f){this.j.on(a,c,f===j?this.h:f)};this.off=function(a,c){this.j.off(a,c===j?this.h:c)};this.o=function(a){this.j.o(a===j?this.h:a)};this.a=function(a,c,f){f!=j&&f&&z.debug("Out: "+a,this.h);this.j.a(a,c,f)};this.n=function(a,c,f){z.debug("Out: "+
a,this.h);this.j.n(a,c,f)};this.$a=function(b,c,f){return function(g){z.debug("Out: "+c,this.h);a.j.eb(g,b,c,f)}};this.Za=function(b){return a.$a(r,b,j)};this.t=function(b,c){return a.$a(k,b,c)};this.sa=function(){console.log(this.j.sa())};this.cb=function(a){this.h=a}}T.prototype.j=new function(){this.sa=v("NoEventManager");this.on=s();this.a=s();this.off=s();this.o=s()};T.prototype.d=new Kinetic.ta;T.prototype.b=p;
function Ha(){var c=[];this.Wa=function(a){c.push(a)};this.K=function(a){var b=a-1;(0>b||b>=c.length)&&h("MonkeyWorld.NoSuchRoundException ("+a+")");return c[b]}}function Ia(){var c=r,a=[];this.na=function(){z.debug("Got mistake report","game");c=k};this.Sa=function(){return c};this.yc=function(b){a.push(b)};this.la=function(){a.splice(a.length-1)};this.bc=function(){return a}}
function Ja(){this.Wa=function(){h("MonkeyWorld.NoMiniGameResultException")};this.K=function(){h("MonkeyWorld.NoMiniGameResultException")}}
function Ka(c){T.call(this,c);var a=this,b=new function(){var a=[];this.setTimeout=function(b,c){var d=setTimeout(b,c);a.push(d);return d};this.setInterval=function(b,c){var d=setInterval(b,c);a.push(d);return d};this.clearTimeout=function(b){a.remove(b);clearTimeout(b)};this.clearInterval=function(b){a.remove(b);clearInterval(b)};this.qa=function(){for(var b=0;b<a.length;b++)clearTimeout(a[b]);delete a;a=[]}},d=[],f=[];this.i=function(a){d.push(a)};this.m=function(){d===p&&h({name:"MW.TearDownAlreadyCalledException",
message:"This module ("+c+") has already been teared down."});b.qa();a.o();for(var g=0;g<d.length;g++)d[g](),d[g]=p;d=p};this.s=function(a){f.push(a)};this.q=function(){f===p&&h({name:"MW.SetupAlreadyCalledException",message:"This module ("+c+") has already been setted up."});for(var a=0;a<f.length;a++)f[a](),f[a]=p;f=p};this.setTimeout=function(a,c){return b.setTimeout(a,c)};this.setInterval=function(a,c){return b.setInterval(a,c)};this.clearTimeout=function(a){b.clearTimeout(a)};this.clearInterval=
function(a){b.clearInterval(a)}}
var K=new function(){var c={global:{language:{f:"en"},monkeySeeRounds:{f:1},triesBeforeGuardianAngel:{f:3}},miniGames:{fishingGame:{targetNumber:{f:2},numberCorrect:{f:1},numberOfFish:{f:7},maxNumber:{f:9}},ladder:{targetNumber:{f:-1}}}};this.fa=function(){return c};this.get=function(a){for(var b=c,d=0;d<arguments.length;d++)b=b[arguments[d]];return b.f};this.set=function(a){for(var b=c,d=0;d<arguments.length-1;d++)b=b[arguments[d]];b.f=arguments[arguments.length-1]};this.Ec=function(){var a=JSON.parse($.cookie("monkeyWorldSettings"));
a!==p&&(c=a)};this.Dc=function(a,b){for(var d=a.split("-"),f=c,g=0;g<d.length;g++)f=f[d[g]];f.f=b}};
function ia(){function c(a,b){for(var d in a)if("object"===typeof a[d]&&a[d].f===j)c(a[d],b+"-"+d);else if(a[d].f!=j){var g=$("#"+b+"-"+d).val();K.Dc(b+"-"+d,g)}}function a(){$("#settings-panel").append('<div id="settings-panel-content">');g=$("#settings-panel-content");g.append("<h1>"+U.get("SETTINGS_LABEL")+"</h1>");g.append("<form>");var a=f.fa(),c;for(c in a)g.append(d(c,2,"")),g.append(b(a[c],2,c));g.append("<button type=\"button\" onclick=\"window['egame']['hideSettings']()\">"+U.get("SETTINGS_CANCEL")+
"</button>");g.append("<button type=\"button\" onclick=\"window['egame']['applySettings']();window['egame']['hideSettings']()\">"+U.get("SETTINGS_APPLY")+"</button>");g.append("</form>");g.append("</div>")}function b(a,c,g){var f;f="<ul>";for(var n in a)if("object"===typeof a[n]&&a[n].f===j)f+=d(n,c+1,g),f+=b(a[n],c+1,g+"-"+n);else{f+="<li>";f+=d(n,c+1,g);var m="",m=m+('<input type="text" id="'+(g+"-"+n)+'" value="'+a[n].f+'" />');f+=m+"</li>"}return f+"</ul>"}function d(a,b,c){var d="",a="SETTINGS_"+
((c===j?"":c+"_")+a).toUpperCase().replace("-","_")+"_LABEL",a=U.get(a);a!=p&&(d+="<h"+b+">"+a+"</h"+b+">");return d}var f=K,g=$("#settings-panel-content");this.apply=function(){var b=f.fa(),d;for(d in b)"object"===typeof b[d]&&c(b[d],d);g.remove();a()};this.show=function(){a();$("#settings-panel").show()};this.hide=function(){g.remove();$("#settings-panel").hide()}}function La(){}function Ma(){}
function Na(c){Ka.call(this,"AgentChooser");var a=[{ja:La,view:Oa},{ja:Ma,view:Pa},{ja:La,view:Oa},{ja:La,view:Oa}];this.cc=function(){return a};this.Yb=function(a){c(a)}}function V(c,a){this.hc=function(){return c};this.jc=function(){return a}}
function ja(c){function a(a){if(q&&!D){var c=m(Qa,function(){c.m();b(a)});c.q();u.a("Game.viewInitiated")}else b(a)}function b(a){if(q&&!D){var b=m(Ra);b.q();u.a("Game.viewInitiated");u.a("Game.demonstrateGarden",{callback:function(){b.m();a()}})}else a()}function d(a){function b(){O=0;u.a("resetPitcherLevel");c.m();u.a("Game.gardenWatered");a!=j&&a()}if(q){var c=m(Ra);c.q();u.a("Game.waterGarden",{callback:function(){b()}})}else b()}function f(){u.a("Game.stopMiniGame");q&&ka.m();B.stop();B.m();
delete B;R=0;B=G;u.a("miniGameDone")}function g(){la();B.q();q&&(ma=m(na,B),ma.q(),u.a("Game.miniGameListenersInitiated"));if("Monkey Do"===x){var a=aa.K(ba).bc();B.play(H,a)}else B.play(H)}function e(a){if(0<C.length){var b=C[0];C.splice(0);var c=b.hc();o(b.jc());oa=c;la=function(){B=m(c.b);na=c.view};a()}else u.a("Game.showMiniGameChooser",{callback:function(b){oa=b;la=function(){u.a("Game.hideMiniGameChooser");B=m(b.b);na=b.view};o(J);a()},ac:Sa})}function i(){aa=new Ha;H=A;x="Monkey See";q&&(ka=
m(Ta),ka.q());e(function(){l(0);g();u.a("miniGameStarted",{},k)})}function l(a){R=a;u.a("backendScoreGameUpdateMiniGame",{Cc:R})}function o(a){u.a("learningTrackUpdate",{tc:a},k)}function n(a){a>K.get("global","monkeySeeRounds")&&("Monkey See"===x||"Monkey Do"===x)&&h("MonkeyWorld.MiniGameRoundOverMaxLimit");1>a&&h("MonkeyWorld.MiniGameRoundUnderMinLimit");ba=a}function m(a,b){a.prototype.j=u.j;a.prototype.b=u;a.prototype.d=c;var d=p;return d=b===j?new a:b!=j?new a(b):new a(b,j,j,j)}var q=k,w=!D,
u=this;T.call(this,"Game");this.j=new Ga;this.d=c;this.b=this;var G=new Ua,I=new Ja,A=m(Va),E=m(Wa),J=new Xa,S=new Ya,ca=new Za,x="Monkey See",B=G,na=p,ma=p,ka=p,la=p,H=A,ba=1,aa=I,R=0,oa=p,O=0,pa=p,C=[];q===j&&(q=k);w===j&&(w=k);q&&m($a);this.uc=function(){B===G&&h({name:"MonkeyWorld.NoActiveMiniGameException",message:"There is no active minigame"});q&&ma.m();l(R+B.dc());if("Child Play"===x)x="Monkey See",g();else if("Monkey See"===x){var a=B.K();aa.Wa(a);x="Monkey Do";H=E;g()}else if("Monkey Do"===
x)if(ba===K.get("global","monkeySeeRounds")){n(1);x="Child Play";H=A;f();var a=oa,b=R;26<b&&30>=b?(C.push(new V(a,ca)),C.push(new V(a,ca))):22<b&&26>=b?(C.push(new V(a,S)),C.push(new V(a,S)),C.push(new V(a,S))):0<=b&&22>=b?(C.push(new V(a,J)),C.push(new V(a.Xb.ra[0],J)),C.push(new V(a,J)),C.push(new V(a,J)),C.push(new V(a,J))):h("MW.NoSuchMinigameScore");i()}else n(ba+1),g()};this.da=function(){return pa};this.start=function(){var b=p,c=p;a(function(){w?(b=m(Na,function(a){b.m();c!=p&&c.m();pa=new a.view;
i()}),q&&(c=m(ab,b),c.q(),u.a("Game.viewInitiated"))):(pa=new Pa,i())})};this.stop=function(){f();x="Child Play";n(1);H=A;aa=I;this.a("Game.stop")};this.Ya=function(){this.stop();this.start()};this.Tb=function(a){console.log("addWaterDrop");u.a(sa);u.a("setPitcherLevel",{callback:function(){6===O?(console.log("OK"),d(a)):a!=j&&a()}});O+=1;console.log(O)};this.nc=function(){return O};this.ab=function(){H=E};this.bb=function(){H=A};this.Ua=function(){return H===A};this.Ta=function(){return H===E};this.ia=
function(){return"Child Play"===x};this.ha=function(){return"Monkey See"===x};this.e=function(){return"Monkey Do"===x}}function Za(){}Za.prototype.name=v("Fast");function Ya(){}Ya.prototype.name=v("Medium");function Xa(){}Xa.prototype.name=v("Regular");
function bb(){function c(){G=r;e.b.e()&&e.a(xa)}function a(a){G=k;e.b.e()&&!e.k()?e.n(wa,a):a()}function b(){n=W.J(i,l);I+=1;W.I(e.t(ua),function(){e.a(ya);e.a(P,{},k);e.b.e()||e.a(Q,{},k)})()}function d(a){u=k;W.I(e.t(za),e.t(N),e.Za(Aa),function(){e.Ea("correct");u=r;a()})()}function f(a){e.n(N,function(){e.a(P,{},k);e.b.e()||e.a(Q);e.na();e.a("Ladder.incorrect");4<=E&&e.a("Ladder.agentSuggestSolution");e.Ea("incorrect");a()})}function g(){var a=3<=q,c=1<=w;3===w||a&&c?(console.log("checkok"),W.I(e.t(Ca),
e.Bc)()):(console.log("placetreat"),b())}cb.call(this,"Ladder");var e=this,i=1,l=6,o=[],n=W.J(i,l),m=p,q=0,w=0,u=r,G=r,I=0,A=0,E=0;e.s(function(){var a,b=0;for(a=i;a<=l;a+=1)o[b]=a,b+=1});this.ka=function(){w+=1;e.b.ia()?(e.n(Ba),e.n(Fa,g)):(e.a(Ba),e.b.Tb(g))};this.p=function(b){m=b;q+=1;W.I(a,e.t("Ladder.picked",{w:b,De:b===n}),e.Za(Da),function(a){E=e.g()?E+1:0;e.g()&&b===n&&e.pc();a()},function(a){b===n&&(b<A&&(e.k()||e.g()))&&e.a("Ladder.betterBecauseSmaller");b===n&&(b>A&&(e.k()||e.g()))&&e.a("Ladder.betterBecauseBigger");
b!==n&&(e.k()||e.g())&&e.a("Ladder.hmm");e.b.e()&&(A=b);if(e.b.e()&&!e.g()||e.g()&&b===n)e.Ac(),e.a(Ea,{},k);a()},e.t(va),function(a){c();b===n?d(a):f(a);b<n&&(e.b.e()&&!e.k()&&!e.g())&&e.a("Ladder.agentTooLow");b>n&&(e.b.e()&&!e.k()&&!e.g())&&e.a("Ladder.agentTooHigh");b<n&&(e.b.ha()||e.k()||e.g())&&e.a("Ladder.tooLow");b>n&&(e.b.ha()||e.k()||e.g())&&e.a("Ladder.tooHigh");m=p})()};this.M=function(){return n};this.Na=function(){var a=W.J(0,o.length-1);return o[a]===n?this.Na():o[a]};this.gc=function(){m===
p&&h({name:"No number chosen yet",b:"Ladder",message:"A chosen number was asked for in the Ladder Game, but no number has yet been chosen by the user or the agent."});return m};this.L=function(){0===I&&h("MinigameNotStartedException");return I};this.ea=function(){return o};this.Qb(function(){G&&e.b.e()&&(c(),e.la(),u||(e.a("Ladder.interrupt",{}),e.n(N,function(){e.a(Q,{},k);e.a(P,{},k)})))});this.Rb(function(){e.a(Da,{},k);e.a(Ea,{},k);e.a("Ladder.start");e.b.ha()?e.n("Ladder.introduceAgent",b):e.b.e()?
e.n("Ladder.startAgent",b):b()});this.Sb(function(){e.a("Game.roundDone")})}
function cb(c){Ka.call(this,c);var a=this,b=[],d=[],f=r,g=r,e=p,i=10,l=p;this.Ea=function(a){e.yc(a)};this.la=function(){e.la()};this.Rb=function(a){b.push(a)};this.Sb=function(a){d.push(a)};this.start=function(){f&&h({name:"MW.MinigameModuleAlreadyStarted",message:"This minigame module ("+c+") has already been started."});for(f=k;0<b.length;)b.shift()()};this.stop=function(){g&&h({name:"MW.MinigameModuleAlreadyStopped",message:"This minigame module ("+c+") has already been stopped."});for(g=k;0<
d.length;)d.shift()()};this.na=function(){0<i&&(i--,a.a(ra,{Ja:i},k));e.na()};this.Sa=function(){return e.Sa()};this.K=function(){return e};this.dc=function(){return i};this.Bc=function(){z.debug("Round done","game");a.a("Game.roundDone");a.a("Game.nextRound");a.b.uc()};this.play=function(b,c){i=10;a.a(ra,{Ja:i},k);e=new Ia;console.log(this.h);l=new b.W[this.h](this,c);this.start()};var o=r,n=r,m=[];this.sc=function(){o=k;l.P();a.b.bb();for(var b=0;b<m.length;b+=1)m[b]()};this.Qb=function(a){m.push(a)};
this.Ac=function(){o=r;a.b.ab();l.zc()};this.k=function(){return o};this.oc=function(){n=k;a.b.bb()};this.pc=function(){n=r;a.b.ab()};this.g=function(){return n}}function Ua(){this.play=function(){h("No implemented mini game")}}Ua.prototype=new cb("NoMiniGame");var Sa=function(){var c={zd:{te:{b:bb,view:db,title:"Tree Game"},ne:{b:bb,view:eb,title:"Mountain Game"}}},a;for(a in c){var b=0,d=c[a],f=[],g;for(g in d)f.push(d[g]),d[g].Xb=d,b++;d.ra=f;d.Kc=function(){return b}}return c}();
function Va(){T.call(this,"GamerPlayer");this.cb("GamerPlayer");z.debug("Creating GamerPlayer","player");this.W=s();this.W.Ladder=s()}
function Wa(){z.debug("Creating MonkeyPlayer","player");T.call(this,"MonkeyPlayer");var c=this;this.W=s();this.W.Ladder=function(a,b){function d(c){g||(i++,setTimeout(function(){z.debug("Picking a number","agent");c===e||"incorrect"===b[c]?a.p(a.Na()):a.p(a.M())},2E3))}z.debug("Applying MonkeyPlayer's strategy to the Ladder","player");var f=0,g=r,e=W.J(0,b.length-1);z.debug("Will make mistake on try number "+e+1,"agent");var i=0;c.on("Ladder.readyToPick",function(){d(f++)});c.on("Ladder.incorrect",
function(){a.k()||(4>i?d(f++):4===i&&!a.g()&&(F.play(fb),a.oc()))});c.on("Ladder.correct",function(){i=0});this.P=function(){z.debug("Interrupting agent","agent");g=k;i=0};this.zc=function(){z.debug("Resuming agent","agent");g=r};c.on("Ladder.hasTarget",function(){setTimeout(function(){a.ka()},1500)});c.on("Game.stopMiniGame",function(){c.o()})}}
var gb={Y:"monkey.png",nb:"balloons.png",Gb:"Symbol-Stop.png",Fb:"Symbol-Check.png",yb:"Jungle_Bkg.png",ad:"elephant.png",he:"lion.png",qd:"giraff.png",wb:"bg-garden.png",xb:"bg-sadgarden.png",B:"minigames/treegame/background.png",Jb:"minigames/treegame/treedots.png",C:"minigames/treegame/lizard_cover.png",u:"minigames/treegame/lizard/lizard-standing.png",Hb:"minigames/treegame/lizard/lizard-step1.png",ya:"minigames/treegame/lizard/lizard-step2.png",ua:"minigames/treegame/lizard/mouth-1.png",va:"minigames/treegame/lizard/mouth-2.png",
wa:"minigames/treegame/lizard/mouth-3.png",xa:"minigames/treegame/lizard/mouth-4.png",D:"minigames/treegame/lizard/tongue/tongue-1.png",za:"minigames/treegame/lizard/tongue/tongue-2.png",Aa:"minigames/treegame/lizard/tongue/tongue-3.png",Ba:"minigames/treegame/lizard/tongue/tongue-4.png",Ib:"minigames/treegame/lizard/tongue/tongue-last.png",Ab:"nrpad.png",Bb:"minigames/treegame/paket-1.png",Cb:"minigames/treegame/paket-2.png",Db:"minigames/treegame/paket-3.png",X:"buttons/wood.png",ob:"buttons/wood-selected.png",
qb:"numbers/dots/prick-1.png",rb:"numbers/dots/prick-2.png",sb:"numbers/dots/prick-3.png",tb:"numbers/dots/prick-4.png",ub:"numbers/dots/prick-5.png",vb:"numbers/dots/prick-6.png",Zc:"moln.png",F:"vattendroppe.png",l:"vattenkanna.png",Z:"vattenkanna-botten.png",mb:"agents/mouse/normal.png",Qc:"agents/mouse/normal-no-arm.png",lb:"agents/mouse/head.png",kb:"agents/mouse/facials/m-normal.png",jb:"agents/mouse/facials/m-glad.png",Pc:"agents/mouse/facials/m-suprised.png"},X={},ga=function(){var c={},a=
0,b=0,d;for(d in X)a++;c.kc=function(){return b};c.Ra=function(c){z.debug("Loading images...","images");var d=0,e=Object.size(gb),i;for(i in gb){var l=gb[i];X[i]=new Image;X[i].onload=function(){++d>=e&&c();b=d/a};X[i].src="../res/img/"+l}};return c}();function Y(c,a,b){this.T=c;this.Ic=a;this.Ob=a!=p;this.Qa=b}
var hb=new Y("19446__totya__yeah","YAY"),ib=new Y("27882__stickinthemud__bike-horn-double-toot",p),jb=new Y("60443__jobro__tada1",p),kb=new Y("406__tictacshutup__click-1-d",p,4),lb=new Y(p,"NO_MY_TURN"),mb=new Y(p,"CHOOSE_YOUR_FRIEND"),nb=new Y(p,"THANKS_FOR_CHOOSING_ME"),ob=new Y(p,"BUT_YOU_CAN_INTERRUPT"),pb=new Y(p,"IM_GOING_TO_PICK_THIS_ONE"),qb=new Y(p,"MAYBE_THAT_WORKS"),rb=new Y(p,"YAY_HELPED_ME_GET_WATER_DROP_1"),sb=new Y(p,"YAY_HELPED_ME_GET_WATER_DROP_2"),tb=new Y(p,"LETS_FILL_THE_BUCKET"),
ub=new Y(p,"WHICH_ONE_DO_YOU_THINK_IT_IS"),vb=new Y("25879__acclivity__drip1",p),wb=new Y(p,"INTRO_1"),xb=new Y(p,"INTRO_2"),yb=new Y(p,"INTRO_3"),zb=new Y(p,"INTRO_4"),Ab=new Y(p,"INTRO_5"),Bb=new Y(p,"INTRO_GARDEN_1"),Cb=new Y(p,"INTRO_GARDEN_2"),Db=new Y(p,"LADDER_LOOKS_FUN"),Eb=new Y(p,"LADDER_SHOW_ME"),Fb=new Y(p,"LADDER_MY_TURN"),fb=new Y(p,"LADDER_PLEASE_HELP_ME"),Gb=new Y(p,"LADDER_TREE_OOPS_TOO_HIGH"),Hb=new Y(p,"LADDER_TREE_OOPS_TOO_LOW"),Ib=new Y(p,"LADDER_TREE_TRY_A_SMALLER_NUMBER"),Jb=
new Y(p,"LADDER_TREE_TRY_A_BIGGER_NUMBER"),Kb=new Y(p,"LADDER_TREE_AGENT_SUGGEST_SOLUTION_1"),Lb=new Y(p,"LADDER_TREE_AGENT_SUGGEST_SOLUTION_2"),Mb=new Y(p,"LADDER_TREE_BETTER_BECAUSE_BIGGER"),Nb=new Y(p,"LADDER_TREE_BETTER_BECAUSE_SMALLER"),Ob=new Y(p,"LADDER_TREE_AGENT_PLAY_TOO_LOW"),Pb=new Y(p,"LADDER_TREE_AGENT_PLAY_TOO_HIGH"),Qb=new Y(p,"LADDER_TREE_AGENT_SEE_CORRECT"),Rb=new Y("34208__acclivity__tongueclick1",p),Sb=new Y(p,"LADDER_MOUNTAIN_IM_DOWN_HERE"),Tb=new Y(p,"LADDER_MOUNTAIN_IM_UP_HERE"),
Ub=new Y(p,"LADDER_MOUNTAIN_TRY_FEWER_BALLOONS"),Vb=new Y(p,"LADDER_MOUNTAIN_TRY_MORE_BALLOONS"),Wb=new Y(p,"LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_1"),Xb=new Y(p,"LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_2"),Yb=new Y(p,"LADDER_MOUNTAIN_BETTER_BECAUSE_BIGGER"),Zb=new Y(p,"LADDER_MOUNTAIN_BETTER_BECAUSE_SMALLER"),$b=new Y(p,"LADDER_MOUNTAIN_AGENT_PLAY_TOO_LOW"),ac=new Y(p,"LADDER_MOUNTAIN_AGENT_PLAY_TOO_HIGH"),bc=new Y(p,"LADDER_MOUNTAIN_AGENT_SEE_CORRECT"),cc=new Y(p,"LADDER_MOUNTAIN_YOU_SAVED_ME"),
dc=new Y(p,"LADDER_MOUNTAIN_IM_HUNGRY"),ec={ve:hb,Sc:ib,qe:jb,Yc:kb,pe:lb,Xc:mb,re:nb,Vc:ob,rd:pb,ye:new Y(p,"YES_I_THINK_THAT_ONE_IS_BETTER"),je:qb,we:rb,xe:sb,fe:tb,ue:ub,le:new Y(p,"MONKEY_HMM"),ie:new Y("51710__bristolstories__u-chimes3_short",p),$c:vb,sd:wb,td:xb,ud:yb,vd:zb,wd:Ab,xd:Bb,yd:Cb,Dd:Db,Td:Eb,Rd:Fb,Bd:new Y(p,"LADDER_IS_IT_RIGHT"),Cd:new Y(p,"LADDER_IT_WAS_RIGHT"),Sd:fb,Ad:new Y(p,"LADDER_AGENT_HELP_IN_INTERRUPT"),ae:Gb,be:Hb,ee:Ib,de:Jb,Xd:Kb,Yd:Lb,Zd:Mb,$d:Nb,Vd:Ob,Ud:Pb,Wd:Qb,
ce:Rb,Ld:Sb,Nd:Tb,Od:Ub,Pd:Vb,Hd:Wb,Id:Xb,Jd:Yb,Kd:Zb,Fd:$b,Ed:ac,Gd:bc,Qd:cc,Md:dc,NUMBER_1:new Y(p,"NUMBER_1"),NUMBER_2:new Y(p,"NUMBER_2"),NUMBER_3:new Y(p,"NUMBER_3"),NUMBER_4:new Y(p,"NUMBER_4"),NUMBER_5:new Y(p,"NUMBER_5"),NUMBER_6:new Y(p,"NUMBER_6"),NUMBER_7:new Y(p,"NUMBER_7"),NUMBER_8:new Y(p,"NUMBER_8"),NUMBER_9:new Y(p,"NUMBER_9"),NUMBER_10:new Y(p,"NUMBER_10"),Rc:new Y(p,"ARE_YOU_READY_TO_TEACH"),pd:new Y(p,p,2),hd:new Y(p,"FISHING_FREE_WRONG_ONES"),ed:new Y(p,"FISHING_CATCH"),kd:new Y(p,
"FISHING_NOT_THIS_ONE"),nd:new Y(p,"FISHING_THERE_ARE_MORE"),jd:new Y(p,"FISHING_KEEP_GOING"),dd:new Y(p,"FISHING_ARE_YOU_SURE"),fd:new Y(p,"FISHING_COUNT_FISH"),gd:new Y(p,"FISHING_COUNT_TARGET_FISH"),od:new Y(p,p),ld:new Y(p,p),md:new Y(p,p),bd:new Y(p,"FISHING_ANGEL_CHOOSE_FISH"),cd:new Y(p,"FISHING_ANGEL_COUNT"),Uc:new Y(p,"BUBBA_HI"),Tc:new Y(p,"BUBBA_HERE_TO_HELP"),me:new Y(p,"MONKEY_LEARNED_WELL"),ke:new Y(p,"MONKEY_DIDNT_LEARN_WELL"),ge:new Y(p,"LETS_SHOW_HIM_AGAIN"),se:new Y(p,"THANK_YOU_FOR_HELPING"),
oe:new Y(p,"NOW_MONKEY_SHOW_YOU")},F=function(){function c(a){for(var b=0;b<f.length;b++)f[b].attrs.y-=30;f.push(a)}var a={},b=p,d=p,f=[],g=p,e=k;a.Fc=function(a){b=a;d=b.Nb};a.lc=function(){if(g===p){g=[];for(var a in ec){var b=ec[a];ec[a].Da=a;if(b.T!=p){var c={id:a,src:"../res/sound/"+b.T+".ogg|../res/sound/"+b.T+".mp3"};b.Qa!=j&&(c.data=b.Qa);g.push(c)}}}return g};a.play=function(a){var g=a.Ic;z.vc('"'+g+'"');if(e&&a.Ob){var o=new Kinetic.Text({x:0,y:d.getParent().attrs.height-50,text:U.get(g),
fontSize:26,fontFamily:"Nobile",textFill:"white",textStroke:"black",align:"center",fontStyle:"bold",width:d.getParent().getWidth(),height:50,verticalAlign:"middle",textStrokeWidth:2});c(o);d.add(o);b.Va();setTimeout(function(){d.remove(o);b.Va();for(var a=0;a<f.length;a++)f[a]===o&&f.splice(a,1)},3E3)}a.T!=p&&SoundJS.play(a.Da)};a.stop=function(a){SoundJS.stop(a.Da)};a.Nc=function(){e?(e=r,console.info("Turning off subtitles")):(e=k,console.info("Turning on subtitles"))};return a}(),U=function(){var c=
{INIT_LOADING_SOUNDS:{sv:"Laddar ner ljud...",en:"Downloading sounds..."},INIT_LOADING_IMAGES:{sv:"Laddar ner bilder...",en:"Downloading images..."},RESTART:{sv:"Starta om",en:"Restart"},SETTINGS:{sv:"Inst\u00e4llningar",en:"Settings"},YAY:{sv:"Hurra!",en:"Yay!"},INTRO_1:{sv:"Hej! De h\u00e4r v\u00e4nnerna beh\u00f6ver din hj\u00e4lp",en:"Hello! These friends need your help"},INTRO_2:{sv:"med att f\u00e5 deras tr\u00e4dg\u00e5rd att v\u00e4xa.",en:"to make their garden grow."},INTRO_3:{sv:"Om du kan l\u00e4ra din v\u00e4n hur man spelar spelen",
en:"If you can teach your friend how to do the games"},INTRO_4:{sv:"kan han eller hon samla vattendroppar -",en:"he or she can collect water drops -"},INTRO_5:{sv:"- f\u00f6r att f\u00e5 deras tr\u00e4dg\u00e5rd att v\u00e4xa -",en:"- to make their garden grow again -"},INTRO_GARDEN_1:{sv:"- fr\u00e5n det h\u00e4r...",en:"- from this..."},INTRO_GARDEN_2:{sv:"...till det h\u00e4r!",en:"...to this!"},CHOOSE_YOUR_FRIEND:{sv:"B\u00f6rja med att v\u00e4lja vilken v\u00e4n du vill hj\u00e4lpa!",en:"First, choose the friend you would like to teach!"},
THANKS_FOR_CHOOSING_ME:{sv:"Ja! Tack f\u00f6r att du valde mig!",en:"Yay! Thanks for choosing me!"},ARE_YOU_READY_TO_TEACH:{sv:"\u00c4r du redo att l\u00e4ra apan?",en:"Are you ready to teach monkey?"},NO_MY_TURN:{sv:"Gl\u00f6m inte att det \u00e4r MIN tur nu!",en:"Remember it\u2019s MY turn now!"},BUT_YOU_CAN_INTERRUPT:{sv:"Men du kan avbryta mig om jag g\u00f6r fel.",en:"But you can interrupt me if I'm making a mistake."},MAYBE_THAT_WORKS:{sv:"Okej, vi testar och ser om det \u00e4r r\u00e4tt.",
en:"OK, let's see if this works."},YAY_HELPED_ME_GET_WATER_DROP_1:{sv:"Hurra! Du hj\u00e4lpte mig att f\u00e5 en vattendroppe",en:"Yay! You helped me get a water drop"},YAY_HELPED_ME_GET_WATER_DROP_2:{sv:"till min tr\u00e4dg\u00e5rd, s\u00e5 den kan v\u00e4xa!",en:"for my garden to grow again!"},LETS_FILL_THE_BUCKET:{sv:"Kom igen och fyll kannan!",en:"Let's fill the bucket!"},WHICH_ONE_DO_YOU_THINK_IT_IS:{sv:"Vilken tror du att det \u00e4r?",en:"Which one do you think it is?"},YES_I_THINK_THAT_ONE_IS_BETTER:{sv:"Ja, det d\u00e4r fungerar nog b\u00e4ttre!",
en:"Yes, I think that one is better!"},LADDER_TREE_BETTER_BECAUSE_BIGGER:{sv:"Ja, det verkar vara ett bra val, eftersom den \u00c4R st\u00f6rre!",en:"Yes, that seems to be a good choice because it IS bigger!"},LADDER_TREE_BETTER_BECAUSE_SMALLER:{sv:"Ja, det verkar vara ett bra val, eftersom den \u00c4R mindre!",en:"Yes, that seems to be a good choice because it IS smaller!"},IM_GOING_TO_PICK_THIS_ONE:{sv:"Okej, f\u00e5r se om den h\u00e4r fungerar. Hmm...",en:"Ok, let's see if this works. Hmm..."},
FISHING_CATCH_NUMBER:{sv:"F\u00e5nga nummer %1",en:"Catch number %1"},FISHING_CATCH:{sv:"F\u00e5nga",en:"Catch"},FISHING_FREE_WRONG_ONES:{sv:"Frige fiskarna som \u00e4r fel",en:"Put back the wrong fish"},FISHING_NOT_THIS_ONE:{sv:"Inte den!",en:"Not this one!"},FISHING_THERE_ARE_MORE:{sv:"Det finns mer fiskar att f\u00e5nga. Forts\u00e4tt leta!",en:"There are more fish to catch. Keep looking!"},FISHING_ARE_YOU_SURE:{sv:"\u00c4r du s\u00e4ker?",en:"Are you sure?"},FISHING_COUNT_FISH:{sv:"R\u00e4kna fiskarna!",
en:"Count the fish!"},FISHING_COUNT_TARGET_FISH:{sv:"R\u00e4kna fiskarna med",en:"Count the fish with"},FISHING_ANGEL_CHOOSE_FISH:{sv:"Jag v\u00e4ljer den h\u00e4r fisken eftersom...",en:"I choose this fish, because it..."},FISHING_ANGEL_COUNT:{sv:"Jag v\u00e4ljer den h\u00e4r siffran eftersom...",en:"I choose this number, because..."},LADDER_LOOKS_FUN:{sv:"Det d\u00e4r s\u00e5g kul ut!",en:"That looked fun!"},LADDER_SHOW_ME:{sv:"Visa mig hur man g\u00f6r!",en:"Now show me how to do it!"},LADDER_MY_TURN:{sv:"Okej, nu ska vi se om jag klarar det h\u00e4r sj\u00e4lv!",
en:"Ok, now let's see if I can do this on my own!"},LADDER_IS_IT_RIGHT:{sv:"G\u00f6r jag r\u00e4tt eller fel?",en:"Am I doing it right or wrong?"},LADDER_IT_WAS_RIGHT:{sv:"Ja! Du fick presenten!",en:"Yeah! You got it!"},LADDER_TREE_OOPS_TOO_HIGH:{sv:"Oj, kanske tog vi i f\u00f6r mycket!",en:"Oops! Maybe we overdid it!"},LADDER_TREE_OOPS_TOO_LOW:{sv:"Hmm... Kanske var det inte tillr\u00e4ckligt!",en:"Hmm... Maybe it wasn't enough!"},LADDER_TREE_TRY_A_SMALLER_NUMBER:{sv:"Vi kan v\u00e4l testa en mindre och se vad som h\u00e4nder!",
en:"Let's try a smaller one and see what happens!"},LADDER_TREE_TRY_A_BIGGER_NUMBER:{sv:"Vad tror du? Ska vi testa en st\u00f6rre?",en:"What do you think? Shall we try a bigger one?"},LADDER_TREE_AGENT_PLAY_TOO_LOW:{sv:"Hmm, det gick inte. Jag undrar varf\u00f6r. Jag testar en st\u00f6rre!",en:"Hmm, that didn't work. I wonder why. Let me try a bigger one!"},LADDER_TREE_AGENT_PLAY_TOO_HIGH:{sv:"\u00c5h, nej! Var den f\u00f6r stor?",en:"Oh no! Was that too big?"},LADDER_TREE_AGENT_SEE_CORRECT:{sv:"WOO! Tack f\u00f6r hj\u00e4lpen! Vilken fin present!",
en:"WOO! Thank you for helping me! What a great surprise!"},LADDER_TREE_AGENT_SUGGEST_SOLUTION_1:{sv:"Kanske kan vi f\u00f6rs\u00f6ka med samma siffra p\u00e5",en:"Maybe we should match the number on"},LADDER_TREE_AGENT_SUGGEST_SOLUTION_2:{sv:"nummerplattan som vid presenten?",en:"the number pad to the number by the gift?"},LADDER_PLEASE_HELP_ME:{sv:"Kan du hj\u00e4lpa mig att v\u00e4lja r\u00e4tt?",en:"Can you please help me find the right one?"},LADDER_MOUNTAIN_IM_DOWN_HERE:{sv:"Jag \u00e4r h\u00e4r nere!",
en:"I'm down here!"},LADDER_MOUNTAIN_IM_UP_HERE:{sv:"Jag \u00e4r h\u00e4r uppe!",en:"I'm up here!"},LADDER_MOUNTAIN_YOU_SAVED_ME:{sv:"Du r\u00e4ddade mig!!!",en:"You saved me!!!"},LADDER_MOUNTAIN_IM_HUNGRY:{sv:"Jag \u00e4r hungrig. Kom s\u00e5 g\u00e5r vi och \u00e4ter!",en:"I'm hungry. Let's go eat!"},LADDER_MOUNTAIN_TRY_FEWER_BALLOONS:{sv:"Kanske ska vi testa med f\u00e4rre ballonger?",en:"Perhaps we should try with fewer balloons?"},LADDER_MOUNTAIN_TRY_MORE_BALLOONS:{sv:"Vi kan v\u00e4l testa med fler ballonger och se vad som h\u00e4nder?",
en:"Let's try with more balloons and see what happens!"},LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_1:{sv:"Kanske kan vi f\u00f6rs\u00f6ka med lika m\u00e5nga ballonger",en:"Maybe we should match the number of balloons"},LADDER_MOUNTAIN_AGENT_SUGGEST_SOLUTION_2:{sv:"som niv\u00e5er upp din v\u00e4n \u00e4r.",en:"to the level your friend is stuck on."},LADDER_MOUNTAIN_AGENT_PLAY_TOO_LOW:{sv:"Oj, det kanske var f\u00f6r f\u00e5 ballonger.",en:"Oops, maybe I used to few balloons."},LADDER_MOUNTAIN_AGENT_PLAY_TOO_HIGH:{sv:"Hoppsan, det var nog f\u00f6r m\u00e5nga ballonger!",
en:"Oops, I think there were too many balloons!"},LADDER_MOUNTAIN_BETTER_BECAUSE_BIGGER:{sv:"Ja, det fungerar nog, f\u00f6r det \u00c4R fler ballonger!",en:"Yes, this can work, beacuse that IS more ballons!"},LADDER_MOUNTAIN_BETTER_BECAUSE_SMALLER:{sv:"Ja, det fungerar nog, f\u00f6r det \u00c4R f\u00e4rre ballonger!",en:"Yes, this will probably work, beacuse that IS fewer balloons!"},LADDER_MOUNTAIN_AGENT_SEE_CORRECT:{sv:"WOO! Tack f\u00f6r hj\u00e4lpen! Vi r\u00e4ddade v\u00e5r v\u00e4n!",en:"WOO! Thank you for helping me! We saved our friend!"},
BUBBA_HI:{sv:"Hej! Mitt namn \u00e4r Bubba!",en:"Hi, my name is Bubba!"},BUBBA_HERE_TO_HELP:{sv:"Jag ska hj\u00e4lpa dig och apan l\u00e4ngs v\u00e4gen.",en:"I'm here to help you and monkey throughout his journey."},MONKEY_LEARNED_WELL:{sv:"Toppen! Apan l\u00e4rde sig bra!",en:"Great! Monkey learned well!"},MONKEY_DIDNT_LEARN_WELL:{sv:"\u00c5h, nej! Apan l\u00e4rde sig inte riktigt.",en:"Oh no! Monkey didn't learn well."},LETS_SHOW_HIM_AGAIN:{sv:"Visa honom igen!",en:"Let's show him again!"},THANK_YOU_FOR_HELPING:{sv:"Tack f\u00f6r att du hj\u00e4lpte apan!",
en:"Thank you for helping monkey!"},NOW_MONKEY_SHOW_YOU:{sv:"Nu visar apan dig vad den har l\u00e4rt sig!",en:"Now monkey show you what it learned!"},MONKEYS_TURN:{sv:"Apans tur!",en:"Monkey's turn!"},MONKEY_HMM:{sv:"Apan: Hmmm...",en:"Monkey: Hmm..."},FISHING_KEEP_GOING:{sv:"Forts\u00e4tt!",en:"Keep going!"},NUMBER_1:{sv:"nummer 1",en:"number 1"},NUMBER_2:{sv:"nummer 2",en:"number 2"},NUMBER_3:{sv:"nummer 3",en:"number 3"},NUMBER_4:{sv:"nummer 4",en:"number 4"},NUMBER_5:{sv:"nummer 5",en:"number 5"},
NUMBER_6:{sv:"nummer 6",en:"number 6"},NUMBER_7:{sv:"nummer 7",en:"number 7"},NUMBER_8:{sv:"nummer 8",en:"number 8"},NUMBER_9:{sv:"nummer 9",en:"number 9"},NUMBER_10:{sv:"nummer 10",en:"number 10"},SETTINGS_LABEL:{sv:"Inst\u00e4llningar",en:"Settings"},SETTINGS_APPLY:{sv:"Verkst\u00e4ll",en:"Apply"},SETTINGS_SHOW:{sv:"Visa inst\u00e4llningar",en:"Show settings"},SETTINGS_HIDE:{sv:"G\u00f6m inst\u00e4llningar",en:"Hide settings"},SETTINGS_CANCEL:{sv:"Avbryt",en:"Cancel"},SETTINGS_GLOBAL_LABEL:{sv:"Globala",
en:"Global"},SETTINGS_GLOBAL_LANGUAGE_LABEL:{sv:'Spr\u00e5k (kan vara "sv" eller "en" och kr\u00e4ver omstart)',en:'Language (can be "sv" or "en" and requires restart)'},SETTINGS_GLOBAL_MONKEYSEEROUNDS_LABEL:{sv:"Monkey See-rundor",en:"Monkey See rounds"},SETTINGS_GLOBAL_TRIESBEFOREGUARDIANANGEL_LABEL:{sv:"F\u00f6rs\u00f6k innan skydds\u00e4ngel",en:"Tries before guardian angel"},SETTINGS_MINIGAMES_LABEL:{sv:"Minispel",en:"Mini-games"},SETTINGS_MINIGAMES_FISHINGGAME_LABEL:{sv:"Fiskespel",en:"Fishing Game"},
SETTINGS_MINIGAMES_FISHINGGAME_TARGETNUMBER_LABEL:{sv:"M\u00e5lnummer",en:"Target number"},SETTINGS_MINIGAMES_FISHINGGAME_NUMBERCORRECT_LABEL:{sv:"Antal korrekta fiskar",en:"Number of correct fish"},SETTINGS_MINIGAMES_FISHINGGAME_NUMBEROFFISH_LABEL:{sv:"Antal fiskar totalt",en:"Number of fish totally"},SETTINGS_MINIGAMES_FISHINGGAME_MAXNUMBER_LABEL:{sv:"H\u00f6gsta m\u00f6jliga nummer",en:"Maximum number on fish"},SETTINGS_MINIGAMES_LADDER_LABEL:{sv:"Stegen",en:"The Ladder"},SETTINGS_MINIGAMES_LADDER_TARGETNUMBER_LABEL:{sv:"M\u00e5lnummer",
en:"Target number"}};return{get:function(a,b){if(c[a]===j)return p;for(var d=c[a][K.get("global","language")],f=1;f<arguments.length;f++)d=d.replace("%"+f,arguments[f]);return d}}}();Object.size=function(c){var a=0,b;for(b in c)c.hasOwnProperty(b)&&a++;return a};
var z=new function(){function c(a,b,c,f){var g=console;c===j?c="":"string"!==typeof c&&(c="");if("evm"!=c&&"sound"!=c){for(var c=c.substr(0,8),c=c.toUpperCase(),e=8-c.length,i=0;i<e;i++)c=" "+c;f.call(g,a+" "+c+" "+b)}}console.log("Creating Log");this.debug=function(a,b){c("DEBUG  ",a,b,console.debug)};this.vc=function(a){c("NOTIFY ",a,"sound",console.info)};this.error=function(a,b){c("ERROR  ",a,b,console.error)}};Array.prototype.remove=function(c){for(var a=0;a<this.length;a++)this[a]===c&&this.splice(a)};
var W=new function(){function c(a,b,c,f,g){var e=0,i=0;this.next=function(){var l=a+e*c,o=b+i*f;e=(e+1)%g;0==e&&i++;return{x:l,y:o}}}this.I=function(a){var b=arguments;return function(a){var c,g=[],e=p,i=k;for(c=0;c<b.length;c+=1)g.push(b[c]);e=function(b){i&&(b=a,i=r);var c=g.shift();c!=j&&c(e,b)};e()}};this.J=function(a,b){return Math.floor(Math.random()*(b-a+1))+a};this.rc=function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return k;return r};this.N=function(a,b,d,f,g){return new c(a,b,d,f,g)}};
Kinetic.Wc=function(c){var a=new Kinetic.Group({x:c.x,y:c.y,width:c.width,height:c.height}),b=new Kinetic.Rect({x:0,y:0,width:c.width,height:c.height,fill:"#ccc",strokeWidth:1,stroke:"white"}),d=new Kinetic.Text({text:c.text,fontFamily:"Arial",textFill:"black",fontSize:c.fontSize,x:c.width/2,y:c.height/2,verticalAlign:"middle",align:"center"});a.add(b);a.add(d);a.on("mousedown touchstart",c.callback);return a};
function fc(){var c=this;this.ec=function(a,b){var d=new Kinetic.Group({x:a,y:b}),f=new Kinetic.Image({image:c.U(),offset:{x:0,y:0},width:c.U().width,height:c.U().height}),g=new Kinetic.Image({image:c.Q(),x:-12,y:-11});d.add(f);d.add(g);return d};this.ic=function(a){var a=new Kinetic.Group({x:a,y:12}),b=new Kinetic.Image({image:c.head(),width:c.head().width,height:c.head().height}),d=new Kinetic.Image({image:c.Q(),x:-12,y:-11});a.add(b);a.add(d);return a}}
function Oa(){fc.call(this);this.Q=function(){return X.Y};this.O=function(){return X.Y};this.U=function(){return X.Y}}function Pa(){fc.call(this);this.head=function(){return X.lb};this.U=function(){return X.mb};this.Q=function(){return X.kb};this.O=function(){return X.jb}}
function ab(c){function a(a,b,d){var l=new Kinetic.Group({x:b,y:d}),b=new Kinetic.Rect({width:250,height:250,fill:{start:{x:125,y:125,radius:0},end:{x:125,y:125,radius:187.5},colorStops:[0,"#00FF7F",1,"#556B2F"]},shadow:{color:"black",blur:15,offset:[15,15],alpha:0.5},alpha:0.6,cornerRadius:10,strokeWidth:4,stroke:"white",offset:{x:125,y:125}});l.add(b);l.r=b;l.Kb=a;a=new a.view;a=new Kinetic.Image({image:a.O(),offset:{x:a.O().width/2,y:a.O().height/2}});l.add(a);l.on("mousedown touchstart",function(){F.play(kb);
l.r.setFill("white");l.moveToTop();f.Vb(l,function(){c.Yb(l.Kb)});f.Zb()});return l}Z.call(this,"AgentChooserView");var b=this,d=p,f=function(){var a=[];this.add=function(b){a.push(b);d.add(b)};this.Zb=function(){for(var b=0;b<a.length;b++)a[b].attrs.listening=r};this.Vb=function(c,d){for(var f=0;f<a.length;f++)a[f]===c?(b.c(a[f].attrs).wait(1E3).to({x:b.d.getWidth()/2,y:b.d.getHeight()/2},1E3),b.c(a[f].attrs.scale).wait(1E3).to({x:1.5,y:1.5},1E3).call(function(){F.play(nb)}).wait(5E3).call(d)):b.c(a[f].attrs).to({alpha:0},
1E3)};return this}();b.q=function(){d=new Kinetic.Layer;b.d.add(d);var g=new Kinetic.Image({image:X.yb});d.add(g);for(var g=W.N(363,230,310,310,2),e=c.cc(),i=0;i<e.length;i++){var l=g.next();f.add(new a(e[i],l.x,l.y))}F.play(mb)};b.i(function(){b.d.remove(d)});b.on(L,function(){d.draw()})}
function Ra(){Z.call(this,"GardenView");var c=this,a,b,d,f,g,e;c.s(function(){a=new Kinetic.Image({image:X.xb});b=new Kinetic.Image({image:X.wb});f=new Kinetic.Group({x:300,y:300,visible:r});g=new Kinetic.Image({image:X.l,offset:{x:X.l.width/2,y:X.l.height/2}});e=new Kinetic.Polygon({points:[{x:40,y:0},{x:60,y:0},{x:80,y:40},{x:41,y:63},{x:15,y:17}],offset:{x:X.l.width/2,y:X.l.height/2},fill:"blue"});d=new Kinetic.Layer;c.getStage().add(d);d.add(a);d.add(f);f.add(e);f.add(g)});c.i(function(){c.getStage().remove(d)});
c.on(L,function(){d.draw()});c.on("Game.demonstrateGarden",function(e){F.play(Bb);b.setAlpha(0);d.add(a);d.add(b);setTimeout(function(){F.play(Cb);c.c(a.attrs).to({alpha:0},2E3);c.c(b.attrs).to({alpha:1},2E3).wait(3E3).call(e.callback)},3E3)});c.on("Game.waterGarden",function(a){var b=e.attrs.points,d=(b[0].y-b[4].y)/(b[0].x-b[4].x),n=(b[2].y-b[1].y)/(b[2].x-b[1].x),m=b[0].y+17,q=b[0].y-d*b[0].x,w=b[2].y-n*b[2].x;f.show();setTimeout(function(){c.c(g.attrs).to({rotation:Math.PI/3});setTimeout(function(){e.transitionTo({points:{"0":{x:(m-
q)/d,y:m},1:{x:(m-w)/n,y:m}},duration:3,callback:function(){var c=(b[3].y-b[4].y)/(b[3].x-b[4].x),d=b[3].y-c*b[3].x;m+=b[3].y-b[2].y;e.transitionTo({points:{"0":{x:(m-d)/c,y:m},1:{x:(m-w)/n,y:m}},duration:3,callback:function(){m+=b[3].y-b[2].y;e.transitionTo({points:{"0":{x:(m-d)/c,y:m},1:{x:(m-d)/c,y:m}},duration:2,callback:function(){setTimeout(function(){a.callback()},3E3)}})}})}})},1E3)},1E3)})}
function Qa(c){Z.call(this,"IntroductionView");var a=this,b,d;a.s(function(){b=a.getStage();d=new Kinetic.Layer;b.add(d);a.setTimeout(function(){F.play(wb)},2E3);a.setTimeout(function(){F.play(xb)},2E3);a.setTimeout(function(){F.play(yb)},7E3);a.setTimeout(function(){F.play(zb)},7E3);a.setTimeout(function(){F.play(Ab)},12E3);a.setTimeout(function(){c()},14E3)});a.i(function(){b.remove(d)});a.on(L,function(){d.draw()})}
function Ta(){Z.call(this,"MinigameHandlerView");var c=this.d.G;(function(a){var b=new Kinetic.Text({text:"Backend Score (current minigame):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:a.d.getWidth()-700,y:35}),d=r,f=r;a.on("backendScoreGameUpdateMiniGame",function(a){b.setText("Backend Score (current minigame): "+a.Cc)});a.on("miniGameStarted",function(){f=d=k;c.add(b)});a.on(M,function(){f&&!d?(c.add(b),d=k,console.info("Turning off backend score display")):
f&&d&&(c.remove(b),d=r,console.info("Turning on backend score display"))});a.i(function(){d=f=r;c.remove(b)})})(this);(function(a){var b=new Kinetic.Text({text:"Learning track (current game):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:a.d.getWidth()-700,y:55}),d=r,f=r;a.on("miniGameStarted",function(){c.add(b);d=f=k});a.on("learningTrackUpdate",function(a){b.setText("Learning track (current game): "+a.tc.name())});a.on(M,function(){f&&!d?(c.add(b),
d=k):f&&d&&(c.remove(b),d=r)});a.i(function(){d=f=r;c.remove(b)})})(this);(function(a){var b,d,f,g,e=10,i=20;a.s(function(){b=new Kinetic.Image({image:X.l,x:c.getStage().getWidth()-X.l.width-20,y:20,width:X.l.width,height:X.l.height,visible:r});d=new Kinetic.Image({image:X.F,offset:{x:X.F.width/2,y:0},width:X.F.width,height:X.F.height,visible:r,rotation:Math.PI});f=new Kinetic.Image({image:X.Z,x:b.getX(),y:b.getY(),width:X.Z.width,height:X.Z.height,visible:r});g=new Kinetic.Rect({fill:"#379de4",x:b.getX()+
20,y:b.getY()+b.getHeight()-4,width:54,height:0});c.add(f);c.add(g);c.add(d);c.add(b)});a.i(function(){c.remove(d);c.remove(b);c.remove(f);c.remove(g)});a.on("miniGameStarted",function(){b.show();var c=a.b.nc();0<c&&f.show();g.setHeight(g.getHeight()-6.9*c)});a.on("resetPitcherLevel",function(){f.hide();g.setHeight(0)});a.on(ta,function(a){e=a.x;i=a.y});a.on("setPitcherLevel",function(c){var o=b.getX()+b.getWidth()/2,n=b.getY()+b.getHeight()-d.getHeight(),m=1E3*(Math.sqrt(Math.pow(e-o,2)+Math.pow(i-
n,2))/200);d.setX(e);d.setY(i);d.setAlpha(1);d.show();F.play(rb);F.play(sb);a.setTimeout(function(){F.play(tb)},2E3);a.c(d.attrs).to({x:o-50,y:n},1.2*m).to({rotation:4*Math.PI/3,x:o-50,y:n-30},300).to({rotation:5*Math.PI/3,x:o-25,y:n-25},300).to({rotation:6*Math.PI/3,x:o,y:n},300).call(function(){F.play(vb);f.show();a.c(g.attrs).to({height:g.getHeight()-6.9},1E3);a.c(d.attrs).to({alpha:0},1E3).wait(1E3).call(function(){d.hide();d.setRotation(Math.PI);c.callback!=j&&c.callback()})})})})(this)}
function $a(){Z.call(this,"MonkeyWorldView");var c=this.d,a=c.G;this.m=function(){this.o()};(function(b){var c=[];b.on("Game.showMiniGameChooser",function(b){var g=b.callback,e=b.ac,i=W.N(200,200,300,100,2),l;for(l in e)(function(){for(var b=0;b<e[l].Kc();b++)(function(){console.log(e[l].ra[b]);var f=e[l].ra[b],m=i.next(),m=new Kinetic.Group(m),q=new Kinetic.Rect({width:280,height:100,stroke:"black",strokeWidth:4}),w=new Kinetic.Text({text:f.title,fontSize:20,fontFamily:"sans-serif",textFill:"black",
align:"center",verticalAlign:"center",width:280,height:100,y:40});w.He("center");m.add(q);m.add(w);m.on("mousedown touchstart",function(){q.setFill("yellow");g(f)});c.push(m);a.add(m)})()})()});b.on("Game.hideMiniGameChooser",function(){for(var b=0;b<c.length;b++)a.remove(c[b]);c=[]})})(this);(function(b){var d=new Kinetic.Rect({x:c.getWidth()/2,y:c.getHeight()/2,width:320,height:50,cornerRadius:10,offset:{x:160,y:25},fill:"#333",alpha:0}),f=new Kinetic.Rect({x:c.getWidth()/2,y:c.getHeight()/2,width:0,
height:30,offset:{x:150,y:15},fill:"#FFCC00"}),g=new Kinetic.Text({fontFamily:"Arial",fontSize:10,textFill:"black",fontStyle:"bold",Je:"black",text:"Monkey World Demo",align:"center",width:c.getWidth(),height:50,y:c.getHeight()/2-50,x:0});b.on("Game.showLoadingScreen",function(b){a.add(d);a.add(f);a.add(g);d.transitionTo({alpha:1,duration:b.time/1E3})});b.on("Game.loadingSounds",function(){g.setText(U.get("INIT_LOADING_SOUNDS"))});b.on("Game.loadingImages",function(){g.setText(U.get("INIT_LOADING_IMAGES"))});
b.on("Game.loadingDone",function(){a.remove(g);a.remove(d);a.remove(f)});b.on("Game.updateSoundLoading",function(a){f.setWidth(300*a.progress)});b.on("Game.updateImageLoading",function(a){f.setWidth(300*a.progress)})})(this)}
Kinetic.A.zb=function(c,a){function b(b){a.c(g.attrs).to({image:X.ua}).wait(l).to({image:X.va}).wait(l).to({image:X.wa}).wait(l).to({image:X.xa}).call(b)}function d(b){a.c(n.attrs).to({image:X.Ba}).wait(o).to({image:X.Aa}).wait(o).to({image:X.za}).wait(o).to({image:X.D}).wait(o).to({visible:r}).call(b)}var f=new Kinetic.Group(c),g,e,i,l=200,o=200,n;g=new Kinetic.Image({image:X.u,width:X.u.width,height:X.u.height});n=new Kinetic.Image({image:X.D,width:X.D.width,height:X.D.height,visible:r,x:109,y:81,
offset:{x:279,y:281}});f.add(n);f.add(g);this.V=function(){g.attrs.image=X.ya;e=a.setInterval(function(){g.attrs.image=X.Hb;i=a.setTimeout(function(){g.attrs.image=X.ya},140)},280)};this.z=function(){a.clearInterval(e);a.clearTimeout(i);g.attrs.image=X.u};f.V=this.V;f.z=this.z;f.Mc=function(c){b(function(){n.show();a.c(n.attrs).to({image:X.za}).wait(o).to({image:X.Aa}).wait(o).to({image:X.Ba}).wait(o).to({image:X.Ib}).call(c)})};f.Lc=function(b){d(function(){a.c(g.attrs).to({image:X.xa}).wait(l).to({image:X.wa}).wait(l).to({image:X.va}).wait(l).to({image:X.ua}).wait(l).to({image:X.u}).call(b)})};
return f};
Kinetic.A.Eb=function(c){var a,b;a=new Kinetic.Group(c);switch(c.type){case 1:b=X.Bb;break;case 2:b=X.Cb;break;case 3:b=X.Db;break;default:h("NoSuchParcelTypeException")}c=new Kinetic.Image({image:b,width:b.width,height:b.height,offset:{x:b.width/2,y:b.height/2},shadow:{color:"black",blur:10,offset:[3,3],alpha:0.5}});a.add(c);a.Gc=function(b){var c=a.getX(),g=a.getY();b.c(a.attrs).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+5},100).to({x:c-5},100).to({x:c+
5},100).to({x:c-5},100).to({x:c},100);b.c(a.attrs).to({y:g-5},100).to({y:g+5},100).to({y:g-5},100).to({y:g+5},100).to({y:g-5},100).to({y:g+5},100).to({y:g-5},100).to({y:g+5},100).to({y:g-5},100).to({y:g},100)};a.xc=function(b){a.on("mousedown touchstart",b)};a.wc=function(){a.off("mousedown touchstart")};a.open=s();return a};
function gc(c){Z.call(this,c);var a=this.d.G;(function(b){var c=new Kinetic.Text({text:"Backend Score (current mode):",fontSize:12,fontFamily:"sans-serif",textFill:"black",align:"left",verticalAlign:"middle",x:b.d.getWidth()-700,y:15});a.add(c);var f=k,g=f;b.on(ra,function(a){c.setText("Backend Score (current mode): "+a.Ja)});b.on(M,function(){g&&!f?(a.add(c),f=k):g&&f&&(a.remove(c),f=r)});b.i(function(){a.remove(c);f=g=r})})(this);(function(b){var c=b.b.da().Q(),f=(new b.b.da).ic(b.getStage().getWidth()-
c.width-30);f.setScale(0.5);b.s(function(){b.b.ia()&&a.add(f)});b.i(function(){a.remove(f)})})(this)}
function hc(c,a){gc.call(this,c);this.cb(c);z.debug("Creating LadderView","object");var b=this,d=p,f=p,g=p,e=p,i={x:800,y:650};this.Ga=function(a){d=new Kinetic.Image({image:X.Gb,x:750,y:700,offset:{x:64,y:64},alpha:0});f=new Kinetic.Image({image:X.Fb,x:900,y:700,offset:{x:64,y:64},alpha:0});a.add(d);a.add(f)};this.Fa=function(a,c,d,f){b.b.ia()||(g=(new b.b.da).ec(a,c),g.setScale(d),f.add(g),b.b.e()&&(e=new Kinetic.Line({points:[660,570,i.x,i.y],stroke:"brown",strokeWidth:2,lineCap:"round"}),f.add(e)))};
b.on("Ladder.interrupt",function(){b.b.e()&&(b.R(e.attrs.points[1]),b.c(e.attrs.points[1]).to(i,1E3).call(function(){F.play(ub)}));b.P()});b.on("Ladder.introduceAgent",function(a){F.play(Db);b.setTimeout(function(){F.play(Eb);b.setTimeout(function(){a()},2E3)},2E3)});b.on(wa,function(c){d.on("mousedown touchstart",function(){b.c(d.attrs).to({rotation:8*Math.PI},1200).to({rotation:0});F.play(ib);a.sc()});f.on("mousedown touchstart",function(){b.c(f.attrs).to({rotation:8*Math.PI},1200).to({rotation:0});
F.play(jb)});c()});b.on(xa,function(){d.off("mousedown touchstart");f.off("mousedown touchstart")});b.on("Ladder.startAgent",function(a){F.play(Fb);b.setTimeout(function(){a();b.c(d.attrs).to({alpha:1},1E3);b.c(f.attrs).to({alpha:1},1E3)},2E3)});b.on(Ca,function(a){F.play(hb);b.setTimeout(a,1500)});b.on(Fa,function(a){b.mc(a)});b.on(Ba,function(){b.Ma()});b.on("Ladder.betterBecauseBigger",function(){F.play(b.Ka)});b.on("Ladder.betterBecauseSmaller",function(){F.play(b.La)});b.on("Ladder.hmm",function(){F.play(qb)});
b.on("Ladder.agentSuggestSolution",function(){b.setTimeout(function(){F.play(b.pa);b.setTimeout(function(){F.play(b.pa)},2E3)},2E3)});b.on("Ladder.tooLow",function(){F.play(b.gb);setTimeout(function(){F.play(b.hb)},2E3)});b.on("Ladder.tooHigh",function(){F.play(b.fb);setTimeout(function(){F.play(b.ib)},2E3)});b.on("Ladder.agentTooLow",function(){F.play(b.Ia)});b.on("Ladder.agentTooHigh",function(){F.play(b.Ha)});b.on("Ladder.picked",function(c,d){if(b.b.e()&&!a.k()&&!a.g()){var f=b.Oa(d.w);F.play(pb);
b.c(e.attrs.points[1]).wait(1500).to(f,3E3).wait(3E3).call(function(){b.p(d.w,c)}).wait(1E3).to(i,1E3)}else b.p(d.w,c)})}
function eb(c){var a=this;hc.call(this,"MtView",c);z.debug("Constructing MountainView",this.h);a.gb=Tb;a.fb=Sb;a.hb=Vb;a.ib=Ub;a.pa=Wb;a.Jc=Xb;a.Ia=$b;a.Ha=ac;a.Ka=Yb;a.La=Zb;a.Ub=bc;var b=r,d=p,f=r,g=new Kinetic.Layer,e=new Kinetic.Layer,i=[],l=new Kinetic.Group({x:400,y:600}),o=new Kinetic.Rect({width:50,height:50,fill:"blue",stroke:"black",strokeWidth:4,offset:{x:25,y:50}});Kinetic.pb=function(a,b){var c=new Kinetic.Group({x:a,y:b}),d=new Kinetic.Circle({fill:"red",stroke:"black",strokeWidth:4,
radius:20}),e=new Kinetic.Line({stroke:"black",strokeWidth:4,points:[0,20,0,65]});c.add(e);c.add(d);return c};a.s(function(){z.debug("Setting up MountainView","mt-view");a.d.add(e);a.d.add(g);var d=new Kinetic.Polygon({points:[50,600,350,600,150,100],fill:"gray",stroke:"black",strokeWidth:4});l.add(new Kinetic.Polygon({points:[0,0,100,0,110,-50,-10,-50],fill:"#993300",stroke:"black",strokeWidth:4}));for(var m=new W.N(730,180,140,140,2),q=0;6>q;q++)(function(d){var e=m.next(),e=new Kinetic.Group({x:e.x,
y:e.y}),l=new Kinetic.Group({x:40,y:40}),n=new Kinetic.Rect({width:140,height:140,fill:"yellow",strokeWidth:4,stroke:"black"});e.add(n);i.push(e);for(var q=0,o=0;o<=d;o++)3===o&&q++,l.add(new Kinetic.pb(30*o-81*q,30*q));e.add(l);e.r=n;e.Ca=l;e.on("mousedown touchstart",function(){b&&a.b.Ua()?(b=r,c.p(d+1)):a.b.Ta()&&!f&&(f=k,F.play(lb),setTimeout(function(){F.play(ob);setTimeout(function(){f=r},2E3)},2E3))});g.add(e)})(q);e.add(d);d=c.ea();for(q=0;q<d.length;q++){var w=new Kinetic.Line({points:[280-
24*q,430-60*q,280-24*q+100,430-60*q],stroke:"black",strokeWidth:4});e.add(w)}o.hide();g.add(o);g.add(l);a.on("frame",function(){g.draw()});a.Ga(g);a.Fa(a.getStage().getWidth()-500,430,g);e.draw()});a.P=function(){d();a.R(l.attrs);a.c(l.attrs).to({x:400,y:600})};a.on("Ladder.placeTarget",function(a){var d=c.M()-1;o.setX(280-24*d);o.setY(430-60*d);o.show();b=k;a.callback()});this.Oa=function(a){a=i[a-1];return{x:a.getX()+a.r.getWidth()/2,y:a.getY()+a.r.getHeight()/2}};this.p=function(b,c){var e=i[b-
1].Ca,f=i[b-1];f.r.setFill("red");var g=f.Ca.getX(),o=e.getY();d=function(){a.R(e.attrs);e.setX(g);e.setY(o);e.moveTo(f);f.r.setFill("yellow")};a.c(e.attrs).to({x:-Math.abs(400-f.getX())+20,y:600-f.getY()+-110},4E3).call(function(){e.moveTo(l);e.setX(20);e.setY(-110);e.moveDown();c()})};a.on("Ladder.approachLadder",function(b){a.c(l.attrs).to({x:280-24*(b.w-1)+100,y:430-60*(b.w-1)},2E3).call(b.callback)});a.on("Ladder.getTarget",function(b){F.play(cc);a.setTimeout(function(){F.play(dc)},2E3);a.c(o.attrs).to({x:l.getX()+
50,y:l.getY()+-25},1E3).call(function(){a.c(l.attrs).to({x:400,y:600},3E3);a.c(o.attrs).to({x:450,y:575},3E3).call(function(){a.c(o.attrs).to({x:550,y:600},2E3).call(b.callback)})})});a.on("Ladder.hasTarget",function(){a.b.e()||c.ka()});a.Ma=function(a){a.callback()};a.on("Ladder.resetScene",function(c){function e(){d!=p&&d();c.Ce&&(b=k);c.callback()}600!=l.getY()?a.c(l.attrs).to({x:400,y:600},2E3).call(e):e()});this.i(function(){z.debug("Tearing down MountainView",this.h);a.d.remove(e);a.d.remove(g)})}
function ic(c){c.x===j&&(c.x=0);c.y===j&&(c.y=0);c.min===j&&(c.min=1);c.max===j&&(c.max=6);c.step===j&&(c.step=1);c.width===j&&(c.width=2);c.ma===j&&(c.ma=s());c.H===j&&(c.H=10);c.ba===j&&(c.ba={x:0,y:0});c.S===j&&(c.S=1);for(var a=[],b=r,d=r,f={color:"black",blur:10,offset:[3,3],alpha:0.5},g=new W.N(c.ba.x,c.ba.y,c.ca+c.H,c.aa+c.H,c.width),e=new Kinetic.Group({x:c.x,y:c.y}),i=c.min;i<=c.max;i+=c.step)(function(i){function o(a,f){f===j&&(f=r);if(!d)if(!f&&b)c.$b(i);else if(f||!b){e.ga();c.ma(i);m.attrs.image=
c.Wb;m.attrs.shadow=p}}var n=g.next(),n=new Kinetic.Group({x:n.x,y:n.y}),m=new Kinetic.Image({image:c.button,width:c.ca,height:c.aa,shadow:f}),q=new Kinetic.Image({image:c.oa[i],scale:{x:c.S,y:c.S},offset:{x:c.oa[i].width/2,y:c.oa[i].height/2},x:c.ca/2,y:c.aa/2});n.on("mousedown touchstart",function(){o(0,r)});n.add(m);n.add(q);m.push=o;e.add(n);a[i]=m;a[i].Pa=n})(i);e.Xa=function(){for(var b=c.min;b<=c.max;b=b+c.step){a[b].attrs.image=c.button;console.log("shadow",f);a[b].Ie(f)}};e.ga=function(){b=
k};e.Oc=function(){b=r};e.qc=function(){d=k};e.Pb=function(){d=r};e.fc=function(b){return{x:e.getX()+a[b].Pa.getX()+a[b].getWidth()/2,y:e.getY()+a[b].Pa.getY()+a[b].getHeight()/2}};e.push=function(b){a[b].push(p,k)};return e}
function db(c){hc.call(this,"TreeView",c);var a=this,b=1/2.083168317,d,f,g,e,i,l=[],o,n,m,q,w,u=p,G,I,A=0,E={},J,S=a.getStage().getHeight()-160,ca=a.getStage().getHeight()-120,x={1:{x:100,y:40,rotation:-Math.PI/9},2:{x:100,y:100,rotation:Math.PI/11},3:{x:200,y:40,rotation:-Math.PI/12},4:{x:200,y:100,rotation:Math.PI/9}};a.gb=Hb;a.fb=Gb;a.hb=Jb;a.ib=Ib;a.pa=Kb;a.Jc=Lb;a.Ia=Ob;a.Ha=Pb;a.Ka=Mb;a.La=Nb;a.Ub=Qb;f=new ic({x:550,y:180,button:X.X,Wb:X.ob,ca:X.X.width,aa:X.X.height,H:15,$b:function(){F.play(lb);
a.setTimeout(function(){F.play(ob);a.setTimeout(s(),2E3)},2E3)},ma:function(b){a.b.Ua()&&c.p(b)},oa:{1:X.qb,2:X.rb,3:X.sb,4:X.tb,5:X.ub,6:X.vb},S:0.75});f.ga();n=new Kinetic.Layer;m=new Kinetic.Layer;a.getStage().add(n);a.getStage().add(m);g=new Kinetic.A.zb({x:240,y:580,scale:b},a);i=function(){e=a.setInterval(function(){l[c.L()-1].Gc(a)},4E3)};w=function(){a.clearInterval(e)};I=function(){u.xc(c.ka)};a.on(sa,function(){a.a(ta,{x:l[c.L()-1].getX(),y:l[c.L()-1].getY()})});a.on(Da,function(){f.qc()});
a.on(P,function(){f.Pb()});a.on(Q,function(){f.Oc()});a.on(Ea,function(){f.ga()});G=function(b){console.log(l);u=l[c.L()-1];a.c(u.attrs).wait(2E3).to({x:100,y:150,rotation:2*Math.PI},1E3).to({rotation:0}).to({y:E[c.M()].getY()+25,rotation:2*Math.PI*(7-c.M())},1E3).to({rotation:0}).call(b)};a.Ma=function(){u.wc();w();u.open();f.Xa();n.draw()};a.mc=function(b){var c=new Kinetic.Image({x:u.getX(),y:u.getY(),image:X.nb,width:128,height:128,offset:{x:64,y:64},scale:{x:0.1,y:0.1}});m.add(c);a.c(c.attrs.scale).to({x:1,
y:1},500).call(function(){a.c(c.attrs).to({y:200},2E3).call(b)})};a.on(ua,function(a){A+=1;G(a)});a.on(va,function(b){q=c.gc();a.c(g.attrs).to({y:480},2E3).to({rotation:-Math.PI/8,x:215},1E3).call(function(){console.log(E[2].getY());1<q?a.c(g.attrs).to({rotation:0,y:430},1E3).call(function(){2<q?(g.V(),a.c(g.attrs).to({y:E[q].getY()},500*q).call(function(){g.z();b()})):(g.z(),b())}):b()})});a.on(N,function(b){function c(){a.c(g.attrs).to({rotation:0,x:240,y:580},2E3).call(function(){f.Xa();b()})}
function d(b){a.c(g.attrs).to({rotation:-Math.PI/16,x:240,y:510},1E3).to({rotation:0,y:530},1E3).call(b)}function e(b){g.V();a.c(g.attrs).to({y:430},500*q).call(g.z).call(b)}2<q?e(function(){d(c)}):1<q?d(c):c()});a.on("Ladder.getTarget",function(b){g.Mc(function(){function c(){d+=1;2===d&&b()}var d=0;a.c(u.attrs).to({x:u.getX()+30,y:u.getY()-30}).wait(200).call(function(){F.play(Rb);g.Lc(c)}).to({x:650+75*A,y:ca,rotation:3*Math.PI},2E3).to({rotation:0}).call(c).call(function(){a.b.e()||(I(),i())})})});
a.on(L,function(){m.draw()});a.i(function(){a.getStage().remove(n);a.getStage().remove(m)});a.P=function(){a.R(g.attrs)};o=new Kinetic.Image({image:X.B,x:0,y:a.getStage().getHeight()-X.B.height,width:X.B.width,height:X.B.height});n.add(o);n.add(new Kinetic.Image({image:X.Jb,x:144,y:167}));a.Ga(m);a.on("Ladder.helpAgent",s());for(d=0;d<c.ea().length;d+=1)o=c.ea()[d],J=new Kinetic.Group({x:120,y:S-70*d}),E[o]=J;m.add(g);m.add(new Kinetic.Image({image:X.C,width:X.C.width,height:X.C.height,x:184,y:a.getStage().getHeight()-
X.C.height}));this.p=function(b,c){F.play(kb);a.b.Ta()&&f.push(b);c()};this.Oa=function(a){return f.fc(a)};n.add(new Kinetic.Image({x:370,y:-100,image:X.Ab}));m.add(f);a.Fa(a.getStage().getWidth()-248,a.getStage().getHeight()-100-252,0.8,m);(function(){var a;for(d=0;3>d;d+=1)a=new Kinetic.A.Eb({x:x[d+1].x,y:x[d+1].y,rotation:x[d+1].rotation,type:d%3+1,scale:b}),m.add(a),l.push(a)})(this);n.draw()}
function Z(c){Ka.call(this,c);var a=new function(){var a=[];this.c=function(c){W.rc(a,c)||a.push(c);return Tween.get(c)};this.removeTweens=function(a){Tween.removeTweens(a)};this.qa=function(){for(var c=0;c<a.length;c++)Tween.removeTweens(a[c])}};this.i(function(){z.debug("Tearing down","ViewModule");a.qa()});this.c=function(b){return a.c(b)};this.R=function(b){a.removeTweens(b)};this.getStage=t("d")};